### ISSUE TITLE
CFG Lock

### ISSUE THREAD

**Issue by Ormsher** [johnnync13/Xiaomi-Mi-Air#100]
After reading the documentation I found that I need to disable CFG lock but there is very little help online on how actually it should be done on locked down bios. If there is a way I think the documentation should be updated with the needed information.

**Comment by johnnync13** [comment]
i will make a tutorial soon. These days, i'm very stressed

**Comment by johnnync13** [comment]
@Ormsher https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/msr-lock

**Comment by johnnync13** [comment]
@Ormsher I have great news. Soon I do to this xiaomi mi air
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/issues/47
