### ISSUE TITLE
BCM94360CS2 to m2 ssd is it possible to?

### ISSUE THREAD

**Issue by leonidy-85** [johnnync13/Xiaomi-Mi-Air#103]
Has anyone had a good experience installing wifi BCM94360CS2 or similar in m2 slot ssd?

**Comment by yllwfsh** [comment]
I have tried, and I think several others did as well (@johnnync13 ?), but it seems this laptop is locked to only receive SSDs in the m.2 slots. It doesn't work.

Apart from that it physically doesn't fit very well either. The bottom panel is too close to the motherboard to fit a adapter + wifi card.

**Comment by johnnync13** [comment]
Is not possible. On Xiaomi 6200u first generation, and 7200u works well. On xiaomi notebook pro too, but on xiaomi mi air doesn't work

**Comment by leonidy-85** [comment]
I saw how they changed the wifi on xiaomi pro 15, and it seemed to work there.
![wifi](https://user-images.githubusercontent.com/5830485/77916460-c5ad6e00-72a1-11ea-85df-06852313f896.jpg)


The discussion was here.
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/31

**Comment by johnnync13** [comment]
the problem is on the bios @leonidy-85

**Comment by leonidy-85** [comment]
Then the counter question is, there is usb wifi that can do airdrop, airplay, my TP-LINK Archer T2U NANO can only use the Internet.

**Comment by johnnync13** [comment]
@leonidy-85 yes, works all because is native wifi card

**Comment by johnnync13** [comment]
I have Xiaomi notebook air 12.5 m3-6y30 with this card wifi

**Comment by songzhelun333** [comment]
> I have Xiaomi notebook air 12.5 m3-6y30 with this card wifi

Is that works well ? @johnnync13
