### ISSUE TITLE
 External 4k display with only 2k resolution

### ISSUE THREAD

**Issue by guoxianxian** [johnnync13/Xiaomi-Mi-Air#104]
I bought a 4k monitor and connected it with a DP to type c cable. The external 4k monitor only has a 2k resolution.

**Comment by johnnync13** [comment]
omg! You should change parameters on Hackintool and pull request to fix it for all users. I don't have this laptop yet

**Comment by yllwfsh** [comment]
@guoxianxian We need your help to fix this! I don't have the same/right hardware. You can read further at these links and if you figure it out please let us know how and share your config.plist. Thx!

https://1revenger1.gitbook.io/laptop-guide/prepare-install-macos/display-configuration#configuring-your-display-adapter-gpu
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by chanbaihai** [comment]
> I bought a 4k monitor and connected it with a DP to type c cable. The external 4k monitor only has a 2k resolution.

Hi,Do you resolve this problem now? since I have the same issue ,and I bought a 4K LG monitor but It only represent to 2k,If you have resolve this,Its really  kind of you to let me know.

**Comment by guoxianxian** [comment]
> > I bought a 4k monitor and connected it with a DP to type c cable. The external 4k monitor only has a 2k resolution.
> 
> Hi,Do you resolve this problem now? since I have the same issue ,and I bought a 4K LG monitor but It only represent to 2k,If you have resolve this,Its really kind of you to let me know.

我在远景轮胎发过贴，可以解决http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1851781&page=1&mobile=yes#pid50438789

**Comment by chanbaihai** [comment]
> > > I bought a 4k monitor and connected it with a DP to type c cable. The external 4k monitor only has a 2k resolution.
> > 
> > 
> > Hi,Do you resolve this problem now? since I have the same issue ,and I bought a 4K LG monitor but It only represent to 2k,If you have resolve this,Its really kind of you to let me know.
> 
> 我在远景轮胎发过贴，可以解决http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1851781&page=1&mobile=yes#pid50438789
我看过这个帖子了，但是那个脚本是小米 pro的，我这个是小米 air 13.3 I5 7代，用pro的脚本unlock_bios就出错了，你能帮我看下嘛，有偿的，我在淘宝都没找到能解决的
