### ISSUE TITLE
fan speed

### ISSUE THREAD

**Issue by flybeat246** [johnnync13/Xiaomi-Mi-Air#105]
sorry my bad English
Hi, everything is fine, but there is one problem.
fans work.
In Mac os, fans run from 40º C, because of this I always hear the noise of fans.
In Windows with software "notebook fan control", the fans are controlled from 60 º C,, and most of the time the laptop runs silently.
Is it possible to do the same in Mac OS?

**Comment by johnnync13** [comment]
yes! With smcio.kext but never I did this.. I can't help you

**Comment by flybeat246** [comment]
name exactly "smcio.kext"?
I can not find on the Internet any information on smcio.kext

**Comment by johnnync13** [comment]
@flybeat246 SMCSuperIO.kext
