### ISSUE TITLE
there  is something wrong with oc

### ISSUE THREAD

**Issue by west-shell** [johnnync13/Xiaomi-Mi-Air#106]
on start shows
OCS: No schema for MatchKernel at 7 index1
OCS: No schema for MatchKernel at 7 index1
OCS: No schema for MatchKernel at 7 index1
OCS: No schema for MatchKernel at 7 index1
....
OCS: No schema for MatchKernel at 13 index1
OCS: No schema for MatchKernel at 13 index1
OCS: No schema for ThirdPartyTrim at 7 index1
OCS: Failed to parse string field of type 2
OCS: Failed to parse string field of type 2
OCS: Failed to parse string field of type 1

Then I delete all the matchkernel and thirdpartytrim iterms in the config.list
it works well.
bu how to fix the string error?

**Comment by johnnync13** [comment]
Try last release with theme

**Comment by west-shell** [comment]
the new one is still have the same problem

**Comment by west-shell** [comment]
OCS: Failed to parse string field of type 2
OCS: Failed to parse string field of type 2
OCS: Failed to parse string field of type 1
This is caused because of the smbios item
I deleted it and replace those items with the simple.config
it works well now
btw, release 7.0.3 cant work.I used the 7.0.0

**Comment by johnnync13** [comment]
@west-shell you have to modify bios or modify config.plist
Open /EFI/OC/config.plist, find the following code:

<key>AppleCpuPmCfgLock</key>
<true/>
<key>AppleXcpmCfgLock</key>
<true/>
Change to:

<key>AppleCpuPmCfgLock</key>
<false/>
<key>AppleXcpmCfgLock</key>
<false/>

**Comment by johnnync13** [comment]
@west-shell whithout modify cfg in config.plist, try to do a pull request

**Comment by west-shell** [comment]
thank you

**Comment by west-shell** [comment]
the wrong smbios items are FirmwareFeatures FirmwareFeaturesMask and one of the empty item. 
new wrong item ShrinkMemoryMap

**Comment by west-shell** [comment]
the wifi is updated .I hope you can update it .add it to the oc kext as default sounds good .brw the oc released new version .I dont konw if it is updated .
thank you.

**Comment by johnnync13** [comment]
@west-shell wifi still can't connect only scan. Now, I'm trying to migrate SSDT* to OpenCore method fixes

**Comment by west-shell** [comment]
the issues of the itlwm reported that the kext works. the speed maybe limited but works.

**Comment by west-shell** [comment]
https://github.com/n-d-k/NdkBootPicker
this is a good picker

**Comment by johnnync13** [comment]
@west-shell https://github.com/AppleIntelWifi/adapter this is better because itlwm is based on openbsd

**Comment by west-shell** [comment]
He is rewriting. That project seems far from work. 
The picker I mentioned above is a nice gui boot picker with background and icons. 
Have you test it.
