### ISSUE TITLE
10.15.4 opencore not working

### ISSUE THREAD

**Issue by lifsux** [johnnync13/Xiaomi-Mi-Air#107]
10.15.4 opencore not working

**Comment by yllwfsh** [comment]
> 10.15.4 opencore not working

Can you try version 7.0.2? 
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.0.2

7.0.3 is only suitable if you have done cpu patches described in https://github.com/johnnync13/Xiaomi-Mi-Air/issues/88
