### ISSUE TITLE
Mi Air 2018 i5 BIOS mod

### ISSUE THREAD

**Issue by festo95** [johnnync13/Xiaomi-Mi-Air#108]
Hi I'm looking to apply the bios patches to have the best compatibility but I have a question:
Can I follow your guide even if I have a Mi Air 2018 i5 8250U (with Mx150) instead of your i7 8550U?

**Comment by yllwfsh** [comment]
@festo95 What is your BIOS version number?

**Comment by yllwfsh** [comment]
If your BIOS version is one of the ones here: https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS/BIOS_Archive

and if your Motherboard is TM1703 it should just work

**Comment by johnnync13** [comment]
@yllwfsh I found this. It is more easy now https://github.com/hackintosh-guides/vanilla-laptop-guide

**Comment by festo95** [comment]
ok I checked my board is TM1703 and my BIOS is XMAKB3M0P100B
Should I Update the bios before or not?

**Comment by johnnync13** [comment]
@festo95 yes

**Comment by yllwfsh** [comment]
> ok I checked my board is TM1703 and my BIOS is XMAKB3M0P100B
> Should I Update the bios before or not?

But, flashing BIOS can be risky, so if you don't want to risk anything, don't do it. I'm still on XMAKB3M0P100B as well. But yes, like @johnnync13 said, if later you do flash the BIOS, you'd need to make the modifications again.

**Comment by festo95** [comment]
Update to XMAKB3M0P1710 and patches applied everything works just fine!
the only problem was windows defender that prevents the script from running but I disabled it 
Thanks for your quick reply

**Comment by yllwfsh** [comment]
@festo95 Thanks for your feedback. I decided also to try it! Now on the 1710 BIOS with reapplied patches as well and everything is still great. Thx for reminding me about Defender, i'll add it to the Howto.
