### ISSUE TITLE
TrackPad not working in most versions of macOS

### ISSUE THREAD

**Issue by Notics-Seed** [johnnync13/Xiaomi-Mi-Air#109]
v7.1.1,macOS10.15.It's trackpad doesn't work.

**Comment by yllwfsh** [comment]
Using Clover/OpenCore?

Did you try F9 key or Fn+F9 to switch on/off trackpad?

**Comment by yllwfsh** [comment]
@Notics-Seed Which release version worked the last time you checked?

**Comment by Notics-Seed** [comment]
emmm，The sys version is 10.15(19A583), Clover, I haven't try Fn+F9, sry I don't know it before. Let me try. It has been a long time since my last time use macOS on the laptop. The bulid seemed to be v6.7.1

**Comment by Notics-Seed** [comment]
> 
> 
> @Notics-Seed Which release version worked the last time you checked?

I just tried Fn+F9, but it doesn't work. (Sry my English is poor.)

**Comment by yllwfsh** [comment]
It seems the latest drivers in release v7.1.1 are only suitable for the latest macOS 10.15.4. You could try updating your macOS or use an older release version like v6.7.1

**Comment by johnnync13** [comment]
@Notics-Seed @yllwfsh trackpad is being modified with big changes, so I will wait for them to do the release since sometimes it doesn't work.

**Comment by johnnync13** [comment]
@yllwfsh all kexts is out less voodooi2c. Update all please.

**Comment by yllwfsh** [comment]
@Notics-Seed @johnnync13 You can now try https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2 to see if it's better. Here everything tested and still working.

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2.1
