### ISSUE TITLE
Weird sound when start up.

### ISSUE THREAD

**Issue by RAXEAL** [johnnync13/Xiaomi-Mi-Air#11]
There is a weird sound every time when I start up macOS via clover.
I suppose it's a function of the new clover, but how can I customize it or turn it off?
Thx a lot for your hardwork.

**Comment by vimcaw** [comment]
Same question, I have tried many way from google, but no one can solve it.

RAXEAL <notifications@github.com> 于2019年1月15日周二 下午10:52写道：

**Comment by vimcaw** [comment]
v2.12 has fixed this problem.

**Comment by johnnync13** [comment]
remove in Xiaomi theme .wav file
