### ISSUE TITLE
The mpcpu.sh give me some wrong and waring and it not work 

### ISSUE THREAD

**Issue by lhxs123** [johnnync13/Xiaomi-Mi-Air#110]
I use the voltage_unlock.cmd unlock the voltageshift .when I reboot on macos . the   temperature is  
 straight forward 80°c  I use the mpcpu.sh .bug have something waring and it not work 

First : the script on my mac 10.15.4 have this worng
正在下载相关文件...
Archive:  VoltageShift.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of VoltageShift.zip or
        VoltageShift.zip.zip, and cannot find VoltageShift.zip.ZIP, period.
下载完成
正在拷贝文件到目标路径...
Password:
cp: ./voltageshift: No such file or directory
cp: ./VoltageShift.kext: No such file or directory
正在修复权限...
正在清理临时文件...
清理完成
主程序安装完成 3S后返回主菜单

Second:I get this waring 
降压选项 ?
(1) 降压 0.09V
(2) 降压 0.05V

输入你的选择 [1~2]: 1
mpcpu.sh: line 270: lownt: command not found

and 

VoltageShift offset Tool
--------------------------------------------------------------------------
Before set power limit:
Warning: MSR and memory values are not equal
Short term power: 44.000 W, 0.002 s, enabled
Long term power: 25.000 W, 28.000 s, enabled
short_time = 0.001000, time = 0xc0
long_time = 28.000000, time = 0xdc
value to write: 0xc0816000dd8078
After set power limit:
Short term power: 44.000 W, 0.002 s, enabled
Long term power: 15.000 W, 28.000 s, enabled
--------------------------------------------------------------------------
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
设置完成
Tip: 默认选项不包含电压设置！！

**Comment by lhxs123** [comment]
I read the script . 

mkdir -p temp
curl -fsSL "$download_dir" -O || networkWarn
unzip VoltageShift.zip

creap temp file folder . Did not dowload the VoltageShift.zip
so unzip will not have this file

**Comment by lhxs123** [comment]
The lownt function can't find the define .I feel it is the reason of   scrip  can't work in my machine .

lownt
                function sysdede() {
                interface
                choice3

![image](https://user-images.githubusercontent.com/22124708/78630003-2e60a000-78cb-11ea-8e42-445a627186fc.png)

**Comment by yllwfsh** [comment]
Fixed now: https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2.1

**Comment by lhxs123** [comment]
> Fixed now: https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2.1

thanks . Now I already succesd  mpcpu.sh and all  functions can work normaly.
