### ISSUE TITLE
HDMI disconnected after wake

### ISSUE THREAD

**Issue by XYSheldon** [johnnync13/Xiaomi-Mi-Air#111]
The HDMI display **(HDMI Jack on the left, not Type-C adaptor)** will be automatically disconnected (no output) after wake from hiberrate, and only reconnect the cable can solve this.

Booting macOS with HDMI plugged also causes same problem. To connect it, i have to re-plug it after boot finished.

- Clover EFI is used.
- Xiaomi Air 13.3 2018 i7-8550u
- macOS 10.15.4
- I found such problem since _**about**_ release v7.0.0

**Note:**
- The DisplayPort (Type-C adaptor) does not have this issue.
- The VGA (Type-C adaptor) does not have this issue.

**Comment by leonidy-85** [comment]
This problem appeared for me on 10.15.4, on 10.15.3 and 10.15.2 it was not.

Clover EFI, release v7.2
Xiaomi Air 13.3 2017 i5-7200U
macOS 10.15.4

**Comment by yllwfsh** [comment]
I also suspect it has more to do with macOS 10.15.4 than with the configs. Might also be related to https://github.com/johnnync13/Xiaomi-Mi-Air/issues/104

**Comment by johnnync13** [comment]
is only to add two parameters...

**Comment by vimcaw** [comment]
Same for me on latest OpenCore EFI and 10.15.4, After unlocking the CFG, problem still exist.

**Comment by vimcaw** [comment]
I found the reason:

* https://github.com/acidanthera/bugtracker/issues/783
* [关于更新macOS 10\.15\.4 以后出现的HDMI接口唤醒的问题跟进\-远景论坛\-微软极客社区](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1850890&highlight=HDMI)
* [WEG1\.38更新，解决笔记本10\.15\.4外接HDMI不能亮屏问题\-远景论坛\-微软极客社区](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1852184&highlight=HDMI)

**Comment by vimcaw** [comment]
After testing, #128 can fix this.

**Comment by vimcaw** [comment]
This problem should be thoroughly fixed by [#142](https://github.com/johnnync13/Xiaomi-Mi-Air/pull/142).
