### ISSUE TITLE
About CFG unlock

### ISSUE THREAD

**Issue by HatsuneMiku-01** [johnnync13/Xiaomi-Mi-Air#112]
I try to run "bios_unlock.cmd", but doesn't work. ( i had run PowerShell before) 
The error code :
 “Xiaomi Mi Notebook Pro BIOS write lock patch by _Cyb_
Tested on 0603 BIOS
Now parsing Variable Information.
LoadDeviceDriver fail, GetLastError = 0x2
Failed to get bios data!
Fail to get Variable Information.
Failed to read variables! "
thanq

**Comment by yllwfsh** [comment]
@HatsuneMiku-01 Check Windows Defender or your Virus scanner. The program is probably blocked
