### ISSUE TITLE
catalina : no internet connection

### ISSUE THREAD

**Issue by lastmethod** [johnnync13/Xiaomi-Mi-Air#113]
Hey there i am trying to install catalina , i did all the steps but i am keep getting " An internet connection is required to install mackOS " even when i use usb 3 ethernet adapter.
can you help me please?

thanks

**Comment by yllwfsh** [comment]
@lastmethod Unfortunately you have to find a USB ethernet adapter that is officially supported by macOS

**Comment by lastmethod** [comment]
Thanks for the response ,
i googled it a lot and i end it up with this one Digitus USB 3.0 to Ethernet 10/100/1000 Adapter [DN-3023] which lots of people says that is 100% compatible !! but it seems not right ?
So the only way is to find an other one ? not find any kekt etc ?

**Comment by 0x47726567** [comment]
Just a heads up, you can use an android phone with usb tethering to install macOS. You just need to add the HoRNDIS kext.

**Comment by lastmethod** [comment]
hmm thats interesting , i have iphon xs , is there any kext to use ?? really thanks and sorry if i am wasting your time

**Comment by yllwfsh** [comment]
@lastmethod Just enable Personal Hotspot in settings and connect via USB, the iPhone series should be compatible without kext

**Comment by 0x47726567** [comment]
@yllwfsh We could mention those methods in the Readme

**Comment by yllwfsh** [comment]
@0x47726567 Good idea, but I have limited time right now. If you like you can make a pull request to add stuff to the readme, otherwise i'll do it in the next few days

**Comment by lastmethod** [comment]
@yllwfsh i just did that but i does not working. The only thing i can see on the Network utility is the ethernet (en0) and still cant access internet !! waht am i doing so wrong ...

**Comment by yllwfsh** [comment]
@lastmethod The usb card you have is compatible with macOS, but uses the AX88179 which requires a kext driver. You could try adding it to your Clover/OpenCore kexts folder and then try to boot the installer.

[AX88179_178A_macOS_10.15_above_Driver_Installer_v2.16.0.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4462063/AX88179_178A_macOS_10.15_above_Driver_Installer_v2.16.0.zip)

**Comment by yllwfsh** [comment]
Here is the zipped Kext by itself:

[AX88179_178A.kext.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4462070/AX88179_178A.kext.zip)

**Comment by lastmethod** [comment]
@yllwfsh ok really really thanks for the help and your time!!!! i really appreciate it !!!
last question , the zip find that you just send me has not any kekt file and i have only windows box, how can i add the kekt file to kekts folder ? or just add the .dmg file ?

**Comment by lastmethod** [comment]
1000000 thanks i have no words :)

**Comment by yllwfsh** [comment]
@lastmethod are you using Clover or OpenCore?

**Comment by lastmethod** [comment]
shall i give this name to the folder AX88179_178A.kext ? on kekts folder.

**Comment by yllwfsh** [comment]
@lastmethod Yes you can leave the name as it is and put it in the same folder as the other kexts

**Comment by yllwfsh** [comment]
@lastmethod Be aware that in this case, Clover is better to use. If you will use OpenCore, you need to add the AX88179_178A.kext to the config.plist as well. So I recommend using Clover to try installing macOS

**Comment by lastmethod** [comment]
i am using Clover but still nothing :( i add the kekt folder but still no internet access

**Comment by yllwfsh** [comment]
@lastmethod Can you share a screenshot of your kext folder structure?

**Comment by lastmethod** [comment]
![kekt](https://user-images.githubusercontent.com/55323033/79001284-dc33af00-7b56-11ea-91cc-0c26af5eb3bd.png)

**Comment by lastmethod** [comment]
ok i am an idiot i thing i fix it i had not the folder contents inside that kekt folder ...

**Comment by yllwfsh** [comment]
@lastmethod That looks good. Make sure the USB adapter is connected directly to the laptop **while booting**, avoid using USB hubs. So your Clover USB stick in one port, your USB LAN adapter in the other, then start the laptop.

**Comment by yllwfsh** [comment]
@lastmethod Working now?

**Comment by lastmethod** [comment]
YEAH !!! i am installing it right now !!! after installation continue with the guide and i will be ok ? or after installation i am ready to run the os ?

**Comment by yllwfsh** [comment]
@lastmethod Follow the guide to move your Clover EFI folder to the ESP of your SSD. Then you can boot without the USB stick.

**Comment by lastmethod** [comment]
ok nice thanks again !!!!! i have no words!!
