### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by maklore74** [johnnync13/Xiaomi-Mi-Air#115]
Hello everybody,
I have a problem with the bluetooth of my Xiaomi mi notebook 13.3 2018 (Clover 5109) and I have latest copy of johnnync13 files.
The module starts but I cannot associate any devices. In the information on this Mac I have:

> Apple Bluetooth software version: 7.0.4f6
   Hardware, functionality and settings:
   Address: 00-00-00-00-00-00
   Bluetooth low power supported: No
   Supported Handoff: No
   Instant Hotspot supported: No
   Manufacturer: Ericsson
   Connection: USB
   Firmware version: 0.0 (0.0)
   Bluetooth status: Active
   Automatic pointing device search: On
   Remote reactivation: Active
   Manufacturer ID: 0x8087
   Product ID: 0x0A2B
   Bluetooth Spec Core: 1.0b (0x0)
   HCI revision: 0x00
   LMP version: 1.0b (0x0)
   LMP subversion: 0x00
   Automatic keyboard search: Active
I hope someone can help me.
thank you

**Comment by johnnync13** [comment]
report to https://github.com/zxystd/IntelBluetoothFirmware

**Comment by maklore74** [comment]
thanks
