### ISSUE TITLE
boot crash！fail

### ISSUE THREAD

**Issue by lifsux** [johnnync13/Xiaomi-Mi-Air#116]
panic(cpu 2 caller 0xffffff800344c32a): Kernel trap at 0xffffff7f86fb942f, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x00000000197ca000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x0000000000000000, RDX: 0x0000000000000001
RSP: 0xffffff81225dbbc0, RBP: 0xffffff81225dbbd0, RSI: 0x0000000000000000, RDI: 0xffffff80e753ea80
R8:  0x0000000000000001, R9:  0x0000000000000001, R10: 0x00000002bd845cc9, R11: 0xffffff8003c0a1c0
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff802852f680, R15: 0xffffff80e74df000
RFL: 0x0000000000010246, RIP: 0xffffff7f86fb942f, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Backtrace (CPU 2), Frame : Return Address
0xffffff81225db620 : 0xffffff80033215cd 
0xffffff81225db670 : 0xffffff800345a3c5 
0xffffff81225db6b0 : 0xffffff800344bf7e 
0xffffff81225db700 : 0xffffff80032c7a40 
0xffffff81225db720 : 0xffffff8003320c97 
0xffffff81225db820 : 0xffffff8003321087 
0xffffff81225db870 : 0xffffff8003ac2c7c 
0xffffff81225db8e0 : 0xffffff800344c32a 
0xffffff81225dba60 : 0xffffff800344c028 
0xffffff81225dbab0 : 0xffffff80032c7a40 
0xffffff81225dbad0 : 0xffffff7f86fb942f 
0xffffff81225dbbd0 : 0xffffff7f86fb99bd 
0xffffff81225dbc00 : 0xffffff7f86fb9718 
0xffffff81225dbc70 : 0xffffff7f86fcc03d 
0xffffff81225dbd30 : 0xffffff7f86fd7c13 
0xffffff81225dbde0 : 0xffffff8003a08c06 
0xffffff81225dbe40 : 0xffffff8003a08741 
0xffffff81225dbef0 : 0xffffff8003a07ade 
0xffffff81225dbf50 : 0xffffff8003a0a296 
0xffffff81225dbfa0 : 0xffffff80032c713e 
      Kernel Extensions in backtrace:
         com.zhong.AppleIntelWiFi(1.0)[E9AFB6BC-7D2B-3E9B-B799-658E962DCD55]@0xffffff7f86f90000->0xffffff7f86ff0fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f83f01000
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[043696D2-853D-3775-A87F-79C42F324EEB]@0xffffff7f86e35000
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[3F6EDFDE-6EF7-38D8-8006-C4EE6DB4D4B5]@0xffffff7f844bf000

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000003000000
Kernel text base: 0xffffff8003200000
__HIB  text base: 0xffffff8003100000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 11769641315

**Comment by yllwfsh** [comment]
Remove the wifi kext and try rebooting. The wifi kexts are not ready to be used during boot. Too unstable for now
