### ISSUE TITLE
Unable to detect boot media

### ISSUE THREAD

**Issue by fatboy32** [johnnync13/Xiaomi-Mi-Air#119]
Hello There,

Thanks for your detailed instructions.

I am new to installing hackintosh systems so please do excuse me if my problem is not valid or just a misunderstanding on my part.

I have a Xiaomi Mi Notebook Air 13 2018 and have purchased an additional Sata SSD which I am trying to install mac os on. However when making the bootable drive it is undetected by the Xiaomi laptop on startup. When using makeinstall.bat it seems to produce mbr formatted drives, I thought this was the problem so I tried getting it to use GPT instead but it would not run through the rest of the process to make a bootable usb. Also it appears when it makes a bootable usb via mbr format only the 200mb partition contains files. I am trying to use Opencore method.

Really wanting to get this system working and am not sure what I am doing wrong, can you help please?

Thanks in advance!

**Comment by yllwfsh** [comment]
Hi @fatboy32,

I'm glad you're trying to hackintosh your laptop, great to see new users here.

When making the bootable USB from windows there's a couple things to note:
* Don't mind the partition format, it's doing all kinds of weird things to make the macOS disk from Windows. Kudos to the guy that made the scripts!
* It's normal that only the BOOT partition seems to contain files. As long as you followed the script and dropped in the path to the macOS recovery files from the gibMacos scripts everything is fine.
* When copying in the EFIOC folder, make sure to rename it to EFI (and delete the existing folder on there)
* When rebooting the laptop, it will restart back to windows, so make sure to shut down, then start the laptop and immediately hit F2 to go to bios, set the usb stick as default boot drive and then reboot. It should start the OpenCore bootloader. From there you can start the Installation. You might need to attach a natively compatible USB ethernet adapter (e.g. from Apple) or compatible usb-c dock to complete the Catalina installer.

**Comment by yllwfsh** [comment]
@fatboy32 if you have a USB network adapter that is based on the AX88179 chip, you might want to use clover bootloader instead and include the driver for it as described here: https://github.com/johnnync13/Xiaomi-Mi-Air/issues/113

**Comment by fatboy32** [comment]
I got it working in clover and then after the latest changes to the EFI for OC I was able to reinstall it with opencore. All good now, just having issues with no wifi module being detected (to be expected as this is still under development) and HDMI not working properly.
