### ISSUE TITLE
Bluethooth mouse pairing issu

### ISSUE THREAD

**Issue by Th3G0sT** [johnnync13/Xiaomi-Mi-Air#120]
Hello, first off all amazing job!! well i tell you, i have succesfully installed mac os catalina on the xiaomi mi air 2018 (core i 5 modle), evrithing works great but the bluethooth. I have the microsoft arc mouse ( a bluethooth mouse ) when i try to connect it, bluethooth settings go crazy and wont connect. What's interesting is that it works fine with a couple bluethooth speakers i tried, and i olso have a bluethooth usb arround ( BLT 4.0)  with if i connect it to the hackintosh, ind try to pair the mouse, it suddenly connects with no issues. 

Thank you for your time!!

**Comment by johnnync13** [comment]
report to https://github.com/zxystd/IntelBluetoothFirmware
