### ISSUE TITLE
Can't switch from Clover to OC

### ISSUE THREAD

**Issue by CamilloCorleone** [johnnync13/Xiaomi-Mi-Air#123]
Hi, 
with the latest release (7.3.7) i tried to switch from Clover to OC.
What I do: 
- delete BOOT and CLOVER folders in EFI partition (leaving APPLE and MICROSOFT folders untouched)
- copied BOOT and OC folders in EFI partition

From BIOS I can choose between two "WINDOWS" (but it was the same with Clover). 
- first one goes directly to Windows
- second one, that previously linked to Clover, now opens a new BIOS window asking which system to boot, and then again I can choose between two windows.

There is no way to access to OC. 
Is there something wrong in what I'm doing? 

Now, mounting EFI from Windows, I replaced BOOT&OC folders with BOOT&CLOVER and it works again. 

Thank you!

**Comment by johnnync13** [comment]
I update OC now. I think that now works again

**Comment by CamilloCorleone** [comment]
Sorry, it is still not working.
Now it seems to start but says:

**> OCS: no schema for protocols at index 5**
