### ISSUE TITLE
OC in latest version not working

### ISSUE THREAD

**Issue by profuckerbro** [johnnync13/Xiaomi-Mi-Air#124]
Hey johnny, I can confirm the new rebased OC is not booting. i already have CFG lock Voltages etc. disabled. 
Clover works fine here. Even got the installation to work without any ethernet-adapter.

 (pro-tip: I installed Catalina over vmware last time. you can create a partition with the real installation media, and select it in vmware workstation as physical disk (with the vmware mac os patcher), which will install because vmware ethernet works with the install media.)

**Comment by johnnync13** [comment]
I know. I will fix soon

**Comment by profuckerbro** [comment]
@johnnync13 i got it to work by changing the value

<key>PickerMode</key>
<string>External</string>

to internal. maybe the external "picker" is missing or the issue. 
do you reccomend any guide/documentation for OC and its boot entries? trying to triple-boot W10, catalina and pop OS (ubuntu-based distro, doesnt use GRUB to boot), and dont want to "F12" every time... have a good day!

**Comment by profuckerbro** [comment]
This is my "edited" config.plist for OC:
(i think i changed some other values while experimenting with OC, but i think the key problem is the "PickerMode" value.)
Thank you for your wonderful work!
[config.txt](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4513653/config.txt)

**Comment by johnnync13** [comment]
@profuckerbro may you do pull request? I don't have mucho time these days by university

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.3.9
