### ISSUE TITLE
latest OC can not boot

### ISSUE THREAD

**Issue by paranoiagu** [johnnync13/Xiaomi-Mi-Air#125]
I can not boot since this commit: c39ff8f9e2bd039971b7c1a2edff6af1cf2fe245.
I saw this first: OCS: No schema for Protocols at 5 Index!
then i saw this: Boot Succeeded - EFI Hard Drive (INTEL SSDXXXXX)
then go to the BIOS boot device selector.

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.3.9
