### ISSUE TITLE
Trackpad issues in last releases

### ISSUE THREAD

**Issue by CamilloCorleone** [johnnync13/Xiaomi-Mi-Air#129]
Hi,
I always used Clover, now I tried both Clover and OC and in the last releases:

- Clover: issues with trackpad (i.e. gestures not working, scrolling not working, etc)
- OC: trackpad doesn't work

Thank you for your work!

**Comment by zyj-nanjing** [comment]
i have the same problem

**Comment by yllwfsh** [comment]
@CamilloCorleone @zyj-nanjing Sorry to hear that. I'd love to help to fix it, but this is more @johnnync13 's specialty. I would love to learn more about the ACPI stuff though. @johnnync13 Could you maybe publish the source files for the ACPI SSDT mods in a folder here on this repo? Then I can have a look at them.

**Comment by paranoiagu** [comment]
![image](https://user-images.githubusercontent.com/1732758/80210388-4758a780-8666-11ea-8ad6-48c0bb7464f1.png)

I use OC. my trackpad works great.
my notebook is Xiaomi Notebook Air 2018 13.3" i7-8550u.

**Comment by 0x47726567** [comment]
Did you try refreshing kext cache? AFAIK it fixes it.

**Comment by yllwfsh** [comment]
That's a good idea. @CamilloCorleone @zyj-nanjing execute this in Terminal:

```
sudo chmod -R 755 /System/Library/Extensions/
sudo chown -R root:wheel /System/Library/Extensions/
sudo chmod -R 755 /Library/Extensions/
sudo chown -R root:wheel /Library/Extensions/
sudo touch /System/Library/Extensions/
sudo touch /Library/Extensions/
sudo kextcache -i / && sudo kextcache -u /
```

**Comment by zyj-nanjing** [comment]
@yllwfsh  ok

**Comment by 0x47726567** [comment]
@yllwfsh Having the source files for the ACPI SSDT mods is a good idea though as we can poke around and improve things.

**Comment by johnnync13** [comment]
you can disassembling with iasl. To do the fixes I use OC daliansky fixes and dortania guide
https://github.com/daliansky/OC-little
https://github.com/dortania

**Comment by yllwfsh** [comment]
@johnnync13 I tried that but it gave me an error:

![image](https://user-images.githubusercontent.com/43885719/80217509-1a919980-8640-11ea-9b10-cc1fe05daafa.png)

**Comment by johnnync13** [comment]
you have to use https://github.com/acidanthera/MaciASL/releases/tag/1.5.7
if you want to do in terminal with homebrew: 
brew install acpica 
iasl -dl *.aml

**Comment by yllwfsh** [comment]
@johnnync13 Whoops yes you're correct. I had that one, but apparently there was an older version somewhere deep in a folder on my mac and of course macOS likes to use that one 😂

**Comment by CamilloCorleone** [comment]
> That's a good idea. @CamilloCorleone @zyj-nanjing execute this in Terminal:
> 
> ```
> sudo chmod -R 755 /System/Library/Extensions/
> sudo chown -R root:wheel /System/Library/Extensions/
> sudo chmod -R 755 /Library/Extensions/
> sudo chown -R root:wheel /Library/Extensions/
> sudo touch /System/Library/Extensions/
> sudo touch /Library/Extensions/
> sudo kextcache -i / && sudo kextcache -u /
> ```

Tried but with Clover it still doesn't work.
If I go into Settings-Trackpad it says "waiting for Bluetooth trackpad detection...".

**Comment by johnnync13** [comment]
@yllwfsh yes! Because this tool was born with Rehabman. But now use property of openCore

**Comment by johnnync13** [comment]
> > That's a good idea. @CamilloCorleone @zyj-nanjing execute this in Terminal:
> 
> > 
> 
> > ```
> 
> > sudo chmod -R 755 /System/Library/Extensions/
> 
> > sudo chown -R root:wheel /System/Library/Extensions/
> 
> > sudo chmod -R 755 /Library/Extensions/
> 
> > sudo chown -R root:wheel /Library/Extensions/
> 
> > sudo touch /System/Library/Extensions/
> 
> > sudo touch /Library/Extensions/
> 
> > sudo kextcache -i / && sudo kextcache -u /
> 
> > ```
> 
> 
> 
> Tried but with Clover it still doesn't work.
> 
> If I go into Settings-Trackpad it says "waiting for Bluetooth trackpad detection...".

You can use older fixes of trackpad in clover. I don’t use Clover anymore

**Comment by yllwfsh** [comment]
Maybe when I have some time later today or tomorrow i'll test all of the Clover/OC trackpad issues

**Comment by CamilloCorleone** [comment]
Tried also with OC, it's the same.
It says "No trackpad found" if I disable bluetooth.

**Comment by tk109** [comment]
徳永 敏さんがあなたを予約されたZoomミーティングに招待しています。

トピック: [johnnync13/Xiaomi-Mi-Air] Trackpad issues in last releases (#129)

Zoomミーティングに参加する
https://zoom.us/j/99655459040

ミーティングID: 996 5545 9040
パスワード: 819981

**Comment by johnnync13** [comment]
trackpad works perfectly....
