### ISSUE TITLE
How to turn off Duang!!!!!!!  sound

### ISSUE THREAD

**Issue by linlinsunny** [johnnync13/Xiaomi-Mi-Air#13]
How to turn off Duang!!!!!!!  sound

**Comment by vimcaw** [comment]
It has been turned off on v2.12.

**Comment by influenist** [comment]
How did accomplish the sound via EFI? I now use different method.

**Comment by vimcaw** [comment]
You can use the diskutil tool to mount the EFI partition in the Terminal, and open Finder, locate EFI partition, delete the Clover folder and copy the latest Clover folder from this repository, and just reboot.

**Comment by johnnync13** [comment]
@influenist is with new clover and audiodxe.. Now I'm working in bios mod to enable wifi m.2

**Comment by vimcaw** [comment]
@johnnync13 what is the audiodxe? I can't get anything from Google.
