### ISSUE TITLE
KP after boot

### ISSUE THREAD

**Issue by terberes** [johnnync13/Xiaomi-Mi-Air#130]
A kernel panic occurs several minutes after booted and logged in.

Here are several panic log files.
[KPFirst.log](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4531057/KPFirst.log)
[KPSecond.log](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4531058/KPSecond.log)

**Comment by yllwfsh** [comment]
@terberes What type of NVMe disk are you using? On Opencore or Clover?

**Comment by terberes** [comment]
I use OpenCore.
My macOS is installed on second SATA drive.

**Comment by yllwfsh** [comment]
Is your primary NVMe SSD a Samsung PM981? Do you have NVMeFix.kext enabled?

**Comment by terberes** [comment]
Yes, my SSD is PM981 and I use latest OpenCore release with NVMeFix enabled
I do not really need the NVMe drive in macOS, so can I just totally disable this drive in OpenCore?
I googled some solutions online, most of them are involving DSDT editing

**Comment by johnnync13** [comment]
It is strange, are you using OC? I don't update clover because OC works better
