### ISSUE TITLE
Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily.

### ISSUE THREAD

**Issue by KrimskiyMaxim** [johnnync13/Xiaomi-Mi-Air#131]
Hi! I use v7.4.1 and OpenCore. Faced a problem. Every night (3 days) I use sleep on my laptop, and by morning I find out that it is turned on (the screen is dark and does not respond). Next, I turn off the laptop, holding the power button for a long time. And by the way, when you turn on the keyboard does not work.

**Comment by KrimskiyMaxim** [comment]
panic(cpu 0 caller 0xffffff8002a91b2c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x1062e.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff8121cab900 : 0xffffff80024471e8 
0xffffff8121eabc40 : 0xffffff80023433f1 
0xffffff8121eabcb0 : 0xffffff8002341c2f 
0xffffff8121eabd00 : 0xffffff80024442e9 
0xffffff8121eabd40 : 0xffffff8002443b4b 
0xffffff8121eabd70 : 0xffffff8002a2d048 
0xffffff8121eabda0 : 0xffffff8002a2ff59 
0xffffff8121eabe00 : 0xffffff8002a152ea 
0xffffff8121eabea0 : 0xffffff8002a14c14 
0xffffff8121eabec0 : 0xffffff8002363545 
0xffffff8121eabf40 : 0xffffff8002363071 
0xffffff8121eabfa0 : 0xffffff80022c713e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxagdc=0

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000002000000
Kernel text base: 0xffffff8002200000
__HIB  text base: 0xffffff8002100000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 2380932111410

**Comment by Creedowl** [comment]
I've just switched to opencore and had the same problem. And when I turn on the keyboard doesn't work, that's really weird

```text
panic(cpu 0 caller 0xffffff8010291b2c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x8f80.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff8132bd3900 : 0xffffff800fc471e8 
0xffffff9144f2bc40 : 0xffffff800fb433f1 
0xffffff9144f2bcb0 : 0xffffff800fb41c2f 
0xffffff9144f2bd00 : 0xffffff800fc442e9 
0xffffff9144f2bd40 : 0xffffff800fc43b4b 
0xffffff9144f2bd70 : 0xffffff801022d048 
0xffffff9144f2bda0 : 0xffffff801022ff59 
0xffffff9144f2be00 : 0xffffff80102152ea 
0xffffff9144f2bea0 : 0xffffff8010214c14 
0xffffff9144f2bec0 : 0xffffff800fb63545 
0xffffff9144f2bf40 : 0xffffff800fb63071 
0xffffff9144f2bfa0 : 0xffffff800fac713e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxagdc=0

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000f800000
Kernel text base: 0xffffff800fa00000
__HIB  text base: 0xffffff800f900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1924455819589
```

**Comment by terberes** [comment]
You should try disabling hibernation
`sudo pmset -a hibernatemode 0`

**Comment by KrimskiyMaxim** [comment]
> You should try disabling hibernation
> `sudo pmset -a hibernatemode 0`

Then my laptop will not sleep at all?

**Comment by terberes** [comment]
No, it will sleep, but it will not be in hibernation mode. 
Hibernation mode is when RAM is dumped to file and laptop shuts down.
Hibernation almost never works on hackintosh laptops.

**Comment by gmallios** [comment]
I'm getting the same KP with hibernationmode set to 0.

**Comment by gmallios** [comment]
Removing darkwake=0 seems to solve the issue on OC. ( I am also using a WiFi usb adapter )

**Comment by gmallios** [comment]
I removed USBInjectAll kext from OC and it seems to solve the issue.

**Comment by Mikes0** [comment]
Same issue.  Latest release, using opencore.  All BIOS patches applied.

```
panic(cpu 0 caller 0xffffff8001491b2c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0xf45b.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff81227e3900 : 0xffffff8000e471e8 
0xffffff8116d33c40 : 0xffffff8000d433f1 
0xffffff8116d33cb0 : 0xffffff8000d41c2f 
0xffffff8116d33d00 : 0xffffff8000e442e9 
0xffffff8116d33d40 : 0xffffff8000e43b4b 
0xffffff8116d33d70 : 0xffffff800142d048 
0xffffff8116d33da0 : 0xffffff800142ff59 
0xffffff8116d33e00 : 0xffffff80014152ea 
0xffffff8116d33ea0 : 0xffffff8001414c14 
0xffffff8116d33ec0 : 0xffffff8000d63545 
0xffffff8116d33f40 : 0xffffff8000d63071 
0xffffff8116d33fa0 : 0xffffff8000cc713e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxagdc=0

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000000a00000
Kernel text base: 0xffffff8000c00000
__HIB  text base: 0xffffff8000b00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 4095008428770
```

Does anyone have any idea about this?

**Comment by Mikes0** [comment]
This issue follows the same pattern each time.  I can trigger this kind of crash reliably because of this.

Stage 1: everything works fine, sleep / wake works no problem

Stage 2: following sleep/wake the bluetooth crashes:
![Screenshot 2020-05-21 at 09 28 01](https://user-images.githubusercontent.com/40921615/82540941-97cd0300-9b47-11ea-8f74-0a4f32e4fb60.png)

Stage 3: Attempting to sleep will cause the crash in this issue.  After the crash turning off the laptop results in the keyboard not being usable, unable to select drive to boot but also unable to enter BIOS or boot menu.  Have to hold power button until properly resets and then can use keyboard again.

Summary: Crash happens when attempting to sleep with bluetooth already crashed.

**Comment by yllwfsh** [comment]
@KrimskiyMaxim @terberes @gmallios @Mikes0 

Could you perhaps try the [new commit](https://github.com/johnnync13/Xiaomi-Mi-Air/commit/6300414634315f92fc43db41cfda65e9f7bc9638) i made? I created a new USB map and power settings. I have not created a release yet, so please download (non-standard) from https://github.com/johnnync13/Xiaomi-Mi-Air/archive/master.zip

Thx!

**Comment by Mikes0** [comment]
@yllwfsh have installed and will test.  Changed the OC config.plist to include

```
<key>AppleCpuPmCfgLock</key>
<false/>
<key>AppleXcpmCfgLock</key>
<false/>
```

**Comment by yllwfsh** [comment]
@Mikes0 Thx! Let me know if it's better or not

**Comment by Mikes0** [comment]
@yllwfsh Issue not fixed by your new zip.  

```
panic(cpu 0 caller 0xffffff8004e91b2c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0xf976.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff812637b900 : 0xffffff80048471e8 
0xffffff8126243c40 : 0xffffff80047433f1 
0xffffff8126243cb0 : 0xffffff8004741c2f 
0xffffff8126243d00 : 0xffffff80048442e9 
0xffffff8126243d40 : 0xffffff8004843b4b 
0xffffff8126243d70 : 0xffffff8004e2d048 
0xffffff8126243da0 : 0xffffff8004e2ff59 
0xffffff8126243e00 : 0xffffff8004e152ea 
0xffffff8126243ea0 : 0xffffff8004e14c14 
0xffffff8126243ec0 : 0xffffff8004763545 
0xffffff8126243f40 : 0xffffff8004763071 
0xffffff8126243fa0 : 0xffffff80046c713e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxagdc=0

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000004400000
Kernel text base: 0xffffff8004600000
__HIB  text base: 0xffffff8004500000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 2466725918440

```

Full crash happens when trying to sleep with already crashed bluetooth.

**Comment by Mikes0** [comment]
@yllwfsh have reverted to Clover for now as is more stable.  Crash only seems to happen in OC.

**Comment by yllwfsh** [comment]
Ok for now I've [reverted](https://github.com/johnnync13/Xiaomi-Mi-Air/commit/42437244f32675b9469ea9422479e47ca2ad1122) the changes

**Comment by KrimskiyMaxim** [comment]
> Ok for now I've [reverted](https://github.com/johnnync13/Xiaomi-Mi-Air/commit/42437244f32675b9469ea9422479e47ca2ad1122) the changes
Hey. Used your changes. There are probably improvements (Using Clover). But at startup, the same error opened, but the computer did not wake up itself.

**Comment by yllwfsh** [comment]
Unfortunately it seems that sleep is working perfectly when Intel Bluetooth kexts are not loaded, so this issue is really only related to those drivers. Nothing we can do about that here really.

So if possible please report this to https://github.com/zxystd/IntelBluetoothFirmware/issues

**Comment by gmallios** [comment]
@yllwfsh I think we should make a different OC folder without Intel WiFi and Bluetooth kexts or remove them from the current one until those kexts are stable.

**Comment by johnnync13** [comment]
it is a bug from bluetooth kext... @gmallios now you have new instructions to work Intel Wifi

**Comment by AnubisGreat** [comment]
I have this with oclp. macbook 7,1, sonoma.
Any advice? thank you.

panic(cpu 0 caller 0xffffff8009592357): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IO80211FamilyLegacy. Thread 0x117bd4.
Failure code:: 0x00000200 00000014

Backtracing specified thread
Panicked task 0xffffff9682814df8: 217 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffffa4e83130c8, Frame : Return Address
0xffffffff007e7790 : 0xffffff8008f7f2a7 mach_kernel : _machine_switch_context + 0xd7
0xffffffff01413b30 : 0xffffff8008e63e86 mach_kernel : _thread_block_reason + 0x1f86
0xffffffff01413bc0 : 0xffffff8008e61ff0 mach_kernel : _thread_block_reason + 0xf0
0xffffffff01413c10 : 0xffffff8008f7c1e0 mach_kernel : _lck_mtx_lock_wait_x86 + 0x130
0xffffffff01413c50 : 0xffffff8008f7b9cb mach_kernel : _lck_mtx_lock_slow + 0x44b
0xffffffff01413c90 : 0xffffff800950cd78 mach_kernel : __ZN10IOWorkLoop9closeGateEv + 0x28
0xffffffff01413cc0 : 0xffffff800950fde9 mach_kernel : __ZN13IOCommandGate9runActionEPFiP8OSObjectPvS2_S2_S2_ES2_S2_S2_S2_ + 0x49
0xffffffff01413d20 : 0xffffff800aeff74b com.apple.iokit.IONetworkingFamily : __ZN19IONetworkController14executeCommandEP8OSObjectPFiPvS2_S2_S2_S2_ES2_S2_S2_S2_S2_ + 0x61
0xffffffff01413d80 : 0xffffff800c9270e1 com.apple.iokit.IO80211FamilyLegacy : __ZN23IO80211VirtualInterface22powerStateWillChangeToEmmP9IOService + 0x89
0xffffffff01413dd0 : 0xffffff80094f20fa mach_kernel : __ZN9IOService23driverInformPowerChangeEv + 0x2fa
0xffffffff01413e70 : 0xffffff80094f1966 mach_kernel : __ZN9IOService15pmDriverCalloutEPS_Pv + 0xa6
0xffffffff01413ea0 : 0xffffff8008e90638 mach_kernel : _thread_call_delayed_timer + 0x508
0xffffffff01413ee0 : 0xffffff8008e916c8 mach_kernel : _thread_call_delayed_timer + 0x1598
0xffffffff01413fa0 : 0xffffff8008dd319e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.4)[5D912FD8-C4CD-3CF6-B214-DF5BF7AB4FA0]@0xffffff800aef4000->0xffffff800af0bfff
         com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[4C07538B-62EB-3D6D-AEF9-93BCDCF45FAB]@0xffffff800c875000->0xffffff800ca5bfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[07852425-8607-3C1A-B273-92FC0221EC02]@0xffffff800a49e000->0xffffff800a4d4fff
            dependency: com.apple.driver.corecapture(1.0.4)[0DED4F91-AC29-379C-9A48-83E6009E40F0]@0xffffff800b99d000->0xffffff800b9bffff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[AD49AD95-220B-3FA9-8BB0-6DC8A16C7545]@0xffffff800a87e000->0xffffff800a887fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[5D912FD8-C4CD-3CF6-B214-DF5BF7AB4FA0]@0xffffff800aef4000->0xffffff800af0bfff
            dependency: com.apple.iokit.IOSkywalkFamily(1.0)[035A9AD9-6CDE-362F-8DEC-B664BC6431EC]@0xffffff800c7a7000->0xffffff800c865fff
            dependency: com.apple.kec.corecrypto(14.0)[DFE2B195-25A0-3CB4-8283-067C1F1804A5]@0xffffff800b9ce000->0xffffff800ba4afff

Process name corresponding to current thread (0xffffffa4e83130c8): kernel_task
Boot args: keepsyms=1 debug=0x100 ipc_control_port_options=0 -nokcmismatchpanic -v

Mac OS version:
23D60

Kernel version:
Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Kernel UUID: 
roots installed: 0
KernelCache slide: 0x0000000008a00000
KernelCache base:  0xffffff8008c00000
Kernel slide:      0x0000000008ae0000
Kernel text base:  0xffffff8008ce0000
__HIB  text base: 0xffffff8008b00000
System model name: MacBookAir7,1 (Mac-
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 14

System uptime in nanoseconds: 173071567460190
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00009d685d4c9ebe
  Sleep   : 0x00009d2c640407a1 0x000000022bfdac60 0x00006319df9bf862
  Wake    : 0x00009d2c90db07d2 0x000000022eea5b96 0x00009d2c818c9ad3
Compressor Info: 24% of compressed pages limit (OK) and 12% of segments limit (OK) with 9 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff901b3bc000 - 0xffffffb01b3bc000
  . PGZ   : 0xffffff901b3bc000 - 0xffffff901c3bd000
  . VM    : 0xffffff901c3bd000 - 0xffffff94e8e23000
  . RO    : 0xffffff94e8e23000 - 0xffffff96826ef000
  . GEN0  : 0xffffff96826ef000 - 0xffffff9b4f155000
  . GEN1  : 0xffffff9b4f155000 - 0xffffffa01bbbb000
  . GEN2  : 0xffffffa01bbbb000 - 0xffffffa4e8621000
  . GEN3  : 0xffffffa4e8621000 - 0xffffffa9b5088000
  . DATA  : 0xffffffa9b5088000 - 0xffffffb01b3bc000
  Metadata: 0xffffffba28dac000 - 0xffffffba48dac000
  Bitmaps : 0xffffffba48dac000 - 0xffffffba4a5ac000
  Extra   : 0 - 0
