### ISSUE TITLE
Clover font broken after update to 10.15.4

### ISSUE THREAD

**Issue by uwetrempelmann** [johnnync13/Xiaomi-Mi-Air#134]
Hi Today my Clover-Bootmenu was broken after update to Catalina 10.15.4.

After some investigation I've found out that the format of font.png inside Xiaomi folder was wrong.
So I put a copy of the darksimple theme inside xiaomi folder and everything is fine again....

cheers,
  Uwe

PS: Thanks for your amazing job on this project, pls. keep the fantastic work!

**Comment by johnnync13** [comment]
10.15.4 need some minimum version of clover
