### ISSUE TITLE
BIOS patch compatibility, Mi Notebook Air 2019 (MX250)

### ISSUE THREAD

**Issue by Mikes0** [johnnync13/Xiaomi-Mi-Air#135]
I have the Xiaomi Mi Notebook air 13,3" **2019 Model** i5 with **MX250 graphics**.

It shipped with BIOS **XMAKB3M0P1710** and the model shows as TM1703 in the BIOS.

Just letting anyone who might be interested that I managed to apply the BIOS patches using the scripts in this repo, they all worked for me so seem compatible with the 2019 model with MX250 graphics as well.

 Laptop didn't brick :) I just followed the guide in this repo.  Scripts tested as working:

bios_unlock.cmd
CFG_unlock.cmd
voltage_unlock.cmd
speedshift_unlock.cmd
bios_lock.cmd

**Comment by yllwfsh** [comment]
Thank you for the info!!!
Any issues with the EFI folder (booting macOS) on that model or can we add it to the compatibility list?

**Comment by Mikes0** [comment]
Hi,

Seems OK in Clover.

in Opencore I have the same issues as reported in #131 (sleep panic) - this bug is a real pain, frequent kp on sleep. Also, #127 (F9 / Fn+F9 button doesn't work, no longer turns on/off trackpad).  

@yllwfsh which release are you currently using? do you use clover or opencore?

**Comment by yllwfsh** [comment]
@Mikes0 Thanks again for the info. I'll update the README compatibility list accordingly when I have the time.

**Comment by yllwfsh** [comment]
Done. https://github.com/johnnync13/Xiaomi-Mi-Air/commit/b7aeced0f66079f833afd3fbe5fa9f8204df75cd
