### ISSUE TITLE
there are some problems

### ISSUE THREAD

**Issue by knifead** [johnnync13/Xiaomi-Mi-Air#137]
There are some problems here. When I use the clover, the name under the startup project is garbled. Secondly, whenever I sleep in opencore, it will cause a black screen to fail to wake up. I can only press the shutdown button to restart, and occasionally encounter keyboard failure Situation, I have unlocked cfglock, but no matter I modify config.plist, this problem will appear.
At the same time I want to know how not to drive the intel Bluetooth driver, because I plan to change the Apple's native network card

这里有一些问题，当我使用四叶草时，启动项目下的名称是乱码，其次，opencore中每当我休眠都会导致黑屏无法唤醒，只能长按关机键重启，偶尔还会遇到键盘失灵的情况，我已经解锁了cfglock，但是不论我修改config.plist都会有这个问题出现。同时我想知道如何不驱动intel蓝牙驱动，因为我打算改苹果原生网卡了

**Comment by yllwfsh** [comment]
@knifead Issue with clover is known (see https://github.com/johnnync13/Xiaomi-Mi-Air/issues/134) and the sleep issue too (see https://github.com/johnnync13/Xiaomi-Mi-Air/issues/131)

If you want to disable the Intel Bluetooth for now:
* On Clover simply delete the 2 bluetooth kexts in EFI/Clover/kexts/other
* On OpenCore, go in to the config.plist with ProperTree and disable (Enabled=False) the 2 Bluetooth kexts in Kernel -> Add
