### ISSUE TITLE
Internet required during install - Add HoRNDIS.kext to EFI?

### ISSUE THREAD

**Issue by Poslezavtra** [johnnync13/Xiaomi-Mi-Air#138]
Hello, i've just installed Catalina on my mi Notebook 13.3 2018, but it said, when i cleck Install, that Internet required. Unfortunately, i have not any usb WiFi Adapter, so, i tried to tether Internet from Android, but it doesn't work. I tried to put Intel WiFi kext in kexts, but it doesn't work as well. 
So, does anyone have an idea, how to Install in this situation? 
I've not found horndis.kext, so, if anyone have this, i'll be glad

**Comment by yllwfsh** [comment]
Intel Wifi or USB Wifi Adapters don't work for installation.

Please read https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/README.md all the information is there in the introduction. Even a link to horndis.kext.

Alternatively you can try to create a USB install disk from MacOS that seems to not require internet during install.

**Comment by gmallios** [comment]
@Poslezavtra You can extract the kext from the HoRNDIS file or i can send it.

**Comment by gmallios** [comment]
@yllwfsh should i create a pr to add the HoRNDIS.kext ?

**Comment by Poslezavtra** [comment]
> @Poslezavtra You can extract the kext from the HoRNDIS file or i can send it.

Yep, could you send it, please

**Comment by Poslezavtra** [comment]
> @yllwfsh should i create a pr to add the HoRNDIS.kext ?

Pr? What is it? Sry, i am new boy in hackintosh

**Comment by yllwfsh** [comment]
@gmallios Yep that would be awesome as i'm extremely limited in time, my day job currently consumes all of it.

**Comment by yllwfsh** [comment]
@Poslezavtra PR means [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests), which means everyone can contribute to this open source project :)

**Comment by yllwfsh** [comment]
Done: https://github.com/johnnync13/Xiaomi-Mi-Air/commit/2d18b42bcfc750914478a121a9b9d751ff62f288
