### ISSUE TITLE
The percentage of battery on menu bar is abnormal when charging

### ISSUE THREAD

**Issue by vimcaw** [johnnync13/Xiaomi-Mi-Air#14]
The current battery is 99%, but the icon is empty, it is normal when it is full and uncharged.

![image](https://user-images.githubusercontent.com/21964227/51647167-a5f02b00-1fb6-11e9-92b8-68d820c912a4.png)

![image](https://user-images.githubusercontent.com/21964227/51647151-98d33c00-1fb6-11e9-8f19-66c437c1d2ac.png)

![image](https://user-images.githubusercontent.com/21964227/51647251-fe272d00-1fb6-11e9-8380-53b21f6de349.png)

**Comment by tk109** [comment]
https://discussions.apple.com/thread/6751144

**Comment by vimcaw** [comment]
@tk109  Oh, I see, Thank you.
