### ISSUE TITLE
Xiaomi Mi Air 1st Gen Stuck on loading screen

### ISSUE THREAD

**Issue by fatboy32** [johnnync13/Xiaomi-Mi-Air#140]
Hello There,

I was really happy with how my hackintosh was working on my 2018 mi notebook air. I thought I would assist a friend in doing the same with their mi notebook air 1st gen, however after inserting the bootable usb it will not get passed the Mac loading screen. It gets about half to three quarters along with the white bar before it just freezes and sends the computer into a reboot which results in more of the same.

Does anyone have any ideas or solutions for this? I have even tried installing mac on the ssd in my computer and then moving it into the other one but the same thing happens when we attempt to boot (it does however work on my 2018 mi notebook).

Thanks in advance for the help.

**Comment by yllwfsh** [comment]
Hi @fatboy32 

This repo is only for the 2018 notebook, however Johnny also has a different repo for the 2016 one: https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen

Hope this helps :)
