### ISSUE TITLE
HDMI Not working properly

### ISSUE THREAD

**Issue by littlezo** [johnnync13/Xiaomi-Mi-Air#141]
Xiaomi Notebook Air 2018 13.3"  i7-8550u

HDMI Not working properly

**Comment by yllwfsh** [comment]
Can you describe the problem? When? How?

**Comment by gmallios** [comment]
#142 Supposedly fixes problems with HDMI.

**Comment by yllwfsh** [comment]
@littlezo Please test: https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.5 and let us know please if it's fixed.
