### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by CamilloCorleone** [johnnync13/Xiaomi-Mi-Air#143]
With last releases my trackpad totally doesn't work with OC.
With Clover, it works but is not recognized as a trackpad (so i can move the pointer but gestures etc don't work). 

Last working release for me is 7.3.5 (Clover), but here I have issues with keyboard (command and ALT keys are inverted).

Can you please help me?

Thank you

**Comment by yllwfsh** [comment]
Hello @CamilloCorleone 

Have you tried these steps? https://github.com/johnnync13/Xiaomi-Mi-Air#troubleshooting

**Comment by johnnync13** [comment]
try the last release, it is possible that in other version with the new force touch simulation not working well. Now it's fine!
