### ISSUE TITLE
About chang DVMT size from 32mb to 64mb

### ISSUE THREAD

**Issue by Gray-Shirt** [johnnync13/Xiaomi-Mi-Air#144]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/BIOS/DVMT_and_0xE2_fix

I want to know if it works in xiaomi-air. Maybe a better experience

sorry I'm not good at English

**Comment by yllwfsh** [comment]
Hello @Gray-Shirt 

The 0xE2 (CFG-Lock) fix works for sure! See https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS . I haven't tried to patch the DVMT size, but I have reason to believe the BIOSes are pretty similar.

However try at your own risk!

**Comment by johnnync13** [comment]
There's no need for that. In the Xiaomi Mi Air it comes by default in 64mb

**Comment by chanbaihai** [comment]
> There's no need for that. In the Xiaomi Mi Air it comes by default in 64mb

If its default with 64MB, then WHY I cant get 4k resolution but only 2k？Do you ever try to connect a 4k monitor?

**Comment by johnnync13** [comment]
You have to change hdmi fix
