### ISSUE TITLE
can used on xiaomi air cpu i7-7500U

### ISSUE THREAD

**Issue by kidd808** [johnnync13/Xiaomi-Mi-Air#145]
hi,

my xiaomi ari CPU is i7-7500U, neither first generation nor 2018. can i use this?

**Comment by yllwfsh** [comment]
It should probably just work, give it a try and see if you can boot the macOS installer USB using the README guide (trying to boot the USB doesn't affect your files). If you can run the installer, you can run macOS.

If you want to keep your current Windows/Linux install, you can install a second SSD in your laptop for macOS.

If it doesn't work, report back please.
