### ISSUE TITLE
Unable to boot 7.5.2 / SMBios settings missing in latest OC config.plist

### ISSUE THREAD

**Issue by yllwfsh** [johnnync13/Xiaomi-Mi-Air#146]
@johnnync13 in the latest release oc plist there's no serial number, MLB or rom info

**Comment by johnnync13** [comment]
Yeah, because that's personal. Each user must generate their own smbios. Also, they're apple properties so it's not very well viewed.

**Comment by yllwfsh** [comment]
@johnnync13 Yeah I know and I would always generate my own, but does OC even boot without the SMBIOS? Shouldn't we provide some basic data to start with? If not, I can write some README to make sure that everyone generates their own.

**Comment by johnnync13** [comment]
maybe, OC should boot with only model laptop

**Comment by vimcaw** [comment]
Yeah, it can't boot for me, and after generating serial number, MLB and rom code, it still can't boot.

**Comment by yllwfsh** [comment]
Then I would suggest to refer everyone to the Opencore vanilla guide on how to generate the numbers themselves in the README or to place the numbers back that we had before

**Comment by vimcaw** [comment]
After updating to v7.5.2, it still can't boot for me.

**Comment by vimcaw** [comment]
Is there someone can successfully boot with latest OC EFI?

**Comment by yllwfsh** [comment]
I currently have no time to test. I'll try to test tonight

**Comment by Gray-Shirt** [comment]
NVMeFix.kext   https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.5

**Comment by johnnync13** [comment]
@Gray-Shirt ?

**Comment by Gray-Shirt** [comment]
7.5.1 即使在补全MLB rom 这些信息后仍然无法启动，使用7.5.0的 NVMeFix.kext，后可以成功启动。
7.5.2我想也是这样。不过我还没有尝试。

并不擅长英语，请使用google翻译。

**Comment by paranoiagu** [comment]
success to boot after revert the NVMeFix.kext.

**Comment by johnnync13** [comment]
@paranoiagu try new release

**Comment by johnnync13** [comment]
Problem has been resolved
