### ISSUE TITLE
can't find devices in Sidecar

### ISSUE THREAD

**Issue by ChenXuyuan350** [johnnync13/Xiaomi-Mi-Air#147]

**Comment by yllwfsh** [comment]
Sidecar requires native (Broadcom) Wifi and Bluetooth capabilities, so it's not supported on this laptop

**Comment by ChenXuyuan350** [comment]
Thank you. I didn't trust my computer when I connected to my iPad, resulting in no device on the display. Now I have successfully connected through USB.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yllwfsh"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上7:17
收件人: "johnnync13/Xiaomi-Mi-Air"<Xiaomi-Mi-Air@noreply.github.com&gt;; 
抄送: "大梦"<1057918148@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [johnnync13/Xiaomi-Mi-Air] can&#39;t find devices in Sidecar (#147)





 
Sidecar requires native (Broadcom) Wifi and Bluetooth capabilities, so it's not supported on this laptop
