### ISSUE TITLE
Kernel Panic while installing

### ISSUE THREAD

**Issue by hker9527** [johnnync13/Xiaomi-Mi-Air#148]
First of all, thank you for this repo, it helps a lot.
So, I tried to install hackintosh yesterday, and the screen freezes while hitting the "Remaining 15 minutes" mark during installing.
My notebook is the MX250 version, i5-8250u.
I am using version 7.5.3 of this repo.
I cannot find any KP logs under /Library/Logs/DiagnosticsReporter, or /private/logs. /Library/Logs/PanicReporter does not exist too.
I tried using 10.15.4 and 10.15.5. I also tried creating an offline installer using MakeInstallmacOS, but KP also happened. I didn't export the logs, so if that maybe a solution, I will try again.
Here is the installer log I tried to export before the KP.

[Installer Log 6-Jun-2020.txt](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4739892/Installer.Log.6-Jun-2020.txt)

**Comment by johnnync13** [comment]
Use v7.5

**Comment by hker9527** [comment]
It is the same, freezing at the same point.

[Installer Log 7-Jun-2020.txt](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4741167/Installer.Log.7-Jun-2020.txt)
