### ISSUE TITLE
Clover Bootloader can't read language

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#152]
Hi, im having issue on reading the language on the bootloader. I have tried to change the language in Clover Configurator Gui to en but still the same. Please help
![20200618_091159](https://user-images.githubusercontent.com/67082163/84966498-40b94e80-b144-11ea-83b1-cfcd80085afb.jpg)

**Comment by arthoes** [comment]
Yes, I have the same problem

**Comment by hongtm77** [comment]
> Yes, I have the same problem

I just figured it out. By changing the clover themes will solve the problem.

**Comment by yllwfsh** [comment]
@hongtm77 @arthoes Since Clover is less and less efficient and less supported I'd highly recommend to switch to OpenCore. It's faster and more secure too! I currently don't have time to fix and test the Clover folder (using only OC), so unless someone makes a pull request, it may stay 'broken' like this.

**Comment by hongtm77** [comment]
> @hongtm77 @arthoes Since Clover is less and less efficient and less supported I'd highly recommend to switch to OpenCore. It's faster and more secure too! I currently don't have time to fix and test the Clover folder (using only OC), so unless someone makes a pull request, it may stay 'broken' like this.

Thanks to the reply. I see, can i convert my clover to OpenCore or do i need to re-install the whole Catalina with OpenCore? Sorry im very new here

**Comment by hongtm77** [comment]
Thanks @yllwfsh now im using OC and finally solve the problem

**Comment by cly1998** [comment]
Yes, I have the same problem

**Comment by stevezhengshiqi** [comment]
Using the latest Clover release(r5119) could solve the problem. The EFI maintainer should check these details before releasing the EFI pack.

**Comment by changly** [comment]
> Using the latest Clover release(r5119) could solve the problem. The EFI maintainer should check these details before releasing the EFI pack.

Have tried in person, can repair, thank you!!!

**Comment by hongtm77** [comment]
Actually i have been using OC since that day @yllwfsh suggested. Everything was so smooth and glad that he advised. I figured out you just need to change your current clover EFI to OC EFI (EFIOC renamed to EFI) that is included in the same zip file that we downloaded. @yllwfsh correct me if im wrong on changing from clover to OC. Since OC has more benefit than Clover, its highly recommended.

**Comment by yllwfsh** [comment]
@hongtm77 Yes you are correct! It's just a matter of replacing the contents of the EFI folder with that of the EFIOC folder, and you will have OpenCore.

**Comment by hongtm77** [comment]
> @hongtm77 Yes you are correct! It's just a matter of replacing the contents of the EFI folder with that of the EFIOC (or renaming EFIOC to EFI) folder, and you will have OpenCore.
> 
> Don't forget to apply your SMBIOS to the OpenCore config.plist if you changed it for iMessage etc. https://dortania.github.io/OpenCore-Desktop-Guide/post-install/iservices.html

Oh ya, I forgot that i applied that too. But its pretty straight forward.

**Comment by brilliantfeat** [comment]
> Hi, im having issue on reading the language on the bootloader. I have tried to change the language in Clover Configurator Gui to en but still the same. Please help
> ![20200618_091159](https://user-images.githubusercontent.com/67082163/84966498-40b94e80-b144-11ea-83b1-cfcd80085afb.jpg)

Maybe you should appropriate modify the “Text Width“ in theme.plist
