### ISSUE TITLE
Is type-c mini-dp work?

### ISSUE THREAD

**Issue by yuqZY** [johnnync13/Xiaomi-Mi-Air#153]
I have some questions about the typec interface. Can I use minidp in macos?  I have a 4k monitor, but it cannot connect to the Xiaomi notebook. Of course, the hdmi interface can work, but it can only support 4k 30hz. I am not sure whether the typec minidp of the Xiaomi notebook needs to work with the mx150. I just want to know,   Whether the Xiaomi minidp can work and output 4k 60hz in macos

**Comment by chanbaihai** [comment]
I have the same issue,I connect a 4k type-c monitor to the computer, but I can just got 2k resolution,I google it and know that I have to change DVMT to more than 64MB to enable 4K output,How to do that on AIR 13.3 ? anyone who know this?

**Comment by cly1998** [comment]
I also want to know if this is OK. If you can, please tell me about it.

**Comment by cly1998** [comment]
> 我对Typec接口有一些疑问。我可以在macOS中使用minidp吗？我有一个4k显示器，但是它无法连接到小米笔记本电脑。当然，hdmi接口可以工作，但只能支持4k 30hz。我不确定小米笔记本的typec minidp是否需要与mx150配合使用。我只是想知道小米minidp是否可以在macOS中输出4k 60hz

Hello, do you need to modify some files with HDMI 4K? My HDMI Mac OS can only 1080p, windows can 4K, but is 30Hz, why can only 1080p Mac? If you know, please let me know

**Comment by cly1998** [comment]
Hello, is your 4K 30Hz connected to 4K monitor using HDMI? My HDMI 30Hz output in windows is no problem, why only 1080p can be recognized in MacOS? Can you add QQ if it's convenient?

**Comment by cly1998** [comment]
> 我对Typec接口有一些疑问。我可以在macOS中使用minidp吗？我有一个4k显示器，但是它无法连接到小米笔记本电脑。当然，hdmi接口可以工作，但只能支持4k 30hz。我不确定小米笔记本的typec minidp是否需要与mx150配合使用。我只是想知道小米minidp是否可以在macOS中输出4k 60hz

Hello, is your 4K 30Hz connected to 4K monitor using HDMI? My HDMI 30Hz output in windows is no problem, why only 1080p can be recognized in MacOS? Can you add QQ if it's convenient?

**Comment by changly** [comment]
> 我有一个相同的问题，我将4k type-c显示器连接到计算机，但是我只能得到2k分辨率，我用google搜索它，并且知道我必须将DVMT更改为超过64MB才能启用4K输出，该如何做在AIR 13.3上？有人知道吗？
If the DVMT is changed to more than 64MB to enable 4K output, what should I do on air 13.3? Have you tried this? Is it successful?

**Comment by chanbaihai** [comment]
After two weeks effort,I got my xiaomi-air-13,3 7200U 4k works well, Both on HDMI and TYPE-C,Id like to tell you how to got it when Im free

**Comment by yllwfsh** [comment]
@chanbaihai That's great news! Please do share how you've managed to do it when you have time :)

**Comment by changly** [comment]
> 经过两个星期的努力，我使我的xiaomi-air-13,3 7200U 4k正常工作，在HDMI和TYPE-C上均可使用，我想告诉您如何在我免费时获得它

That's really good news. I'm waiting for you to share your successful experience

**Comment by yllwfsh** [comment]
@changly @yuqZY 

Check this howto: https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/BIOS/Enable%204K.md

Thanks a lot to @chanbaihai !!!
