### ISSUE TITLE
My iPad is disconnected

### ISSUE THREAD

**Issue by YuHayring** [johnnync13/Xiaomi-Mi-Air#154]
When I connect my iPad(mini 5, using usb 3.0 port ,usb2.0-lighting data cable) for about a minute, it is disconnected by the system. And it shows :
USB配件已停用
拔掉耗电量太大的配件以重新启用USB设备。
(USB accessory disabled,Unplug the power consuming accessory to re enable the USB device.)

<img width="251" alt="截屏2020-06-19 23 32 16" src="https://user-images.githubusercontent.com/43499247/85151345-4028d100-b286-11ea-939e-a296a6f4eb36.png">

**Comment by yllwfsh** [comment]
Can you try https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.5.9 and report back if it's fiixed?
