### ISSUE TITLE
Sometimes bluetooth not work

### ISSUE THREAD

**Issue by yuqZY** [johnnync13/Xiaomi-Mi-Air#155]
Sometimes, Bluetooth will disabled after long time sleep. Under normal circumstances, after a long sleep, the screen will display that the computer has restarted abnormally, and then Bluetooth will turn gray, unable to turn off and turn on. After restarting the computer, the exception disappears

**Comment by yllwfsh** [comment]
Hi @yuqZY,

Please report this at https://github.com/zxystd/IntelBluetoothFirmware
Nothing we can do here unfortunately.

Thanks
