### ISSUE TITLE
USB Problem and Kernel Panic

### ISSUE THREAD

**Issue by MEMZSONBILI** [johnnync13/Xiaomi-Mi-Air#156]
I'm useing macOS Catalina 10.15.6 19F101,sometimes when I wake up the laptop,it says:

> 您的电脑因遇到问题而重新启动

I check the log and there is a:

> panic(cpu 0 caller 0xffffff801be9167c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle:com.apple.iokit.IOUSBHostFamily

"Com.apple.iokit.IOUSBHostFamily" appears to be due to this problem with the USB device, but I did not insert any USB device except the mouse.

so what happened with this？

Here is full log:[https://paste.ubuntu.com/p/3NwjGnNjPG/](The Log)

**Comment by yllwfsh** [comment]
Hi @MEMZSONBILI,

This is a known issue and related to the Intel Bluetooth device (attaches internally to the USB hub).
Please report this at https://github.com/zxystd/IntelBluetoothFirmware
Nothing we can do about this error here unfortunately.

Thanks
