### ISSUE TITLE
The EFI also works well on Mi Air 2017

### ISSUE THREAD

**Issue by Notics-Seed** [johnnync13/Xiaomi-Mi-Air#157]
The EFI files(clover)(i haven't tried OC) also works well on Mi Air 2017 with the i7-7500U
everything works fine

![8D9D67DC-2BFC-4E28-B292-94680955FFFC](https://user-images.githubusercontent.com/52071868/85415163-9310ca00-b59f-11ea-9aaf-9a455b298189.png)

**Comment by hongtm77** [comment]
Yes, im using Mi air 2017 too. Everything works perfectly.

**Comment by iSonik** [comment]
Does the bios unlock also work on the 2017 version?

**Comment by Notics-Seed** [comment]
> Does the bios unlock also work on the 2017 version?
> 
> > Yes, im using Mi air 2017 too. Everything works perfectly. By the way, what is OC?
> 
> Open Core

I don't know. I haven't tried yet

**Comment by Notics-Seed** [comment]
OK, OpenCore is also usable

**Comment by yllwfsh** [comment]
@Notics-Seed @iSonik Thx for the info I'll add it to the README.

**Comment by moddi3** [comment]
BIOS patches is also working for Mi Air 2017, Intel Core I5 7200U
latest Catalina

**Comment by hongtm77** [comment]
> BIOS patches is also working for Mi Air 2017, Intel Core I5 7200U
> latest Catalina

Hi, what you mean by Bios Patches?

**Comment by moddi3** [comment]
> > BIOS patches is also working for Mi Air 2017, Intel Core I5 7200U
> > latest Catalina
> 
> Hi, what you mean by Bios Patches?

Hi, I mean Unlock Scripts from this folder
https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS

**Comment by sketubz** [comment]
Anyone could comment on which version is working for the 2017 one plz ? I tried different version of MacOS with either OC et Clover without succes (tried EFI from 7.8 and 7.5.9 with Catalina 19h15, HS 17G66 and Mojva 18F2059 with no avail, it reboot after reaching half of the booting of the macos with no message). Or perhaps am i missing something ?
Thanks to whoever can help

**Comment by vanyasem** [comment]
Sorry to hijack this old thread, but I've been running macOS on my **Air 2017 7200u** for the past 5 years, and I've recently decided to upload my configuration to GitHub: https://github.com/vanyasem/hackintosh-xiaomi-air-7200U
It might be better suited for this particular laptop, and I still update it to this day.

One caveat though is that I focus on supporting one macOS version at a time to ensure maximum reliability (all changes are tested manually by me prior to releasing an update). The currently supported macOS version is mentioned in the readme.

BIOS patches are required, and I believe that the method mentioned above worked for me as well (although I admit it's quite hard to remember such details after 5 years)

**Comment by vanyasem** [comment]
I have made an update that supports macOS Sonoma: https://github.com/vanyasem/hackintosh-xiaomi-air-7200U/releases/tag/oc0.9.9_macos12-14

It supports macOS 12 - Monterey, macOS 13 - Ventura, macOS 14 - Sonoma (including the latest version 14.4)
