### ISSUE TITLE
The EFI also works on Mi Notebook Air 13.3' 7200U

### ISSUE THREAD

**Issue by rootwhois** [johnnync13/Xiaomi-Mi-Air#158]
The EFI files(clover & OC) also working on Mi Notebook Air 13.3' with the i5-7200U, MacOS 10.15.5.
Thanks for your work!
Hope it can support Big Sur soon!

**Comment by rootwhois** [comment]
And I found a new problem, OC can't boot MacOS 10.15.1 Beta Version (19B77a)

**Comment by yllwfsh** [comment]
@rootwhois Support of this repo is not really focused on older versions of macOS, only the latest. If you post some logs maybe we can help figuring it out but if 10.15.5 works, I'd suggest to use that of course
