### ISSUE TITLE
Wifi card instead of Intel Wifi

### ISSUE THREAD

**Issue by iSonik** [johnnync13/Xiaomi-Mi-Air#159]
Hey guys, 
I got myself a native WIFI card for the Mi Air 13. But after installing it, nothing happend. Do i have to disable the Intel Wifi driver first?

**Comment by yllwfsh** [comment]
Hi @iSonik, If you're trying to install a m.2 wifi card, unfortunately that's not possible as it seems Xiaomi locked the bios to SSDs only. Some people have tried to fix that but as far as I know no success yet.

@johnnync13 Do you know any improvements on that front?

**Comment by iSonik** [comment]
@yllwfsh Oh. Even on the 7200u version? That means i would need an adapter for the 2nd slot, not the first one right?

**Comment by johnnync13** [comment]
@iSonik you need nvme interface. On your model I don’t know if works. On 6200u works well

**Comment by iSonik** [comment]
So i am a little confused. Do i need an NVME adapter but i could still use the Main SSD slot. Or do i need a different adapter and use the 2nd slot?

Wifi Card:
BCM94360CS2

**Comment by yllwfsh** [comment]
@iSonik Theoretically the idea is to use the NVMe slot (usually the left one) with your adapter and the Apple WiFi card. The other slot is then still available for a M.2 SATA SSD. But I don't think it'll work. I've tried mine too (2018 i7-8550u) but had to put the wifi card back into my drawer :/ 

Apart from that the adapter + wifi card is physically too thick to put in my laptop anyway. Now I use an [Edimax EW-7822ULC](https://www.amazon.de/Edimax-EW-7822ULC-Dual-Band-MU-MIMO-Adapter/dp/B06WD1PTVY/ref=sxts_sxwds-bia-wc-p13n1_0?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&cv_ct_cx=Edimax+EW-7822ULC&dchild=1&keywords=Edimax+EW-7822ULC&pd_rd_i=B06WD1PTVY&pd_rd_r=0789b32a-56b5-47d8-935f-2efb9859d114&pd_rd_w=gOWDl&pd_rd_wg=Nu2tR&pf_rd_p=5acb4b2f-6301-41be-b183-642bc5d3fb81&pf_rd_r=6JD4HR7PEN8J2ZF4ZFNQ&psc=1&qid=1593289214&sr=1-1-c8b680f7-0dc9-4abe-aa5a-ccfde0ac07ae) And the drivers from [chris1111](https://github.com/chris1111/Wireless-USB-Adapter). Wifi connectivity works great, no handoff and continuity though.

**Comment by iSonik** [comment]
@yllwfsh Did you try both Slots?

**Comment by yllwfsh** [comment]
@iSonik The right hand slot is wired as SATA only so it doesn't work. For instance you cannot put the NVMe SSD in there either. On top of that it doesn't fit due to the key (B vs. M).

**Comment by yllwfsh** [comment]
@iSonik And even after all of that if it would fit and work you still need to find a spot to solder the bluetooth wires to and re-route (+extend?) the antenna wires

**Comment by iSonik** [comment]
@yllwfsh so the right side slot is the one that has the original ssd?

My plan was to use Broadcom wifi + intel bluetooth

**Comment by yllwfsh** [comment]
No there is an NVMe SSD installed normally (at least in mine and I think in yours too) so you'd also have to buy a M.2 SATA SSD.

Yes you can still use Intel Bluetooth.

But like I said, it's unknown at this point if it'd even fit and work in your laptop. In mine it didn't recognise the Wifi adapter when I installed it in the NVMe slot. The only success story I know of is on the Xiaomi Notebook Pro and the old 6200u version of the 13"

**Comment by yllwfsh** [comment]
@iSonik You can check in your hardware specs what type of SSD you have. Probably something like a Samsung PM961 or PM981. Both are NVMe SSDs

**Comment by iSonik** [comment]
@yllwfsh  exactly. I have an NVMe SSD installed but bought another Sata SSD for the other slot. Also the Adapter for the Wifi card does fit into the slot. It is just not recognised

**Comment by yllwfsh** [comment]
@iSonik Yeah so unless somebody finds a way to hack the Xiaomi BIOS it's not going to work.

**Comment by iSonik** [comment]
@yllwfsh there are some hacks for the Pro version. Do you think it would be hard to port one of these?

**Comment by yllwfsh** [comment]
@iSonik Which hacks? Any of those have to do with the BIOS whitelist? In that case maybe

**Comment by yllwfsh** [comment]
@iSonik We have all the known BIOS mods on this repo too: https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS

**Comment by iSonik** [comment]
> @iSonik We have all the known BIOS mods on this repo too: https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS

Yeah i used that one to CFG unlock my u7200.
I meant this one: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods

**Comment by yllwfsh** [comment]
@iSonik None of those would do anything for the BIOS whitelist on our laptops unfortunately

**Comment by iSonik** [comment]
> @iSonik None of those would do anything for the BIOS whitelist on our laptops unfortunately

I see. So the best way would be prob. to port some of the 6200 versions Bios right?

**Comment by yllwfsh** [comment]
Maybe. But I think there's too much that has changed between the CPUs that It would not be safe to try the 6200u BIOS on your machine. Maybe you can ask this on one of the BIOS modding forums out there :) You could give them the BIOSes for all three revisions (6200u, 7200u and 8250u/8550u) and maybe someone smart will find the differences in the PCIe/NVMe whitelist...
