### ISSUE TITLE
internal mic not working

### ISSUE THREAD

**Issue by carlosxfigueroa** [johnnync13/Xiaomi-Mi-Air#16]
as title says the input mic doesnt work, im on the i5 variant

**Comment by johnnync13** [comment]
Use the last efi, should works

**Comment by vimcaw** [comment]
It works for me after using the latest EFI (https://github.com/johnnync13/Xiaomi-Mi-Air/tree/998e35f4dce5f3a083d4aa4e732b450e7b114db5), Thanks.
