### ISSUE TITLE
latest oc can't work

### ISSUE THREAD

**Issue by knifead** [johnnync13/Xiaomi-Mi-Air#160]
now im using the 7.5.6，works well，but the latest can't boot

**Comment by yllwfsh** [comment]
What's going wrong? Clover/OpenCore? Logs?

**Comment by knifead** [comment]
how to get it , Forgive me for not knowing how to get the log

**Comment by yllwfsh** [comment]
Maybe you can try to describe your problem as something like one of these?: https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html

**Comment by knifead** [comment]
panic(cpu 0 caller 0xffffff800c29167c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x150e.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff812b173900 : 0xffffff800bc458f8 
0xffffff812f02bc40 : 0xffffff800bb413f1 
0xffffff812f02bcb0 : 0xffffff800bb3fc2f 
0xffffff812f02bd00 : 0xffffff800bc429f9 
0xffffff812f02bd40 : 0xffffff800bc4225b 
0xffffff812f02bd70 : 0xffffff800c22cae8 
0xffffff812f02bda0 : 0xffffff800c22f9f9 
0xffffff812f02be00 : 0xffffff800c214d8a 
0xffffff812f02bea0 : 0xffffff800c2146b4 
0xffffff812f02bec0 : 0xffffff800bb61565 
0xffffff812f02bf40 : 0xffffff800bb61091 
0xffffff812f02bfa0 : 0xffffff800bac513e 

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxonln=1 igfxonlnfbs=0x010203

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000000b800000
Kernel text base: 0xffffff800ba00000
__HIB  text base: 0xffffff800b900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 521418327946

**Comment by yllwfsh** [comment]
So the problem is that your laptop crashes during wake, after sleeping. This is related to Bluetooth and should be reported to https://github.com/zxystd/IntelBluetoothFirmware

Nothing we can do about it here unfortunately. Until then you can disable the Bluetooth kexts in your Clover/OpenCore or just make sure your laptop doesn't sleep.
