### ISSUE TITLE
11.0: Successfull Big Sur installation!

### ISSUE THREAD

**Issue by vladdenisov** [johnnync13/Xiaomi-Mi-Air#161]
I've Managed to get Big Sur working on my Xiaomi mi Notebook Air 13" 2017.

Used VM to install to internal ssd, then booted it. Used latest [OC](https://github.com/williambj1/OpenCore-Factory/releases), latest kext build using makefile from [this repo](https://github.com/daliansky/XiaoMi-Pro-Hackintosh).

Basically, you need to modify your OC config under NVRAM sections:

![Screenshot 2020-06-25 at 13 24 05](https://user-images.githubusercontent.com/18082735/85702595-3ddfd000-b6e7-11ea-8ad2-1ed7f9f059e5.png).  
Also, check `Booter->Quirks->AvoidRuntimeDefrag` to be `false`

Everything works, except battery and touchpad for me, looks like it's always emulating force touch instead of normal click, but touchpad doesn't appear in settings. We need to wait till SMCBatteryManager is updated to support 11.0.

![Screenshot 2020-06-25 at 13 20 33](https://user-images.githubusercontent.com/18082735/85702046-b003e500-b6e6-11ea-9cbe-f698851c9e1b.png)

PS: Not my real SMBOIS on this screenshot.

**Comment by vladdenisov** [comment]
Sample config:
[config.plist.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4842080/config.plist.zip)

**Comment by yllwfsh** [comment]
Nice!

**Comment by lang-ji** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!

**Comment by Notics-Seed** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by hongtm77** [comment]
@vladdenisov Hi, i have the same model (2017 mi air) Dual Booting Windows 10 and Catalina. Everything is working perfectly and wanted to try Big Sur. Can i install Big Sur as the third boot so that i can test the OS? Can I create a partition from the Catalina SSD and Install on that new partition? will it affect the Catalina OS?
