### ISSUE TITLE
microphone from headphone not working

### ISSUE THREAD

**Issue by Bixio999** [johnnync13/Xiaomi-Mi-Air#162]
When I plug in my headphones using jack, audio works but the only microphone detected is built-in microphone, that is not very usable because of fans spinning sound. 

Is there a way to fix? 

P.S. thanks a lot for this repo, loving Mac OS

**Comment by yllwfsh** [comment]
Yes there's a way!

See https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/Audio

**Comment by Bixio999** [comment]
I tried many times but the only microphone detected is the build-in one. 
I used the ALCPlugFix script.

**Comment by yllwfsh** [comment]
Try the other one: https://github.com/hackintosh-stuff/ComboJack

**Comment by Bixio999** [comment]
Do i need to put VerbStub kext in Clover's EFI folder? Or it refers to another folder?

**Comment by yllwfsh** [comment]
Yes put VerbStub.kext in Clover/kexts/Other and run the Combojack install.sh

Also make sure CodecCommander.kext is removed from your system completely

**Comment by Bixio999** [comment]
Understood, thank you! 

To access the EFI folder do i need to mount its partition using mount command, right?

**Comment by yllwfsh** [comment]
Correct you can do it with the mount commands in Terminal (check that the disk number is correct):

```
diskutil list
sudo diskutil mount /dev/disk0s1
```

... or mount it with Clover configurator or with a tool like https://github.com/corpnewt/MountEFI
