### ISSUE TITLE
7.6 wifi support

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#163]
Hi, i check online and found out that 2018 and 2017 model has the same Intel Wireless AC 8265. Im having 2017 model and updated to the latest 7.6 EFI on OC. Do I need to manually update the wifi kext in order for it to work? Because it is not working for me.

**Comment by johnnync13** [comment]
you have tu install heliPort app 
[HeliPort.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4890180/HeliPort.zip)

**Comment by hongtm77** [comment]
@johnnync13 thank you very much! it works
