### ISSUE TITLE
> 我对Typec接口有一些疑问。我可以在macOS中使用minidp吗？我有一个4k显示器，但是它无法连接到小米笔记本电脑。当然，hdmi接口可以工作，但只能支持4k 30hz。我不确定小米笔记本的typec minidp是否需要与mx150配合使用。我只是想知道小米minidp是否可以在macOS中输出4k 60hz

### ISSUE THREAD

**Issue by yuqZY** [johnnync13/Xiaomi-Mi-Air#164]
> 我对Typec接口有一些疑问。我可以在macOS中使用minidp吗？我有一个4k显示器，但是它无法连接到小米笔记本电脑。当然，hdmi接口可以工作，但只能支持4k 30hz。我不确定小米笔记本的typec minidp是否需要与mx150配合使用。我只是想知道小米minidp是否可以在macOS中输出4k 60hz

Hello, do you need to modify some files with HDMI 4K? My HDMI Mac OS can only 1080p, windows can 4K, but is 30Hz, why can only 1080p Mac? If you know, please let me know

_Originally posted by @cly1998 in https://github.com/johnnync13/Xiaomi-Mi-Air/issues/153#issuecomment-655483108_
不，实际上是不管HDMI还是Type-c转minidp，我都只能获得1080p，这个问题好像跟苹果系统对英特尔核显的输出限制有关，在小米笔记本pro上，葫芦娃EFI好像可以正常输出4k，针对Air的4k支持我没有找到，可能比较难解决

**Comment by johnnync13** [comment]
Firstly,mx150 not works in macOS. Secondly, I don´t have this laptop anymore, so you can try to fix with hackintool

**Comment by yllwfsh** [comment]
Duplicate issue. Continue the discussion in https://github.com/johnnync13/Xiaomi-Mi-Air/issues/153
