### ISSUE TITLE
OpenCore is pretty well supported now, should we still maintain Clover?

### ISSUE THREAD

**Issue by yllwfsh** [johnnync13/Xiaomi-Mi-Air#165]
I understand people like Clover for it's 'ease of use' but since OpenCore is more secure and gaining more users and traction it is clearly the way to go in my opinion for the future releases of macOS. So my question is: Should we still maintain Clover in this repo? I my opinion we can safely drop support for Clover.

@johnnync13 What do you think?

Any users that are big fans of Clover and have a clear and good reason to use it, please feel free to give your opinion below:

**Comment by johnnync13** [comment]
OpenCore is stable now. The problem is that clover fix things and appears more problems. So, to update Clover only need update clover and kexts. Acpi is fixed good

**Comment by chanbaihai** [comment]
> I understand people like Clover for it's 'ease of use' but since OpenCore is more secure and gaining more users and traction it is clearly the way to go in my opinion for the future releases of macOS. So my question is: Should we still maintain Clover in this repo? I my opinion we can safely drop support for Clover.
> 
> @johnnync13 What do you think?
> 
> Any users that are big fans of Clover and have a clear and good reason to use it, please feel free to give your opinion below:

Could Open Core support 4k resolution ?

**Comment by johnnync13** [comment]
Yes. OpenCore is the boot loader but 4k depends of hdmi fix

**Comment by chanbaihai** [comment]
> Yes. OpenCore is the boot loader but 4k depends of hdmi fix

 Could you tell me which hdmi fix should I use ?

**Comment by johnnync13** [comment]
use hackintool is more easy. https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by chanbaihai** [comment]
> use hackintool is more easy. https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

Really thank you,I’ll try it out later

**Comment by changly** [comment]
> > 使用hackintool更容易。https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
> 
> 真的谢谢你，我稍后再试

Is it necessary to change DVMT to 64M? Have you succeeded in the reform?

**Comment by changly** [comment]
> 是。OpenCore是引导加载程序，但4k取决于hdmi修复

Is it necessary to change DVMT to 64M? Have you succeeded in the reform?

**Comment by johnnync13** [comment]
NO

**Comment by changly** [comment]
> @changly请检查https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/BIOS/Enable%204K.md

Thanks to @chanbaihai  for your priority. Already 4k@30hz （HDMI）
