### ISSUE TITLE
Mac OS update for OC

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#167]
Can I update the MacOS normally on OC? Or I will need to backup and re-install the latest version of MacOS?

**Comment by yllwfsh** [comment]
Hi @hongtm77 You should be able to upgrade to 10.15.6 without problems on OC. But always make a backup to be safe just in case :)

**Comment by hongtm77** [comment]
> Hi @hongtm77 You should be able to upgrade to 10.15.6 without problems on OC. But always make a backup to be safe just in case :)

Okay noted. So I backup using time machine? Or?

**Comment by yllwfsh** [comment]
Yeah Time Machine works great with a USB disk or NAS device. Alternatively you could use something like [SuperDuper](https://shirt-pocket.com/SuperDuper/SuperDuperDescription.html)

**Comment by hongtm77** [comment]
> Yeah Time Machine works great with a USB disk or NAS device. Alternatively you could use something like [SuperDuper](https://shirt-pocket.com/SuperDuper/SuperDuperDescription.html)

okay noted. thank you very much. really appreciate it.
