### ISSUE TITLE
Lack NVRAM - Delete - boot-args in all Xiaomi repositories

### ISSUE THREAD

**Issue by stevezhengshiqi** [johnnync13/Xiaomi-Mi-Air#169]
Hi, thank you so much for all the great work.

There's a problem in all of the Xiaomi laptops repositories that the following code is missing in OC config:
```xml
<key>Delete</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>boot-args</string>
			</array>
		</dict>
```
In NVRAM part, `Delete` is not people's usual thinking that it blocks something; however, it is required when new NVRAM fields occur. For safety reasons, OC doesn't overwrite NVRAM field, so it's necessary to use `Delete` to remove old variables. OC only writes to empty corresponding NVRAM field. Therefore, new boot-args will never be preserved if the above lines are missing, for example, add -v in boot-args won't work. 

Please have a check and have a great day. @johnnync13 

Reference: [acidanthera's official OpenCore Sample.plist](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist#L807-L810)

**Comment by johnnync13** [comment]
thank you @stevezhengshiqi. Now I´m on vacation studying ML and DL, so for September or November, I will update the repository

**Comment by yllwfsh** [comment]
Thanks! I can have a look at it maybe today or tomorrow.

**Comment by yllwfsh** [comment]
@stevezhengshiqi @johnnync13 Done!
