### ISSUE TITLE
Command key and Option key are reversed on 2.14

### ISSUE THREAD

**Issue by vimcaw** [johnnync13/Xiaomi-Mi-Air#17]
Previous win key was Command key, Alt key was Option key, now it is reversed, How should I change it back?

**Comment by vimcaw** [comment]
I use Karabiner-Elements to change key map as temporary solution.

**Comment by torkasnueaver** [comment]
change it in Sys Pref > Keyboard > Modifier Keys

**Comment by vimcaw** [comment]
@torkasnueaver Your method is better, thanks.
