### ISSUE TITLE
Windows boot with opencore

### ISSUE THREAD

**Issue by festo95** [johnnync13/Xiaomi-Mi-Air#171]
hi, my build with opencore works fine and great, my only "issue" is that booting windows with opencore i lose windows license and media management by keyboard keys, it is not a big issue but a bit annoing considering that I use primary windows for work and opencore set himself as default bootloader when used to boot macOS.
I may have found a solution here:
https://www.reddit.com/r/hackintosh/comments/h0y0hl/booting_windows_from_opencore_is_it_bad/
I'm not sure how to apply it so I thought it could be helpful to share it with you developers

**Comment by yllwfsh** [comment]
You are correct, it is very hard to fix this issue without breaking something in either macOS or windows. Personally I haven't managed to get it working so I always boot to my Linux/Windows install using the BIOS bootloader (tap F12 when starting the laptop from the 'off' state - doesn't work on restart)

**Comment by johnnync13** [comment]
all fixes are here https://github.com/daliansky/OC-little
