### ISSUE TITLE
Needed to downgrade trackpad kexts on OC to get it working

### ISSUE THREAD

**Issue by timmmmmmmmm** [johnnync13/Xiaomi-Mi-Air#173]
Just did a clean macOS install with the latest version and my trackpad wasn't recognized. I couldn't really remember when and which version, but months ago with an older release my trackpad worked fine so I picked VoodooI2C.kext, VoodooI2CHID.kext and VoodooPS2Controller.kext from release 7.5.7 and put those in my OC/Kext folder. After this the trackpad was working but the click was always triggering a force click. I don't use that function, so I disabled Force Click in the macOS Trackpad settings.

**Comment by yllwfsh** [comment]
Interesting! I'd have to run some tests to confirm but currently I don't have this issue. Did you already try to run the kext cache commands from the troubleshooting section on the latest release?

**Comment by timmmmmmmmm** [comment]
I didn't run those, as I thought they were specifically for Clover and didn't want to mess things further up. I did follow the two points under "Using OpenCore:" though, so I checked kexts on the SSD and did a NVRAM reset.

Would you still recommend running those kext commands under the Clover section?

**Comment by yllwfsh** [comment]
Using OC there should be no need to put any hackintosh kexts on your install disk. Only in the OC/kexts folder. They are 'injected' during boot.

But it can still be beneficial sometimes if there are changes in kexts to clear the kextcache.

NVRAM reset was a good idea too.

If you have time can you try the latest (not released yet) files by downloading/cloning the repo as zip (https://github.com/johnnync13/Xiaomi-Mi-Air/archive/master.zip)?

**Comment by timmmmmmmmm** [comment]
I tried using the latest files in the repo, but still get the same issue. Everything works, except the touchpad. Also tried kext reload and NVRAM reset afterwards.

So I replaced the three Voodoo files again and am up and running again. So although there still might be a bug (for some) it all works pretty great for me 👍  :)
