### ISSUE TITLE
Trying to get DRM protected content to work with Safari

### ISSUE THREAD

**Issue by TheSylex** [johnnync13/Xiaomi-Mi-Air#174]
Neither Netflix nor Prime Video are working on Safari, though they work perfectly fine on Edge Chromium for MacOS.
I suspect it has to do with the way the iGPU is set on OpenCore but I cannot figure it out. The error returned from both platforms looks like it's completely unrelated and doesn't help at all. Any help would be appreciated.

**Comment by yllwfsh** [comment]
Unfortunately DRM content in Safari is not supported with only iGPU on hackintosh as far as I know. On desktop systems with iGPU+AMD or just AMD GPU it might work. You can read more about it on the whatevergreen github page.

**Comment by TheSylex** [comment]
Thanks for the feedback, I took a look at the WhateverGreen FAQ and it in fact confirms what you said.
https://github.com/acidanthera/WhateverGreen/blob/3f5624bdacddd7afc8069ef4277d3d78d6a9dff8/Manual/FAQ.Chart.md
Here if Im not mistaken the Mi Air 2018 would fall in the last category, as the MX150 isn't supported.

Any recommendations for watching Netflix then other than using Edge? You can close the issue as soon as you answer, thanks for the fast feedback anyway :)

**Comment by yllwfsh** [comment]
I currently don't know any other way than to use a Chrome(-based) browser. I think that also means it's limited to 720p. Let's keep an eye on Whatevergreen and hope there's a fix in the future.
