### ISSUE TITLE
bluetooth doesn't working 

### ISSUE THREAD

**Issue by rootwhois** [johnnync13/Xiaomi-Mi-Air#175]

**Comment by yllwfsh** [comment]
You should give us some more info. When does Bluetooth not work? What did you try to fix it? Using Clover or OpenCore?

Bluetooth is working fine here on my laptop using OpenCore and macOS 10.15.6.

**Comment by rootwhois** [comment]
My Bluetooth doesn't working while using OpenCore. It can work using Clover after rebuild kexts.

**Comment by yllwfsh** [comment]
For OC you have to remove all hackintosh kexts from /L/Extensions to let them be injected by OC successfully. Once booted, rebuild kext cache and reboot
