### ISSUE TITLE
Battery drain after sleep (possible MX150 issue)

### ISSUE THREAD

**Issue by mynameissagan** [johnnync13/Xiaomi-Mi-Air#177]
First of all, thanks to everyone who is supporting this project! I'm new to Hackintoshes and trying to use this build as sort of a daily driver. However, there's a major issue for me - battery drain increases significantly after I let my laptop sleep for a while and wake it up (almost 50% more compared to a similar usage scenario after a fresh reboot). In addition, the laptop gets noticeably warmer (±42-45 degrees idle compared to ±36-40 after a reboot).

I have a feeling that it's connected to MX150 working for some reason and macOS not being able to disable it after sleep. 

There's also a possible fix I've found using SSDT-PTSWAK.

- https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PTSWAK.dsl
- https://www.reddit.com/r/hackintosh/comments/gf6j7q/increased_battery_drain_after_wake_from_sleep_xps/ 

I'm very new at messing with ACPI and therefore, not able to test whether it works or not. Perhaps, someone more experienced can try out this SSDT or help to solve the issue in any other possible way? Thanks again!

**Comment by robinlsf** [comment]
Intel nic support 

https://github.com/OpenIntelWireless/itlwm
http://bbs.pcbeta.com/viewthread-1848662-1-1.html

**Comment by timmmmmmmmm** [comment]
I also seem to have battery drain when the device is sleeping. No idea if it's the GPU, would it be possible to test by physically disconnecting it somehow?

**Comment by johnnync13** [comment]
it is bluetooth kext
