### ISSUE TITLE
Improve fan behaviour

### ISSUE THREAD

**Issue by Olasergiolas** [johnnync13/Xiaomi-Mi-Air#179]
For me, it seems like the fan curve that is being used here could be changed in order to imitate what is done [here](https://github.com/hirschmann/nbfc) with the TM1703 config they provide. I don't know if it could be achievable but having the fans stop spinning under low temperature would greatly improve the hackintosh overall experience.

**Comment by johnnync13** [comment]
all fixes are here https://github.com/daliansky/OC-little
