### ISSUE TITLE
Hackintosh Mojave working on Mi Notebook Air i5 7200U too

### ISSUE THREAD

**Issue by guidodelu** [johnnync13/Xiaomi-Mi-Air#18]
Hi since a lot of tries and researches I can 100% assure the compatibility of your guide and EFI folder with Xiaomi Mi Notebook Air 13.3 i5 7200U

Everything works just great with Mojave such as trackpad, brightness and so on.

Of course known bugs are still there.

I have a couple of requests by the way:

1. can anyone suggest the EXACT model of a working USB WiFi adapter AND  the EXACT model of a working USB Bluetooth adapter which work without any configuration?

2. I figured out that Aliexpress sells M2 adapters for WiFi and BT cards which are actually used on MacBooks

(link of the adapter https://www.aliexpress.com/i/32946629990.html)
(link of the card used on MacBooks https://www.aliexpress.com/item/New-Original-BCM94360CSAX-for-Apple-Pro-Retina-A1425-A1502-A1398-Wifi-card-802-11ac-and-Bluetooth/32743619891.html?spm=2114.10010108.1000014.4.13c47a85RyTebR&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.13338.128418.0&scm_id=1007.13338.128418.0&scm-url=1007.13338.128418.0&pvid=23118ad0-c67f-4a13-bc12-00334d58f3dc)

Could anyone investigate and tell if it could work with that configuration?  I could buy those components and help investigating if someone knows and tells me what to do.

I noticed the Mi Notebook Pro community already found a similar workaround. What about us?

**Comment by johnnync13** [comment]
In my Mi Air 4 generation not works. On mi air 12,5 1rt generation works perfectly
