### ISSUE TITLE
Audio device not detected

### ISSUE THREAD

**Issue by maklore74** [johnnync13/Xiaomi-Mi-Air#182]
hello everyone, for no reason at boot the audio device is not detected the volume indicator on the panel cannot be activated. I have all the kext and clover updated to the latest version..any idea?
![Schermata 2020-08-29 alle 12 49 09](https://user-images.githubusercontent.com/63496781/91635125-0eef1e80-e9f6-11ea-8536-d34fe4269fdb.png)

**Comment by johnnync13** [comment]
Use OC, is newer

**Comment by maklore74** [comment]
thanks for reply, you mean open core? but I have Clover!
is it difficult to switch from Clover to OC?
can it be done without reinstalling the operating system?

**Comment by yllwfsh** [comment]
Yes, very easy, basically you just replace the EFI folder with the contents of the EFIOC folder. The only thing you have to do maybe is replace your SMBIOS data (only if you changed it to fix iMessage etc.)

You don't need to reinstall macOS.

**Comment by maklore74** [comment]
ok thanks, I think my SMBIOS data I can retrieve it from the clover config file Right? but if I use OC I shouldn't unlock the bios (CFG)?

**Comment by yllwfsh** [comment]
Yes you can copy the relevant SMBIOS values from your clover config.plist to the OC config.plist. A nice tool for it is ProperTree (see the README.md). The CFG-unlock is optional. The OC folder you can download from the releases page should work without the BIOS patches as is. If you're not comfortable doing the BIOS fixes, I would recommend not to do them. The only thing is potentially your battery life is slightly shorter but performance should be the same.

**Comment by maklore74** [comment]
hello thanks again for your help.
As for the SMBIOS values, will it be enough to change the 4 values deleted in the attached photo?
Do you think the battery will last much shorter than the configuration with Clover?
Will I also need to delete the kext copied to / Library / Extensions / rebuild Kernel Extension Cache?
![Schermata 2020-09-01 alle 21 25 05](https://user-images.githubusercontent.com/63496781/91898557-3109ca80-ec9c-11ea-8ded-5ffe756a6de1.png)

**Comment by yllwfsh** [comment]
No problem!

Yes replacing those 4 values will do it ;)

I think the battery life should be similar but that's something to test out :) Make a backup of you Clover EFI just in case.

You might want to leave the kexts in L/E for now (if you want to return to Clover) but once it boots using OC, delete them (this might fix the audio problem then)

In the ideal case, OC will detect Windows and Ubuntu installs. Be aware that if you boot those using OC you might encounter problems with the activation in Windows for instance (it will think it runs on a mac). You can always multi-boot via the UEFI on the laptop (F2 or F12 during boot) to boot them 'natively'.

Let us know if this actually fixes your Audio :)

**Comment by maklore74** [comment]
Windows is on the primary ssd, Mac and Ubuntu on the second ssd instead. Clover does not create any problems at boot..
Win is my main operating system I would not want to compromise it and be forced to reinstall everything!

**Comment by yllwfsh** [comment]
@maklore74 Just replacing the EFI folder on the macOS ssd should not compromise Windows or any files. It's just if you boot Windows using OC you might find that it's not activated. In case you do find a Windows/MS folder and a ubuntu folder in your EFI folder, I'd leave them in place, just replacing the clover folder with the oc folder

**Comment by maklore74** [comment]
I replaced the Clover folder with that of OC also resulting from bios it is no longer possible to access MacOs only Win and Ubuntu start up..
Now I don't know how to access the EFI partition to restore Clover folder

**Comment by maklore74** [comment]
update:
I managed to restore the old configuration with Clover unfortunately the audio still doesn't work.
I believe that the switch from Clover to OC should be done from a clean install ..

**Comment by yllwfsh** [comment]
@maklore74 did you perhaps also remove the Windows and ubuntu EFI folders? Did you manage to boot using OC? Was Audio fixed when you booted using OC?

**Comment by maklore74** [comment]
> @maklore74 did you perhaps also remove the Windows and ubuntu EFI folders? Did you manage to boot using OC? Was Audio fixed when you booted using OC?
I was able to boot with OC but at the same time I lost the ability to boot Ubuntu.
OC still gave me problems starting MacOs so I reset Clover
Audio still not working!!!

**Comment by yllwfsh** [comment]
@maklore74 can you try to replace AppleALC.kext and Lilu.kext with the newest versions from:

https://github.com/acidanthera/AppleALC/releases
https://github.com/acidanthera/Lilu/releases

Make sure to replace them both in /Library/Extensions/ AND in EFI/Clover/Kexts/other and then rebuild the kextcache!

**Comment by maklore74** [comment]
> @maklore74 can you try to replace AppleALC.kext and Lilu.kext with the newest versions from:
> 
> https://github.com/acidanthera/AppleALC/releases
> https://github.com/acidanthera/Lilu/releases
> 
> Make sure to replace them both in /Library/Extensions/ AND in EFI/Clover/Kexts/other and then rebuild the kextcache!
is the first thing I did but without success

**Comment by yllwfsh** [comment]
Hmm then I'm at a loss... I'll think about it a little bit and if I think of something I'll let you know. Maybe @johnnync13 has additional troubleshooting ideas?

**Comment by johnnync13** [comment]
All kext must be on efi folder, not in macOS!!!

**Comment by maklore74** [comment]
sorry I don't understand, with clover the kexts must also be in / Library / Extensions / or I'm wrong?
with OC instead only in the EFI folder I know this ..
now it has to say that with the latest Clover update and kexts the audio is magically working again, but I have not updated the kexts in the folder / Library / Extensions / I am afraid that replacing them and then rebuild the kextcache, may cause some new error ..

**Comment by johnnync13** [comment]
Kext must always go in the efi folder, not in the macOS folders

**Comment by maklore74** [comment]
> Kext must always go in the efi folder, not in the macOS folders

Sorry Johnny but in your guide you wrote:

Copy all the Kernel Extensions (kexts) from the EFI/CLOVER/kexts/Other to your system's /Library/Extensions folder (this is important, otherwise keyboard/trackpad and other devices might not work)
Execute these commands in Terminal to rebuild Kernel Extension Cache:

kexts are in macOS folder..

**Comment by johnnync13** [comment]
THIS IS OUTDATED

**Comment by maklore74** [comment]
> THIS IS OUTDATED
so can I delete them from the / Library / Extensions folder? without causing damage?

**Comment by johnnync13** [comment]
yes but after sudo kextcache -i or use hackintool for this

**Comment by johnnync13** [comment]
if you can't fix, do clean install... 
all fixes are here https://github.com/daliansky/OC-little
