### ISSUE TITLE
Both OC version of 7.6.2 and 7.6.1 not working (on i5 7200u)

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#185]
i have tried both of the OC version is not working. on the dual boot screen, when choose MacOS, it will kept bringing back to the boot options. will not boot to MacOS. I have changed back to 7.6 OC

**Comment by hongtm77** [comment]
Is this only compatible with BigSur?

**Comment by johnnync13** [comment]
I only support 8250u and 8500u, maybe you have to mod the bios

**Comment by vimcaw** [comment]
My Mi Air CPU is 8550U, but it also doesn't work, same as you, after rollback to 12bf4ea, it works.

**Comment by johnnync13** [comment]
@vimcaw try to modify new config.plist tu sign in. I have macbook pro now...

**Comment by vimcaw** [comment]
@johnnync13 Yeah, after updating to [v7.6.3 (release)](https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.6.3), it works perfectly, thank you!

**Comment by johnnync13** [comment]
Do it Works with big sur?

**Comment by vimcaw** [comment]
I don't upgrade to Big Sur yet, expect others can share this.

**Comment by hongtm77** [comment]
@johnnync13 Just tested v7.6.3 too. Works perfectly on my 7200u. Thanks for the update. May I know, can i dual boot Catalina and Big Sur on the same SSD? I can test the Big Sur whether it is working.

**Comment by johnnync13** [comment]
Yes. Big sur working perfectly

**Comment by hongtm77** [comment]
> Yes. Big sur working perfectly

I just installed Big Sur on my 3rd boot. Everything works perfectly. Thanks

**Comment by hongtm77** [comment]
By the way, do we install heliport for wifi on Big Sur?

**Comment by yllwfsh** [comment]
> By the way, do we install heliport for wifi on Big Sur?

I haven't tested it, but if you want to use native WiFi i guess you have to use Heliport on Big Sur
