### ISSUE TITLE
Can I update bigsur directly now？

### ISSUE THREAD

**Issue by YanYuHanYun** [johnnync13/Xiaomi-Mi-Air#186]
Use the V7.6.2,Can I update bigsur directly now？

**Comment by johnnync13** [comment]
https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#acpi
https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#grabbing-the-installer

**Comment by johnnync13** [comment]
Now, you can update directly @YanYuHanYun
