### ISSUE TITLE
Small problems after using the latest OC boot you released

### ISSUE THREAD

**Issue by msiLiu** [johnnync13/Xiaomi-Mi-Air#187]
first problem
There will be a prompt every time the boot interface
OCS:No schema for processorType at 2index, context <Generlc>
Does not affect the normal boot, what is the reason?

second problem

<key>AppleCpuPmCfgLock</key>
<true/>
<key>AppleXcpmCfgLock</key>
<true/>

Change to:

<key>AppleCpuPmCfgLock</key>
<false/>
<key>AppleXcpmCfgLock</key>
<false/>

If you change these two settings, you will get stuck on the boot interface and cannot enter the system

**Comment by yllwfsh** [comment]
The OC message is harmless but I'll investigate it so it can be fixed.

In order to activate native CPU power management read https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS first.

**Comment by yllwfsh** [comment]
Fixed in https://github.com/johnnync13/Xiaomi-Mi-Air/commit/a3c26e4a9c797896c21c330c952c485cff2381a9
