### ISSUE TITLE
Use EFI for 10.13.6

### ISSUE THREAD

**Issue by elGiank** [johnnync13/Xiaomi-Mi-Air#19]
Hi
I have successfully installed High Sierra (10.13.6) on my Mi Air 2018 using the EFI from here [stevezhengshiqi/XiaoMi-Pro](https://github.com/stevezhengshiqi/XiaoMi-Pro) but I have a couple of issues (power management, brightness key and restarts when turning on) that looks solved with your EFI. So my question is, Do I have to make a clean install of Mojave to use this EFI? or there is a way to just "update" my EFI to use this one?.

=================================================================

Hola!
He podido instalar High Sierra (10.13.6) en mi Mi Air 2018 usando la EFI de [stevezhengshiqi/XiaoMi-Pro](https://github.com/stevezhengshiqi/XiaoMi-Pro), pero aun tengo problemas con el % de la bateria y algunos reinicios al entrar a macOS. Lo de la bateria aparece resuelto y posiblemente los reinicios tmbn se arreglen con tu EFI. Por lo que mi pregunta es, Tengo que hacer una instalacion limpia de Mojave usando tu EFI? o existe alguna forma de actualizar mi EFI con la tuya para que todo funcione?

Saludos!

**Comment by vimcaw** [comment]
You can just replace the Clover folder from EFI partition.

**Comment by elGiank** [comment]
Looks like it didn't work for me :(. I replaced my Clover folder with the one provided here and now the macOS is dead. I will try a clean installation and then share my experience.

**Comment by vimcaw** [comment]
Nice try, look forward to your experience.

**Comment by elGiank** [comment]
Good news, now is working :)
I did a clean install of Mojave using the EFI folder from this repo and now everything is working like a charm!
My final thought is that the EFI folder provided here is not working well with High Sierra.
BTW, I have a Xiaomi Mi Air 13.3 i5

**Comment by vimcaw** [comment]
Congratulation! Thank you for sharing the experience.

Gian Carlo Vegas R. <notifications@github.com> 于2019年3月21日周四 上午10:51写道：

**Comment by hawkinchina** [comment]
if you installed High Sierra (10.13.6) , i think you  should the version of tag 1.2.. @elGiank
