### ISSUE TITLE
How to configure "SecretBootModel" correctly

### ISSUE THREAD

**Issue by EdenJohnson2006** [johnnync13/Xiaomi-Mi-Air#190]
[https://github.com/OpenIntelWireless/itlwm]() releases "AirPortItlwm",but it needs 
> Set SecureBootModel to Default to make sure IO80211Family loads properly.

I use the "OpenCoreConfigurator" and set SecretBootModel to Default,but it caused the startup loop.
So how to configure SecretBootMode to make the machine boot normally and activate AirPort Itlwm?

**Comment by Olasergiolas** [comment]
Same, I can't even use the latest release (7.6.4) without having opencore hanging before the boot select menu. Restoring securebootmodel to Disabled makes it boot again but also breaks itlwm functionality in the process.

**Comment by johnnync13** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card

**Comment by Olasergiolas** [comment]
> https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card

Setting DmgLoading to Signed made OC boot again while using 7.6.4 but itlwm.kext won't load regardless of IO80211Family being forced to load or not.

[config.plist.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/5282085/config.plist.zip)

**Comment by Olasergiolas** [comment]
7.6.6 didn't fix wifi for me either but I got it working already by:
1. Changing DmgLoading to signed in config.plist
2. Forcing IO80211Family to load
3. Removing the existing itlwm.kext
4. Adding the 1.1.0 Airportitlwm kext from here [https://github.com/OpenIntelWireless/itlwm](url)
5. Doing an OC Snapshot in Propertree

**Comment by TheSylex** [comment]
> 7.6.6 didn't fix wifi for me either but I got it working already by:
> 
> 1. Changing DmgLoading to signed in config.plist
> 2. Forcing IO80211Family to load
> 3. Removing the existing itlwm.kext
> 4. Adding the 1.1.0 Airportitlwm kext from here [https://github.com/OpenIntelWireless/itlwm](url)
> 5. Doing an OC Snapshot in Propertree

Can confirm this works, although step 5 isn't needed obviously.

**Comment by johnnync13** [comment]
so, you can do pull request
