### ISSUE TITLE
Stucked on 'MI' logo on boot

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#192]
When turned on the laptop, i was stucked at the Mi logo and cant even see the boot menu. *v7.6.6 please help

**Comment by KuangXilai** [comment]
I got the same problem, I uses the files in the 7.6.6 to replace the EFI floder,the after reboot,it just stucked at the Mi logo

**Comment by EdenJohnson2006** [comment]
Try Set "DmgLoading" to signed in Misc - Secutity
![0Cy5Yn.jpg](https://s1.ax1x.com/2020/09/25/0Cy5Yn.jpg)

**Comment by festo95** [comment]
> 
> 
> Try Set "DmgLoading" to signed in Misc - Secutity
> ![0Cy5Yn.jpg](https://camo.githubusercontent.com/46fabe3649332a68a94c324e60d114ded381515c/68747470733a2f2f73312e617831782e636f6d2f323032302f30392f32352f30437935596e2e6a7067)

I try this, manage to boot again but faced a "itlwm is not running message" from Heliport App

**Comment by EdenJohnson2006** [comment]
> I try this, manage to boot again but

I'm useing AirPort itlwm,and it can work
![0CR8K0.jpg](https://s1.ax1x.com/2020/09/25/0CR8K0.jpg)

**Comment by github-wang** [comment]
When turned on the laptop, i was stucked at the Mi logo and cant even see the boot menu. *v7.6.6 please help

**Comment by github-wang** [comment]
the usb flash disk cant even see the boot menu

**Comment by EdenJohnson2006** [comment]
> the usb flash disk cant even see the boot menu

Use F12 (BootMenu)

**Comment by github-wang** [comment]
> > USB闪存盘甚至看不到启动菜单
> 
> 使用F12（BootMenu）

"DmgLoading" to signed in Misc - Secutity is ok,very good,thanks

**Comment by vimcaw** [comment]
I can't boot macOS after updating to V7.6.7 which fix DmgLoading option, the behaviou is, on the dual boot screen, after choosing macOS, it will back to the dual boot screen.
