### ISSUE TITLE
itlwm is not working

### ISSUE THREAD

**Issue by KuangXilai** [johnnync13/Xiaomi-Mi-Air#193]
After updated to v7.6.7 ,the HeliPort reported that "itlwm is not running"

**Comment by EdenJohnson2006** [comment]
Itlwm is replaced by AirPort Itlwm in a0bab9f

**Comment by rootwhois** [comment]
you can find the network in the system preference setting, it works.
在系统便好-网络中可以开启系统内置的Wi-Fi哦。

**Comment by KuangXilai** [comment]
The "WiFi" option didn't show up in the network preference setting,should I reinstall the Mac OS?
网路设置中并没有看到WiFi,是因为之前装了Heliport App的影响吗?是否需要重装Mac OS?

**Comment by rootwhois** [comment]
Oops, I replaced the itlwm.kext and reboot, then it works. Maybe you can try to reboot, if do not work, you can replace the itlwm.kext which you used before. It work on Big Sur, i5-7200U.
我替换了该itlwm.kext，重启后就工作了。你可以试试，如果不成功，就先暂时将该文件替换成你之前的吧。我的电脑环境是Big Sur，处理器是i5-7200U。

**Comment by EdenJohnson2006** [comment]
> Oops, I replaced the itlwm.kext and reboot, then it works. Maybe you can try to reboot, if do not work, you can replace the itlwm.kext which you used before. It work on Big Sur, i5-7200U.
> 我替换了该itlwm.kext，重启后就工作了。你可以试试，如果不成功，就先暂时将该文件替换成你之前的吧。我的电脑环境是Big Sur，处理器是i5-7200U。

7.6.7 should fix dmgloading and secretbootmode , maybe the name?
7.6.7 应该已经将SecretBootMode设置正确了，是不是kext名字的问题？

**Comment by rootwhois** [comment]
I don't know, I use the v7.6.2 or v7.6.3 now. Maybe you can try it.
我用的是7.6.2或者7.6.3，这几天更新的比较频繁的版本还没开始用，你可以尝试下哦。

**Comment by Creedowl** [comment]
I replaced the itlwm.kext with [AirportItlwm_v1.0_Beta_Catalina.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_Catalina.kext.zip) and renamed it to itlwm.kext, then it works

**Comment by rootwhois** [comment]
> I replaced the itlwm.kext with [AirportItlwm_v1.0_Beta_Catalina.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_Catalina.kext.zip) and renamed it to itlwm.kext, then it works

yep, I pull the Big Sur version, and it may cause the Catalina user can't use the wifi model. Sorry about that. 
对的，我推送的是Big Sur 版本的，可能导致Catalina用户无法使用Wi-Fi模块。 抱歉。

**Comment by KuangXilai** [comment]
You are right! It's the name problem,Thanks Guys!!

**Comment by hongtm77** [comment]
> I replaced the itlwm.kext with [AirportItlwm_v1.0_Beta_Catalina.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_Catalina.kext.zip) and renamed it to itlwm.kext, then it works

Hi, I saw there is 2 version, one is Catalina and one is BigSur. I am dual booting both, so does that mean that I need to change the itlwm.kext when I boot to another OS?

**Comment by Creedowl** [comment]
> > I replaced the itlwm.kext with [AirportItlwm_v1.0_Beta_Catalina.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_Catalina.kext.zip) and renamed it to itlwm.kext, then it works
> 
> Hi, I saw there is 2 version, one is Catalina and one is BigSur. I am dual booting both, so does that mean that I need to change the itlwm.kext when I boot to another OS?

I think so. Because I can't use wifi when using the BigSur version on Catalina

**Comment by hongtm77** [comment]
Hi, anyone experiencing a slower connection using the Airportitlwm compare to previous itlwm?

**Comment by EdenJohnson2006** [comment]
> Hi, anyone experiencing a slower connection using the Airportitlwm compare to previous itlwm?

No.It is as fast as itlwm on my 8265AC

**Comment by darkleon78** [comment]
Hi guys. Can I ask you about some help with itlwm?
As I understood itlwm.kext is work with HeliPort software which provides feature to select the necessary networks and provide a passwords. Airportitlwm can't do this...
I have AIR with i7 8th model TIM1703 with 1710 BIOS and on my laptop only Airportitlwm is works
I read all articles with FAQ and other guides but can't run itlwm.kext on my laptop...
Does anyone know any secrets why it's happening?

**Comment by hongtm77** [comment]
> Hi guys. Can I ask you about some help with itlwm?
> As I understood itlwm.kext is work with HeliPort software which provides feature to select the necessary networks and provide a passwords. Airportitlwm can't do this...
> I have AIR with i7 8th model TIM1703 with 1710 BIOS and on my laptop only Airportitlwm is works
> I read all articles with FAQ and other guides but can't run itlwm.kext on my laptop...
> Does anyone know any secrets why it's happening?

Airportitlwm dont need heliport. Just use the native wifi

**Comment by rootwhois** [comment]
> Hi guys. Can I ask you about some help with itlwm?
> As I understood itlwm.kext is work with HeliPort software which provides feature to select the necessary networks and provide a passwords. Airportitlwm can't do this...
> I have AIR with i7 8th model TIM1703 with 1710 BIOS and on my laptop only Airportitlwm is works
> I read all articles with FAQ and other guides but can't run itlwm.kext on my laptop...
> Does anyone know any secrets why it's happening?

itlwm needs to be used in combination with heliport, but Airporitlwm doesn't need. Heliport is a software, the password stored in this software and the system are not interoperable. If you have the iPad or iPhone, using Airitlwm it will read the password stored from iCloud, and doesn't you to input again.

**Comment by darkleon78** [comment]
Hi guys.
I have found and used this guide [https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/Docs/Drive-Native-Intel-Wireless-Card.pdf](url) and now all works. Itlwm is working. Heliport is OK and now I can select network which i need to connect.
