### ISSUE TITLE
Trackpad not working on older versions, newer versions won't boot

### ISSUE THREAD

**Issue by finner** [johnnync13/Xiaomi-Mi-Air#195]
Xiaomi mi air 2018 (8th i5) and 120C bios won't boot with most of the EFI versions found here.
 Only 2.16 works with trackpad
 7.2.5 can boot but on 7.2.5 trackpad wont work.
Latest 7.6.8 will show loading screen but it will crash before entering OS.

OSX Catalina installed on 500GB sata m2 drive.

**Comment by rbotte** [comment]
Latest 7.6.8 having the same issue in BIOS P1710, show loadingscreen and then crash.
