### ISSUE TITLE
not good

### ISSUE THREAD

**Issue by knifead** [johnnync13/Xiaomi-Mi-Air#196]
panic(cpu 0 caller 0xffffff7f8846c231): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x1e VID=0xffff DID=0xffff
. FW Revision=111110WD\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320
Backtrace (CPU 0), Frame : Return Address
0xffffff81268b39e0 : 0xffffff8005b1a65d 
0xffffff81268b3a30 : 0xffffff8005c54a75 
0xffffff81268b3a70 : 0xffffff8005c465fe 
0xffffff81268b3ac0 : 0xffffff8005ac0a40 
0xffffff81268b3ae0 : 0xffffff8005b19d27 
0xffffff81268b3be0 : 0xffffff8005b1a117 
0xffffff81268b3c30 : 0xffffff80062c1a6c 
0xffffff81268b3ca0 : 0xffffff7f8846c231 
0xffffff81268b3cc0 : 0xffffff7f88457362 
0xffffff81268b3e20 : 0xffffff80062322d9 
0xffffff81268b3e90 : 0xffffff80062321f9 
0xffffff81268b3ec0 : 0xffffff8005b5c605 
0xffffff81268b3f40 : 0xffffff8005b5c131 
0xffffff81268b3fa0 : 0xffffff8005ac013e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[2D554F70-092B-3B6B-B2AD-5C09EDB5B4F8]@0xffffff7f88449000->0xffffff7f8848bfff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[FF23E772-067A-3614-B922-33C82CEC0CBF]@0xffffff7f86c2e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[44472E6F-8DA0-3B46-ADEF-AFF76EC6C6DB]@0xffffff7f86512000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[10E46031-889C-3FB7-8B4B-0DECAB5AE325]@0xffffff7f883e7000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[CB3CB8CA-881A-37F3-A96B-8063CAF0476D]@0xffffff7f86880000
            dependency: com.apple.iokit.IOReportFamily(47)[72B53B80-5713-30C1-BAD8-9D55FD718DA2]@0xffffff7f86449000

BSD process name corresponding to current thread: kernel_task
Boot args: darkwake=0 gfxrst=1 igfxonln=1 igfxonlnfbs=0x010203 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide:     0x0000000005800000
Kernel text base: 0xffffff8005a00000
__HIB  text base: 0xffffff8005900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 3570849152033

**Comment by johnnync13** [comment]
what ssd are you using?

**Comment by knifead** [comment]
sn750 500g，well，Maybe it's because I removed the original network card on the motherboard and replaced bcm94360cs2

**Comment by yllwfsh** [comment]
@knifead Did you try to reset your NVRAM? I've noticed this solved some PCIe problems on my desktop hac once or twice.

**Comment by knifead** [comment]
@johnnync13 I will test it again and I will promptly feedback any questions

**Comment by johnnync13** [comment]
If you put wifi on nvme you should delete NVMEFix.kext

**Comment by knifead** [comment]
Two days later, it worked very well, and there was no such problem again. I removed the kext driver for intelbluetooth. Before I thought that cs2 needs airportbcmfixup, but not, so I also removed it.airportltlwm has also been removed.
