### ISSUE TITLE
Stop Sign

### ISSUE THREAD

**Issue by petriccions** [johnnync13/Xiaomi-Mi-Air#197]
As title says, I'm trying to upgrade from 10.15.6 to Big Sur Beta with your EFI folder. I have your same exact notebook, Mi Air 2018, but verbose stops in a while and a stop sign appears.

**Comment by johnnync13** [comment]
this efi only works now at big sur

**Comment by davideakadudu** [comment]
Hi, thank you for your work first of all.
i have the same laptop of you with Catalina, and I have the same issue of the other user. How did you update from Catalina to Big Sur?

**Comment by johnnync13** [comment]
if you have catalina, change airportitlwm catalina version
