### ISSUE TITLE
Cannot enter the system

### ISSUE THREAD

**Issue by hsmliu** [johnnync13/Xiaomi-Mi-Air#198]
I updated macos11 and changed the 7.6.8 OC boot, and then I can't enter the system

**Comment by xiyanxy** [comment]
试试我这个：https://github.com/Vaimibao/Xiaomi-Air-Hackintosh-Big_Sur
我没后续更新，这是oc0.6.0，你试试更新0.6.3能不能全新安装

**Comment by as005401** [comment]
I have the same problem after I updated macos11 (from the previous beta to the last beta) OC 7.6.8.

**Comment by rootwhois** [comment]
You can try this version, it works on 7200U, beta10. [v7.6.4](https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.6.4)

**Comment by Creedowl** [comment]
https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2740811
This works for me, you can have a try.

**Comment by hsmliu** [comment]
> https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2740811
> This works for me, you can have a try.

thank you
I follow the response in the link，Change security/SecureBootModel/ change this from Default to Disabled, Then reset nvrm to enter the system。

**Comment by hsmliu** [comment]
> You can try this version, it works on 7200U, beta10. [v7.6.4](https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.6.4)

This doesn't solve my problem

**Comment by as005401** [comment]
When I changed SecureBootModel from default to disable my opencore can't download (just black screen) . How I can fix it?

**Comment by EdenJohnson2006** [comment]
> When I changed SecureBootModel from default to disable my opencore can't download (just black screen) . How can I fix it?

Set "DmgLoading" To Any

**Comment by as005401** [comment]
> > When I changed SecureBootModel from default to disable my opencore can't download (just black screen) . How can I fix it?
> 
> 
> 
> Set "DmgLoading" To Any

Thanks for helping but it didn't help me. I have the same black screen.

**Comment by as005401** [comment]
I understood my problem. I just wrote 'disable' instead of 'disabled'. Now I successfully updated Big Sur.

**Comment by davideakadudu** [comment]
For me nothing of this was good to fix my problem 😒
