### ISSUE TITLE
airportitlwm on Catalina

### ISSUE THREAD

**Issue by davideakadudu** [johnnync13/Xiaomi-Mi-Air#199]
hi, there is no chance to make airportitlwm.kext usable on Catalina?

**Comment by rootwhois** [comment]
You can download this kext to replace the itlwm.kext. [AirportItlwm_v1.0_Beta_Catalina.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_Catalina.kext.zip)

**Comment by davideakadudu** [comment]
yes but I don't know how to set the config.plist to make it functional. could you help me?

**Comment by rootwhois** [comment]
Just rename the airportitlwm.kext to itlwm.kext, and replace it, then reboot.

**Comment by davideakadudu** [comment]
really so simple? have I to uninstall heliport before restart the Mac?

**Comment by davideakadudu** [comment]
so there is no need to touch anything in the config.plist?

**Comment by rootwhois** [comment]
There is no need to touch anything in the config.plist.
You can try a moment first. If you like Airportitlwm, you can uninstall heliport. 
Or, you can download the itlwm for Catalina and use heliport to connect WIFI.

**Comment by davideakadudu** [comment]
![Schermata 2020-10-18 alle 13 31 26](https://user-images.githubusercontent.com/72854390/96366241-a8a99100-1146-11eb-8661-6b2b95595a28.png)
nothing happens :(

**Comment by rootwhois** [comment]
Did you rename airportitlwm.kext to itlwm.kext and replace the older kext?
Go to System Preferences -> Network. If there is no Wifi item, maybe it doesn't support and you can use [itlwm_v1.1.0_Stable.kext.zip](https://heliport.bat-bat.workers.dev/https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/itlwm_v1.1.0_Stable.kext.zip) and heliport.

**Comment by davideakadudu** [comment]
![Schermata 2020-10-18 alle 13 59 50](https://user-images.githubusercontent.com/72854390/96366926-0344ec00-114b-11eb-8043-738a7e96dfa8.png)
![Schermata 2020-10-18 alle 14 05 27](https://user-images.githubusercontent.com/72854390/96366930-093acd00-114b-11eb-94d5-9dd5c2fa96dd.png)


nothing in preferences - network. do you think my wifi module is not supported?

**Comment by finner** [comment]
Latest 7.6.8 EFI contains a config.pist that supports airportitwlm kext. So make sure you have this EFI, mount the EFI partition, enter the Kexts folder and replace the airportitwlm.kext with this file https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Catalina-v1.2.0-DEBUG-alpha-7ae2ecd.zip

Also make sure itwlm.kext is deleted from Kexts folder as both kexts cannot co-exists. Reboot and check if everything is ok.

**Comment by davideakadudu** [comment]
> Latest 7.6.8 EFI contains a config.pist that supports airportitwlm kext. So make sure you have this EFI, mount the EFI partition, enter the Kexts folder and replace the airportitwlm.kext with this file https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Catalina-v1.2.0-DEBUG-alpha-7ae2ecd.zip
> 
> Also make sure itwlm.kext is deleted from Kexts folder as both kexts cannot co-exists. Reboot and check if everything is ok.

how can I check the EFI version?

**Comment by finner** [comment]
No need to check. Download from this repo latest release, unpack, rename EFIOC to EFI and mount the EFI partition of your catalina ssd and delete the old EFI folder and copy the new.

**Comment by davideakadudu** [comment]
> No need to check. Download from this repo latest release, unpack, rename EFIOC to EFI and mount the EFI partition of your catalina ssd and delete the old EFI folder and copy the new.

aww ok, I'm with this EFI then. so, I erase itwlm.kext, put the one in the link and what have I to do in config.plist?

**Comment by finner** [comment]
You dont touch config.plist. It has everything you need

**Comment by davideakadudu** [comment]
> You dont touch config.plist. It has everything you need

so have I to rename the airportitwlm.kext with itwlm.kext?

**Comment by finner** [comment]
No. Do the following:

1. Mount the EFI Partition
2. Enter the Kexts folder (EFI/OC/Kexts/)
3.Delete itwlm.kext if present
4. Copy into that folder airportitwlm.kext download from https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Catalina-v1.2.0-DEBUG-alpha-7ae2ecd.zip
5.Reboot and check

**Comment by davideakadudu** [comment]
> No. Do the following:
> 
> 1. Mount the EFI Partition
> 2. Enter the Kexts folder (EFI/OC/Kexts/)
>    3.Delete itwlm.kext if present
> 3. Copy into that folder airportitwlm.kext download from https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Catalina-v1.2.0-DEBUG-alpha-7ae2ecd.zip
>    5.Reboot and check

I didi all the steps. nothing happens for me.

**Comment by finner** [comment]
Are you sure you have latest EFI? If not 
1. delete the EFI folder found in your EFI partition. 
2.Then download this https://github.com/johnnync13/Xiaomi-Mi-Air/archive/v7.6.8.zip
3. Extract this archive and rename EFIOC to EFI
4.Copy EFI folder to EFI partition of your SSD
5.Replace airportitwlm.kext with the one I told you

**Comment by davideakadudu** [comment]
> Are you sure you have latest EFI? If not
> 
> 1. delete the EFI folder found in your EFI partition.
>    2.Then download this https://github.com/johnnync13/Xiaomi-Mi-Air/archive/v7.6.8.zip
> 2. Extract this archive and rename EFIOC to EFI
>    4.Copy EFI folder to EFI partition of your SSD
>    5.Replace airportitwlm.kext with the one I told you

It works!! But there is a problem with my apple account. Is it normal?

**Comment by finner** [comment]
I get some notifications as well but apart from that appstore works fine.

**Comment by davideakadudu** [comment]
> I get some notifications as well but apart from that appstore works fine.

Ok thank you very much

**Comment by hsmliu** [comment]
airportitlwm is easy to drop, it might as well continue to use itlwm

**Comment by changly** [comment]
- [ ] 

1. 

- 

> 
![Uploading image.png…]()

**Comment by changly** [comment]
What if Bluetooth doesn't work?

**Comment by changly** [comment]
> _`[
![Uploading QQ20201025-142856.png…]()
](url)`_

**Comment by changly** [comment]
![Uploading QQ20201025-142856.png…]()

**Comment by changly** [comment]
> Are you sure you have latest EFI? If not
> 
> 1. delete the EFI folder found in your EFI partition.
>    2.Then download this https://github.com/johnnync13/Xiaomi-Mi-Air/archive/v7.6.8.zip
> 2. Extract this archive and rename EFIOC to EFI
>    4.Copy EFI folder to EFI partition of your SSD
>    5.Replace airportitwlm.kext with the one I told you

What if Bluetooth doesn't work?

**Comment by kojinmalia** [comment]
> **Latest 7.6.8 EFI contains a config.pist that supports airportitwlm kext**. So make sure you have this EFI, mount the EFI partition, enter the Kexts folder and replace the airportitwlm.kext with this file https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Catalina-v1.2.0-DEBUG-alpha-7ae2ecd.zip
> 
> Also make sure itwlm.kext is deleted from Kexts folder as both kexts cannot co-exists. Reboot and check if everything is ok.

Can you specify what in the config.plist makes airportitwlm kext supported..? Just curious so i can adapt to former (i want to stay on Mojave)!
