### ISSUE TITLE
Update from Clover to OpenCore

### ISSUE THREAD

**Issue by Bixio999** [johnnync13/Xiaomi-Mi-Air#201]
Hi. I've been using this EFI for a long time, but since I installed it months ago I never updated EFI Version or MacOS (I tried once updating MacOS from 10.15.5 to 10.15.6 but during reboot in Clover menu appeared 3 more options and choosing again the boot from SSD interrupted the installation because of an error; i clarify that I can't say what other options do because texts in Clover are compressed and hard to read, I read that it was a bug but never undestood how to fix). 

I used Clover because of first attempt to installing MacOS in my life, so I followed the most common guide. Now I see that OC has been more updated than Clover, and more efficient so I want to switch to OC but I prefer to not format my SSD because of files and documents I've created and downloaded in my PC. 
Is there a way to easily switch from Clover to OpenCore without losing my data? Or is a clean install recommanded to avoid compatibiliy issues? 

Thanks again for this repo and sorry if it is not the right way to ask questions like this.

**Comment by finner** [comment]
It should be enough just to replace your EFI with the most current one. If it not boots just revert to the old EFI.

I had issues using the most recent EFI so I had to format and re-install Catalina from scratch in order to boot OC with latest Catalina.

**Comment by Bixio999** [comment]
Do you suggest to change the Clover EFI with the OC folder? Doing only that should work?  

If I get issues from this operation and being not able to boot system, how can i access to EFI partition to revert the folder? Isn't it in APFS? Can Windows be able to read it? 

Btw thanks for the answer. Probably I will backup the most important files before doing anything.

**Comment by finner** [comment]
Yes, this is the way to do it. Download latest release from here, rename EFIOC to EFI and paste that folder into EFi partition. First backup your previous EFI folder into a USB stick in order to restore it in case your hackintosh wont boot with the OC EFI.

Accessing EFI partition from Windows:
1.Use diskpart to assign a letter to EFI partition
2. Install Explorer++ and run it as administrator. Access the EFI partition and copy paste the folder.

**Comment by Bixio999** [comment]
Understood, thanks a lot. Soon I'll try. 

About MacOS updates, once I switch to OpenCore EFI I should be able to update directly from settings, right?
