### ISSUE TITLE
Can't install big sure

### ISSUE THREAD

**Issue by davideakadudu** [johnnync13/Xiaomi-Mi-Air#202]
Hi, first of all tx for your work. 
I need help: I'm trying to install big sur, but after installing it (after two normal reboot during the installation), at the end when I boot from the hd, the loading bar remains stucked there and the system doesn't start.  
![IMG_20201025_140458_329](https://user-images.githubusercontent.com/72854390/97108339-32b8a300-16cd-11eb-88aa-938914bace21.jpg)

**Comment by as005401** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/issues/198#issuecomment-711627019

**Comment by keke-cute** [comment]
> #198 (comment)

worked,thank you !

**Comment by johnnync13** [comment]
Try the last efi
