### ISSUE TITLE
Smartphones are not recognized as USB tethering during macOS Catolina installation

### ISSUE THREAD

**Issue by Rakleed** [johnnync13/Xiaomi-Mi-Air#203]
I am trying to install macOS Catalina 10.15.7 (19H2). But after booting into Recovery Mode and trying to start the installation, an error message appears stating that an Internet connection is required. Since I don't have a natively supported internet adapter, I decided to use my smartphone as a USB tethering.

I first tried this with an iPhone XR running iOS 14.1. I did everything as described in #113, except that I did not specifically add AX88179_178A.kext, since it was already added to the repository with a commit https://github.com/johnnync13/Xiaomi-Mi-Air/commit/28605b576ca01b96f52c19675d0eb85449f284c5. I tried both Clover and OpenCore, as well as version 7.6.8, and 7.6.7 (since I'm not completely sure if version 7.6.8 is only suitable for Big Sur, or is simply optimized for this version of macOS). I also tried connecting a USB stick and a USB tethering to different USB ports. And also, just in case, I checked that the Internet via a USB tethering works on a computer with Windows 10. But in any case, during installation, I got an error that I do not have an Internet.

Then I tried using the OnePlus 3 with Android 9 as a USB tethering. I added HoRNDIS.kext to the flash drive as stated in [README.md](https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/README.md#what-do-i-need). I have also tried with different versions, with Clover and with OpenCore, changing the USB ports for connecting the smartphone, but every time I enter Recovery Mode, open Terminal and write the command `sudo kextload -v /Volumes/BOOT/HoRNDIS.kext` I was getting the error `sudo: command not found`. To solve this problem, I tried [this solution](https://discussions.apple.com/thread/8653929), but I didn't have all those files anyway, so it didn't work. Perhaps this solution is generally not suitable for my case, but in [the issues in this repository](https://github.com/johnnync13/Xiaomi-Mi-Air/issues?q=is%3Aissue+sort%3Aupdated-desc+sudo%3A+command+not+found), I also did not find any similar questions.

Is the ability to use a smartphone as a USB tethering option currently working when installing macOS Catalina, or am I doing something wrong?

**Comment by yllwfsh** [comment]
Hi @Rakleed Thx for your detailed description.

I don't know if iPhone tethering works (never tested it) but Android tethering should work like you describe. Did you try the command without 'sudo'? This might have been a typo in the README.md

**Comment by Rakleed** [comment]
I forgot to mention that I tried this too. Now I tried to enter the `kextload -v /Volumes/BOOT/HoRNDIS.kext` command again, but in response I received the following error message:
`Requesting load of /Volumes/BOOT/HoRNDIS.kext.`
`/Volumes/BOOT/HoRNDIS.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8)`

I used the command `tail -f /var/log/system.log` to display sytem.log, but during the execution of the kextload command no entries appeared in it. I could not find kernel.log, and when I entered the log show command, I received an error that such command was not found (although this method is mentioned in the repository https://github.com/jwise/HoRNDIS).

**Comment by yllwfsh** [comment]
@Rakleed You need to adjust the path to the HoRNDIS.kext accordingly. This path is not valid apparently according to the error. If you've put it on a separate Fat32/ExFAT/MacOS Formatted USB stick the path would be for instance: `/Volumes/USBSTICK/HoRNDIS.kext`

**Comment by yllwfsh** [comment]
@Rakleed I can also highly recommend to either create the Installer USB via a real mac (or already setup hackintosh) or just getting a compatible USB network adapter to avoid this issue.

**Comment by Rakleed** [comment]
Indeed, my HoRNDIS.kext folder was in the BOOT/EFI/CLOVER/kexts/Other path, so when I now enter the
`kextload -v /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext` command, this error no longer appears. But now another error appears:
`/Volumes/BOOT/HoRNDIS.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8)`

.
> @Rakleed I can also highly recommend to either create the Installer USB via a real mac (or already setup hackintosh) or just getting a compatible USB network adapter to avoid this issue.

I'll take this into account, but at the moment I'm installing Hackintosh for the first time, I don't have a real Mac, and it's quite difficult to buy a natively supported USB Internet adapter in my area for a reasonable price.

**Comment by gmallios** [comment]
@Rakleed Try fixing the permissions for the HoRNDIS.kext using `sudo chown -R root:wheel /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext` or without sudo.

**Comment by Rakleed** [comment]
To find out the current permissions of a path, I wrote `ls -ld /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext` and got back:
`drwxrwxrwx 1 _unknown _unknown 2048 Oct 27 11:49 /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext`

Then I wrote the `chown -R root:wheel /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext` command without sudo, because I get the error `sudo: command not found` when I write the sudo command, and I got an empty line in response.

Then I wrote the `ls -ld /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext` command again, but the permissions were the same:
`drwxrwxrwx 1 _unknown _unknown 2048 Oct 27 11:49 /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kex`

So when I wrote `kextload -v /Volumes/BOOT/EFI/CLOVER/kexts/Other/HoRNDIS.kext`, I got the same error:
`/Volumes/BOOT/HoRNDIS.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8)`

**Comment by Rakleed** [comment]
@yllwfsh
> @Rakleed I can also highly recommend to either create the Installer USB via a real mac (or already setup hackintosh) or just getting a compatible USB network adapter to avoid this issue.

Any adapter with the AX88179 chipset will do? For example, will [this one](https://www.aliexpress.com/item/33061294878.html) fit?

**Comment by yllwfsh** [comment]
Hi @Rakleed yes any USB adapter with that chipset will do great. The one you suggested seems fine.

**Comment by johnnync13** [comment]
In installation kexts are not in ram

**Comment by Rakleed** [comment]
@johnnync13 so can I use my smartphone as USB tethering or not? If not, then information about this should be removed from README.
