### ISSUE TITLE
Full hibernation on Xiaomi....

### ISSUE THREAD

**Issue by darkleon78** [johnnync13/Xiaomi-Mi-Air#204]
Hi guys...
Is anybody make experiments with hibernation?
If I set hibernatemode=0 then only sleep mode is supported
If I set hibernationmode=25 then hibernation is works but sometimes Xiaomi load macOS with a green screen, where mouse pointer is works and it can be fixed by pressing for 1sec power button, display will off, and then by pressing any key laptop is show screen before hibernated and it's perfect return from full hibernation
I try to enable mode 3 to provide sleep mode for a couple of hours and then switch the laptop to full hibernation...
Maybe someone did any experiments?
Any info will be appreciated.

**Comment by darkleon78** [comment]
Hi
Good news. With help from my friend on Apllelife.ru finally, I've got that I want.
Now my Xiaomi AIR has a sleep mode and hibernation mode.
I provided some checking of ACPI patches... found some mistakes. Fixed it. Some patches were removed.
HibernationFixup latest version from the developer, who also helped me to fix the situation.
Now, what I have?
Sleep set to 5 min inactivity on battery mode, and 15 min from AC
Sleepdelayhigh and sleepdelaylow parameters set to 7200 sec (2 hours) for both modes (BAT and AC)
Poweroffdelay parameter to the same value.
How does it look?
Laptop after idle time goes to sleep mode.
The power is off. Led on the power button is blinking.
The laptop stays in this mode for sleepdelay time in seconds
During this time laptop stay in sleep mode. After that, it's power up and goes to hibernate mode till it will be powered on by a button
Some later I will provide small instruction how to do that.
Greets

**Comment by gmallios** [comment]
Would you mind posting your modifications or submitting a PR? 
Thank you.

**Comment by darkleon78** [comment]
Some delay... Just on testing... WIll post soon...

**Comment by johnnync13** [comment]
@darkleon78 you can do pull request
