### ISSUE TITLE
new airpotitlwm

### ISSUE THREAD

**Issue by davideakadudu** [johnnync13/Xiaomi-Mi-Air#207]
there's a new airportitlwm in alpha version. I tried it and it seems to me more performing than the old one.

**Comment by darkleon78** [comment]
Hi dude.
Are you talking about 1.2.0 alpha version?

**Comment by davideakadudu** [comment]
> Hi dude.
> Are you talking about 1.2.0 alpha version?

yes

**Comment by johnnync13** [comment]
Alpha is installed
