### ISSUE TITLE
Big Sur official release

### ISSUE THREAD

**Issue by davideakadudu** [johnnync13/Xiaomi-Mi-Air#209]
Hi guys, today maybe will be released the final release of Big Sur. Do you think the OC Efi in this GitHub will be fine to make a clean install of Big Sur Mac OS?
tx in advance

**Comment by changly** [comment]
Have you tried the official version of Big Sur today?

**Comment by changly** [comment]
> Hi guys, today maybe will be released the final release of Big Sur. Do you think the OC Efi in this GitHub will be fine to make a clean install of Big Sur Mac OS?
> tx in advance

Have you tried the official version of Big Sur today?

**Comment by johnnync13** [comment]
you can try the last version
