### ISSUE TITLE
imessage and app store don't work

### ISSUE THREAD

**Issue by heroiam** [johnnync13/Xiaomi-Mi-Air#21]
imessage and app store don't work. i'm using xiaomi air i5 version. tried every soluation in google. can imessage work in your xiaomi air?  are there any solutions to fix it?

**Comment by vimcaw** [comment]
I found a simple solution in an article but it is Chinese, you can translate it by google: 
[macOS黑苹果解决iMessage，FaceTime，iCloud最简单的方法，clover自制白 \- 为程序员服务](http://ju.outofmemory.cn/entry/374108)

**Comment by heroiam** [comment]
明白了，不是方法的问题，是账户出了问题，应该是被拉了黑名单，现在不让我登录
