### ISSUE TITLE
It was successfully run in big sur official version (11.0.1)

### ISSUE THREAD

**Issue by apiaoqzh** [johnnync13/Xiaomi-Mi-Air#211]
![image](https://user-images.githubusercontent.com/12195833/99081307-9152ac00-25fd-11eb-9ae4-213c3b563660.png)
本人头铁直接用系统自带的系统更新组件更新到bug sur。

**Comment by zazajin** [comment]
So can I use the latest release for Big Sur without going first Catalina and then update ?

I mean like : instant fresh Big Sur installation ?

**Comment by DokiOnjouji** [comment]
emmm I got a tips from  52pojie.com and found another "perfect Big Sur" for MiAir2018. Here's the [origin](https://www.52pojie.cn/thread-1281728-1-1.html)But I learn that Big Sur prevent kext from driving in a different way..but U jusu update from 15 and everthing goes well?

**Comment by chenkai0912** [comment]
> ![image](https://user-images.githubusercontent.com/12195833/99081307-9152ac00-25fd-11eb-9ae4-213c3b563660.png)
> 本人头铁直接用系统自带的系统更新组件更新到bug sur。

你是Clover引导吗？咋装啊，先更新EFI然后在线更新重启Install安装吗？我重启后选Install后，出现logo就无限重启，貌似引导不起来。请教你。

**Comment by johnnync13** [comment]
Try my last version
