### ISSUE TITLE
mi air reboots/crashes during installation

### ISSUE THREAD

**Issue by lastmethod** [johnnync13/Xiaomi-Mi-Air#213]
Hi , i have a mi air 20019 laptop and it keep crashes during installation ( the crashes are random )

any idea what should i do ?

Thanks a lot

**Comment by DokiOnjouji** [comment]
crash? check your SSD, maybe its a PM981 or PM981a

**Comment by lastmethod** [comment]
thanks for the replay ,

so if i install this one i will be fine ? 

 Samsung 250GB NVMe SSD 970 Evo Plus Series M.2 PCI-Express

**Comment by lastmethod** [comment]
@gmallios are you here ??

**Comment by gmallios** [comment]
Are you installing Big Sur or Catalina?

**Comment by lastmethod** [comment]
@gmallios thanks , i am trying to install catalina . i will have the samsung nvme tomorrow and try to install it again on it. is there any way to contact you to ask some questions ? ( i am also greek :P )

thanks
