### ISSUE TITLE
coping kexts into System/Library

### ISSUE THREAD

**Issue by lastmethod** [johnnync13/Xiaomi-Mi-Air#215]
Hi i have successfully installed catalina on my xiomi but i have one problem , i cant copy kexts filers into /System/Library/Extensions/ . I can run the system but the only problem i have seen so far is that the trackpad is not working properly (i did the clover installation ).

Thanks

**Comment by johnnync13** [comment]
Not copy kexts to library/extensions. This is deprecated

**Comment by lastmethod** [comment]
@johnnync13 Sorry i am new to mac and i lost you , i have to copy them to my users library/extensions ? rebuild it and then the trackpad will be ok ??

thanks for the response !
