### ISSUE TITLE
This causes Windows Fn + F4 / F5 or F4 / F5 to fail to adjust brightness

### ISSUE THREAD

**Issue by cuinchy3** [johnnync13/Xiaomi-Mi-Air#220]
The problem may be SSDT,this causes Windows Fn + F4 / F5 or F4 / F5 to fail to adjust brightness.
It fails if you boot with OpenCore but works fine if you boot with F12.

**Comment by johnnync13** [comment]
thank you! I will fix this on next update @cuinchy3

**Comment by cuinchy3** [comment]
> 谢谢！我将在下次更新@ cuinchy3时解决此问题

Thank you!Looking forward to your update

**Comment by cuinchy3** [comment]
@johnnync13 I found a solution to fix the problem：Disable SSDT-KBD0.aml,Rename _Q1C and Rename _Q1D(<true/> change to <false/>),and Enable the BrightnessKeys.kext.
[BrightnessKeys.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/5616394/BrightnessKeys.zip)

Maybe you have better way to solve this.

In addition,I hope you to update EFI based on the latest OpenCore example.

**Comment by cuinchy3** [comment]
I found a solution to fix the problem：
Disable SSDT-KBD0.aml,Rename _Q1C and Rename _Q1D,then Enable the BrightnessKeys.kext.
[BrightnessKeys.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/5616433/BrightnessKeys.zip)

Maybe you have better way to solve this.

In addition,I hope you to update EFI based on the latest OpenCore. @johnnync13

**Comment by changly** [comment]
How long is your boot time?

**Comment by johnnync13** [comment]
@cuinchy3 yes. I was going to do that. But if you want to make a pull request please!

**Comment by cuinchy3** [comment]
> @ cuinchy3是的。我打算那样做。但是，如果您要提出拉取请求，请！

i'm waiting for your next update,hahaha

**Comment by uwetrempelmann** [comment]
Hi,

thank you so much for your efforts!

I still have that problem with v7.7.2

**Comment by lolom68** [comment]
I have also the same issue on windows. Dualboot with open core 0.6.7 and v7.7.2.

**Comment by paranoiagu** [comment]
here is the merge request
https://github.com/johnnync13/Xiaomi-Mi-Air/pull/240

**Comment by johnnync13** [comment]
I don't have this laptop. I have new macbook pro M1

**Comment by yllwfsh** [comment]
> I no longer have this laptop. I have new macbook pro M1

Same here. So I cannot test things anymore unfortunately.
