### ISSUE TITLE
short battery life on Catalina 

### ISSUE THREAD

**Issue by Bixio999** [johnnync13/Xiaomi-Mi-Air#221]
I noticed that my battery doesn't last more than 2/3 hours even with low load. I used the bios scripts to get MacOS native battery management but I didn't notice any improvements than before. A new thing is that MacOS says I need to contact assistance for battery, but I don't know if this always happens because of Hackintosh or is really my battery that has an issue. I'm asking if someone had the same problems and if there is something I can do to improve the battery life. 

I'm currently running macOS Catalina 10.15.7 and using v7.6.7 EFI.
(I specify that I also used the bios script to get 64mb DVMT because I'm using a 4k monitor, idk if this can be relevant. Of course the battery life I'm mentioning above happens without monitor connected)

**Comment by changly** [comment]
This notebook has been used for a long time. My question is basically the same as yours

> I noticed that my battery doesn't last more than 2/3 hours even with low load. I used the bios scripts to get MacOS native battery management but I didn't notice any improvements than before. A new thing is that MacOS says I need to contact assistance for battery, but I don't know if this always happens because of Hackintosh or is really my battery that has an issue. I'm asking if someone had the same problems and if there is something I can do to improve the battery life.
> 
> I'm currently running macOS Catalina 10.15.7 and using v7.6.7 EFI.
> (I specify that I also used the bios script to get 64mb DVMT because I'm using a 4k monitor, idk if this can be relevant. Of course the battery life I'm mentioning above happens without monitor connected)

This notebook has been used for a long time. I basically connect the power adapter to use it. If the power adapter is not available, it can take 2 to 3 hours

**Comment by gmallios** [comment]
@Bixio999 If you have a windows installation you can use BatteryInfoView ( or Coconut Battery on MacOS) to see your battery health. If your battery health is low, you can try calibrating it. If that doesn't fix it, you will have to replace it which is easy on this laptop.

**Comment by Bixio999** [comment]
@gmallios Thanks, I used both BatteryInfoView on Windows and CoconutBattery on MacOS and they report the battery Health to 70%. Actually I don't know if the battery is really that consumed or it just need a Calibration, but I will try. 
I have not seen yet the bios settings, but is there an option in it to perform the battery Calibration or should i have to use a third party app?

**Comment by YuHayring** [comment]
This problem is caused by Apple inc.
I had used an MacBook Air with 0% battery life last mouth. Macintosh (Apple inc)  limits the cpu speed in 0.9Ghz because of the low battery life.
The only one solution is to buy a new battery.

**Comment by spicytrance** [comment]
This is caused by the BD PROCHOT enabled. 
Running cinebench R23 while on AC, gives me a multicore score of 3400. This is the same on windows, while plugged in.
But running it on battery, it throttles down every "multicore" workload to 0.44Ghz (?) and the score is very low. 
Geekbench is giving me a lower multicore score than single-core on battery...
On windows we see a frequency of 1.8-2.0GHz, which is way better, and with BD PROCHOT disabled it goes up to the max frequency it gets. (multicore workload)
Any way to disable it via VoltageShift? it should be able to change MSR values.

**Comment by spicytrance** [comment]
Yes, changing the MSR value did indeed enable full power while on battery. 
![image](https://user-images.githubusercontent.com/58493397/102944449-1e213d00-44bb-11eb-83c9-e2d56e8f8620.png)

**Comment by darkleon78** [comment]
> Yes, changing the MSR value did indeed enable full power while on battery.
> ![image](https://user-images.githubusercontent.com/58493397/102944449-1e213d00-44bb-11eb-83c9-e2d56e8f8620.png)

Can you provide info how did you change MSR value?
I have the same situation on my AIR laptop
