### ISSUE TITLE
How long is your boot time?

### ISSUE THREAD

**Issue by changly** [johnnync13/Xiaomi-Mi-Air#222]
I am using big sur, but I feel that the boot time is relatively slow at about 30 seconds. I did not find the problem when I turned on-v. How long is the boot time?

**Comment by lavjamanxd** [comment]
If you are using itlwm as your wifi driver, you can expect slower boot times.

**Comment by changly** [comment]
> 如果您将itlwm用作wifi驱动程序，则启动时间可能会更慢。

Yes, I am using the itlwn driver, can it be solved only by disabling this?

**Comment by lavjamanxd** [comment]
maybe you can solve it by disabling autoconnect to wireless networks
