### ISSUE TITLE
macOS 11.1 already release,When will the next update be made？

### ISSUE THREAD

**Issue by cuinchy3** [johnnync13/Xiaomi-Mi-Air#223]
anticipation

**Comment by YuHayring** [comment]
I have updated successfully. 
You can try it

**Comment by cuinchy3** [comment]
> 我已成功更新。
> 你可以尝试一下

thank you

**Comment by cuinchy3** [comment]
> 我已成功更新。
> 你可以尝试一下

where is it?

**Comment by vimcaw** [comment]
I have been using macOS 11 for a while and have not encountered any problems, you can try it if want.
