### ISSUE TITLE
Bluetooth Big Sur connect MI Mouse

### ISSUE THREAD

**Issue by aurel5918** [johnnync13/Xiaomi-Mi-Air#224]
Hi, I admire your work!
I can't connect my MI Mouse to bluetooth, I'm using the latest version you offer.
Is there a solution ?
thank you.

**Comment by YuHayring** [comment]
run the following command in Terminal:

log show --last boot | grep IntelFirmware

Save the driver logs, opening an issue (in https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues ). If there are no logs, you should probably check your Bootloader, USB, BIOS, etc.

**Comment by darkleon78** [comment]
Hi. I tried to connect my Microsoft BT mouse 3600 and have no success. macOS displayed that the mouse connected and then disconnect. 
I tried to connect the original Apple magic mouse from my iMac and it works perfectly. So I think that macOS has some restrictions to 3rd party BT mouses probably...

**Comment by johnnync13** [comment]
try to report on intel bluetooth repo
