### ISSUE TITLE
SSD not showing up in UEFI mode

### ISSUE THREAD

**Issue by Athlon007** [johnnync13/Xiaomi-Mi-Air#227]
For the couple of days, I've been trying to make macOS boot up on its own. It does install fine, it runs perfectly off of USB media installer, but for whatever reason the EFI of macOS does not show up. I've been following the tutorial; I've tried also using the Clover from Deprecated folder; I've tried installing Clover straight from the internet - nothing worked.

I've installed macOS on second SSD - Samsung 860 Evo.

**Comment by johnnync13** [comment]
clover is not supported
