### ISSUE TITLE
Wireless doesn't work

### ISSUE THREAD

**Issue by ahaolee** [johnnync13/Xiaomi-Mi-Air#228]
use the 7.7.1 version, in settings of network , there is no WiFi option. reset nvram is ineffective, and reset network setting is ineffctive. this is my setting :
<img width="668" alt="image" src="https://user-images.githubusercontent.com/35681414/103964100-9400f600-5195-11eb-8de8-027f606fe391.png">

**Comment by spaceface777** [comment]
Try editing the OpenCore `config.plist` file (located in `/EFI/OC/config.plist`). 

Search for:
```xml
<key>SecureBootModel</key>
<string>Disabled</string>
```
and change that to:
```xml
<key>SecureBootModel</key>
<string>Default</string>
```

**Comment by ahaolee** [comment]
> Try editing the OpenCore `config.plist` file (located in `/EFI/OC/config.plist`).
> 
> Search for:
> 
> ```
> <key>SecureBootModel</key>
> <string>Disabled</string>
> ```
> 
> and change that to:
> 
> ```
> <key>SecureBootModel</key>
> <string>Default</string>
> ```

**Comment by geekjair** [comment]
@ahaolee hi, is your problem solved? I'm in the same situation as you
