### ISSUE TITLE
Reboot loop during installation of Big Sur

### ISSUE THREAD

**Issue by Bixio999** [johnnync13/Xiaomi-Mi-Air#229]
Hi, I was installing Big Sur from latest Catalina, but once the installer reached the second phase, it continues to reboot without completing the installation, leaving me without boot option for macOS. I tried to shut down completely the PC and restart but nothing has changed. 
Before starting the installation I changed the EFI version from 7.6.7 to 7.7.1. How can I solve?

**Comment by festo95** [comment]
I had the same issue and solved updating open core to 0.6.5 
I'm not an expert so the procedure I'll describe next could be imprecise but it worked for me...I simply downloaded the lastest version of open core and copied the missing file of the new EFI (empty folders from stock OC) form this 7.7.1 
I also updated Kext with kext updater

**Comment by Bixio999** [comment]
> I had the same issue and solved updating open core to 0.6.5 
> I'm not an expert so the procedure I'll describe next could be imprecise but it worked for me...I simply downloaded the lastest version of open core and copied the missing file of the new EFI (empty folders from stock OC) form this 7.7.1 
> I also updated Kext with kext updater 

Could you please share to me your EFI? I would save a lot of time and anxiety haha

**Comment by festo95** [comment]
https://mega.nz/file/iEJFxADT#WaDT8UwcqtRtOQFFDK-nM6pHg_hffY56dFzU74LyQS8

Here you are try it

**Comment by Bixio999** [comment]
I tried your EFI, and OpenCore boots. The problem is that macOS installer option is gone. Do you have any ideas how to solve? 

Can I ask what you exactly did to make the EFI with OC 0.6.5? Which file did you delete from stock OC? I tried to delete all except the essential files as OC guide shows [here](https://dortania.github.io/OpenCore-Install-Guide/assets/img/clean-efi.5f36d3ad.png) and then copy the missing files from my old EFI, but it didn't work and OC doesn't boot.

When you updated and had the issue, did you reinstall entirely macOS again and formatted, or you did the changes in EFI and completed the installation?

**Comment by festo95** [comment]
I did not delete anything from OC 0.6.5 EFI folder only added the missing files that were in my 7.7.1 EFI such as kext and media 

My problem maybe was a bit different, I could boot "Mac OS installer" which freezed like your but I also could boot "macOS" (the name I gave to my APFS partition) and run the un-updated operative system 

And in the end I'm really sorry but I don't know how to help you because basically I don't know how it works and don't wanna tell you something wrong
The only thing I could tell you if it doesn't boot OC read the error and google it

**Comment by Bixio999** [comment]
After a day waiting for downloads and installs, I finally managed to update to Big Sur. I had to clean install again Catalina and then do the update by using your EFI, and all went right! Thanks again! 😄

**Comment by BigKing33** [comment]
could you please repost the efi? i have the same problem
