### ISSUE TITLE
XMAKB3M0P1911 and XMAKB3M0P1A12 available on the official support site

### ISSUE THREAD

**Issue by fightforlife** [johnnync13/Xiaomi-Mi-Air#232]
I am not sure what is changed, but Installation was successfull

**Comment by MarFre22** [comment]
Hi @fightforlife,
Can you share the link please?
Thanks :)

**Comment by fightforlife** [comment]
The official support site is linked here:
https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/BIOS/BIOS_Archive/Official%20Xiaomi%20support.txt

Download is here:
https://www.mi.com/service/bijiben/drivers/13-air-8
https://cdn.cnbj1.fds.api.mi-img.com/mibook-drivers/BIOS/MarbleR8/BIOS_1911.zip

**Comment by fightforlife** [comment]
Dont install! BD ProcHot see4ms to be set at 60 C

**Comment by darkleon78** [comment]
Hi dude. Do you have any problems with frequency and performance while Geekbench doing tests and Xiaomi works on battery? Multicore performance seems to be disabled. Low score about 1000 and frequency dropped on 0.4Ghz.

**Comment by fightforlife** [comment]
New Version available: https://cdn.cnbj1.fds.api.mi-img.com/mibook-drivers/BIOS/MarbleR8/XMAKB3M0P1A12.zip

Installation successful, Didnt notice any change.

**Comment by johnnync13** [comment]
good news!

**Comment by c-chytoudis** [comment]
Any changelog for P1A12 ?

**Comment by fightforlife** [comment]
Now XMAKB3M0P1B13 is available. Installation went fine.

**Comment by c-chytoudis** [comment]
> Now XMAKB3M0P1B13 is available. Installation went fine.

Any changelog ?

**Comment by Lelo5657** [comment]
XMAKB3M0P1B13 CPU-Government dosen't work propperly with the 7500u - downgraded to MAKB3M0P100B - works best in my opinion!

**Comment by fightforlife** [comment]
> 

Also noticed problems with the speedshift epp on XMAKB3M0P1B13. Frequency would swwitch between 399mhz and 3390mhz.
I found some tools to open the bios by insyde. But I was not able to finde the differences yet.
