### ISSUE TITLE
Disable BIOS Power throttling limit PL1 PL2

### ISSUE THREAD

**Issue by fightforlife** [johnnync13/Xiaomi-Mi-Air#233]
Does someone know how to disable the powerlimit introduced in the newer BIOS versions by Xiaomi?
Throttlestop does change the correct registers in memory already known by other manufacturers. 
(1: FED159A0 and 2: FED159A4)   (78 in hex is 120 in dec, and 120/8 is 15W)
But the laptop does still throttle down to 15W after a around 10secs

3: Mabe this has something to do with FED15930 which is set to 00000078 which equals 15. But everytime I try to write a different values it is instantly back to 78.

![image](https://user-images.githubusercontent.com/5511687/106644822-e31b2a80-658b-11eb-8581-265804af2186.png)

**Comment by johnnync13** [comment]
I don't have this laptop anymore but you can change this value with modshell
