### ISSUE TITLE
Wifi doesn't work after sleep till I turn it of and on BigSur 11.1

### ISSUE THREAD

**Issue by Keylem** [johnnync13/Xiaomi-Mi-Air#234]
Whenever my laptop goes to sleep it trys to turn off wifi and when I open the lid it trys to connect to the wifi in a loop. Besides that wifi works just fine, but it is kinda annoying to turn it of and on manually. 
I have a 2017 model and I'm currently using BigSur 11.1 (w OpenCore)
How can I solve this issue? Or do you also have it? thanks

**Comment by johnnync13** [comment]
https://github.com/OpenIntelWireless/itlwm
