### ISSUE TITLE
Lags and high cpu usage on browsers Safari/Chrome/Firefox 

### ISSUE THREAD

**Issue by EvgenyHS** [johnnync13/Xiaomi-Mi-Air#239]
Hello, all the browsers on my PC are slow, when I scroll a website (YouTube, reddit, unsplash) the CPU usage is very high, up to 110% and the animation are choppy, is that because the i5 8250u is to old or not enough ram? On windows the same sites on chrome are good. Thanks.

PC - Mi notebook air 13.3 2018 i5 8520u 
OS - MacOS Big sur 11.2.3 (i had the same issue on Catalina)

**Comment by johnnync13** [comment]
use scrip cpufriend to generate cpu files
