### ISSUE TITLE
Updating OC

### ISSUE THREAD

**Issue by hongtm77** [johnnync13/Xiaomi-Mi-Air#242]
Hi, just a question. Can I manually update the Open Core (6.8.0)? If yes, how to update? Appreciate for a help

**Comment by lolom68** [comment]
I also tried it but it doesn't seems to work well. I had no more the same OS selection screen (canopy). 
Maybe the issue came from my plist.

**Comment by haisy2019** [comment]
Maybe you could found the EFI in website: bbs.pcbeta.com

**Comment by darkleon78** [comment]
If you want update OC to 0.6.8 version you need to update it by instruction on Opencore site. Also be sure that you update OCBinary data. Also instruction can be found on Opencore site. When all completed - on first reboot dont forget to clear NVRAM from opencore boot menu (hidden menu by pressing spacebar)

**Comment by hongtm77** [comment]
> If you want update OC to 0.6.8 version you need to update it by instruction on Opencore site. Also be sure that you update OCBinary data. Also instruction can be found on Opencore site. When all completed - on first reboot dont forget to clear NVRAM from opencore boot menu (hidden menu by pressing spacebar)

Hi, thanks for the info. I have tried to update this way, but it doesn't seems to work. it is not booting. I have to boot with a bootable usb into MacOS and change back the EFI in order to boot back normally

**Comment by maklore74** [comment]
> > If you want update OC to 0.6.8 version you need to update it by instruction on Opencore site. Also be sure that you update OCBinary data. Also instruction can be found on Opencore site. When all completed - on first reboot dont forget to clear NVRAM from opencore boot menu (hidden menu by pressing spacebar)
> 
> Hi, thanks for the info. I have tried to update this way, but it doesn't seems to work. it is not booting. I have to boot with a bootable usb into MacOS and change back the EFI in order to boot back normally

same problem, is there any user who can write a little guide?

**Comment by Xinyao0512** [comment]
> Hi, just a question. Can I manually update the Open Core (6.8.0)? If yes, how to update? Appreciate for a help

Download the latest version of OpenCore, replace the corresponding file, modify the config. Plist file, I have successfully upgraded to the latest version of OpenCore.

**Comment by hongtm77** [comment]
> > Hi, just a question. Can I manually update the Open Core (6.8.0)? If yes, how to update? Appreciate for a help
> 
> Download the latest version of OpenCore, replace the corresponding file, modify the config. Plist file, I have successfully upgraded to the latest version of OpenCore.

hi, thanks for the reply. may I know what have you done to the config.plist? I have done everything but no luck
