### ISSUE TITLE
Not working on 7200U

### ISSUE THREAD

**Issue by rootwhois** [johnnync13/Xiaomi-Mi-Air#243]
Thanks for your hard work. But it still now working on 7200U, macOS 12 beta1.

**Comment by johnnync13** [comment]
you should modify config.plist

**Comment by rootwhois** [comment]
It seems doesn't work... Which place should I modify?

**Comment by rootwhois** [comment]
Hi, I modified the boot args, and it works on 7200U.
But now is it will boot for among 5 minutes and pause at one place for a long while.

boot-args I modified:
`gfxrst=1 dart=0 vsmcgen=1 igfxonln=1 igfxonlnfbs=0x010203 -lilubetaall -v`

![image](https://user-images.githubusercontent.com/53112648/121763062-beebdd80-cb6b-11eb-9076-c27d978db651.png)

**Comment by rootwhois** [comment]
WIFI is working now on Monterey by using this kext: https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0-alpha/AirportItlwm-Monterey-v2.0.0-DEBUG-alpha-7214459.zip

**Comment by kojinmalia** [comment]
> you should modify config.plist

could you specify which part should be modified please?
