### ISSUE TITLE
Graphical issue on booting

### ISSUE THREAD

**Issue by festo95** [johnnync13/Xiaomi-Mi-Air#244]
I found the new version 7.7.4 a minor graphical issue on booting, it show text boot menù and not the images of disks

Anyway this is not absolutely a big problem and I really want to thank johnnync13 for his work, continued even if he sold the laptop (can you tell us if you plan to support this project in the future?),  my experience with 7.7.4 overall is great, it solved some problems like the Macos updates the did't show up before.
The only thing I did to make it usable is get the last itlwm wifi kext 1.3.0 stable to get the wifi work again ( on first boot the last kext doesn't worked for me)
tested on Big Sur 11.4

**Comment by johnnync13** [comment]
the last kext is for monterey
