### ISSUE TITLE
Cant boot into installation media, any ideas?

### ISSUE THREAD

**Issue by wilsonnkwan** [johnnync13/Xiaomi-Mi-Air#245]
Hi Johnny, love your work here. I used your version previously for catalina and recently want to uphrade to big sur. But faced with the problem that, once i load the installation media, it just display apple logo and stuck there forever. Same effect be it clover or oc. I am on the 1703 machine. Any ideas?

**Comment by hongtm77** [comment]
for Big Sur, most stable EFI is 7.7.2

**Comment by wilsonnkwan** [comment]
> for Big Sur, most stable EFI is 7.7.2

Hi hongtm77, I tried your advice, still stuck at the logo when I choose to boot from the installer media. 
Just curious if it is because of this, could it be the image i downloaded was from an M1 mac and it doesn't work?

**Comment by wilsonnkwan** [comment]
Guys, solved. It's the M1 mac. I redownloaded the image using the old hackintosh catalina and redo the USB drive, now works like a charm (except for the Airportitlwm, which I suspect it's because I need to download the specific Big Sur kext, have not tried. now just use the itlwm and heliport)
