### ISSUE TITLE
AirportItlwm.kext 1.3 Big Sur loaded but can’t get internet

### ISSUE THREAD

**Issue by wilsonnkwan** [johnnync13/Xiaomi-Mi-Air#246]
Hi, I managed to load the latest AirportItlwm.kext and I can see network but when I tried to connect, even after it says connected, I can’t seem to get an internet connection. Anyone seeing the same thing? Or if you made it work, how you did it?

**Comment by rootwhois** [comment]
You can open the internet settings and click the dhcp bottom to get your IP address .

**Comment by wilsonnkwan** [comment]
Guys, managed to fix it. what I did was tried connecting to it, once connected, it still doesn't have internet, i turned off and on the wifi in the system preference. when it reconnects to the network I wanted, it will get internet. I suspect it has something to do with the DHCP. Problem solved.
