### ISSUE TITLE
headphone not worked on mibookair 13.3 8250U

### ISSUE THREAD

**Issue by Omoinemie** [johnnync13/Xiaomi-Mi-Air#247]
no sound on headphone

**Comment by wilsonnkwan** [comment]
Just to confirm, got sound on Windows?

**Comment by Omoinemie** [comment]
Windows worked fine

**Comment by johnnync13** [comment]
do you apply the script?

**Comment by Heiwater** [comment]
Try to change the `config.plist` and find the `layout-id` from `3` to `27`,this may help

**Comment by YuHayring** [comment]
my layout-id is 30, its working fine
