### ISSUE TITLE
It takes more longer time to boot

### ISSUE THREAD

**Issue by wangsaiCool** [johnnync13/Xiaomi-Mi-Air#25]
Hi，
I update my kexts upto commit id 48b35c40e3a0f78693d2f9f4ec557977bad7479c.
Now it takes more longer time, about 5min, to boot up.

I would be grateful if anyone could give me some help.

**Comment by stevezhengshiqi** [comment]
Try to remove `SMCLightSensor.kext` and `SMCSuperIO.kext` because XiaoMi laptops do not have ambient light sensor, and also are not supported by `SMCSuperIO.kext`.

**Comment by vimcaw** [comment]
@stevezhengshiqi Thanks For Your Helping, but after removing those, It looks the same.

**Comment by wangsaiCool** [comment]
> Try to remove `SMCLightSensor.kext` and `SMCSuperIO.kext` because XiaoMi laptops do not have ambient light sensor, and also are not supported by `SMCSuperIO.kext`.

 @stevezhengshiqi 
Thx~ for ur help, but it seems that it doesn't work.

**Comment by stevezhengshiqi** [comment]
Thanks for reply. You guys can add -v boot argument to watch the line which the system gets stuck.

**Comment by vimcaw** [comment]
It appears this when stuck, appear one every other 60 seconds, the total is about 3 or 4 times: 
```bash
kextd stall[0], (60s): 'ApplePS2MouseDevice'
```
This is a photo,`kextd stall[0], (60s): 'ApplePS2MouseDevice'` locate the bottom. I'm sorry, but I don't know how to save the log of verbose mode.
![image](https://user-images.githubusercontent.com/21964227/57827385-b6cce280-77d9-11e9-9306-df95ba129017.png)

**Comment by stevezhengshiqi** [comment]
You can try to remove VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext and VoodooPS2Trackpad.kext. They are also redundant kexts that not useful for Xiaomi laptops.

**Comment by RAXEAL** [comment]
> You can try to remove VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext and VoodooPS2Trackpad.kext. They are also redundant kexts that not useful for Xiaomi laptops.

This worked, thx.

**Comment by vimcaw** [comment]
It booting up fastly now 😄, thanks for helping.

**Comment by wangsaiCool** [comment]
Amazing, it does work.
Thx~ you guys.
