### ISSUE TITLE
7.7.4 version I found several problems

### ISSUE THREAD

**Issue by knifead** [johnnync13/Xiaomi-Mi-Air#253]
7.7.4 version I found several problems
1. The GUI interface no longer works. I used propertree to adjust the pickmode, but it didn’t work. I simply adjusted it to the builtin mode. I guess that the GUI driver has not been updated. This is yet to be verified. I turned off showpick, so I don’t need it for the time being. on
2. USBinjectALL.Kext doesn't seem to work. I feel that USBports has changed its name and put it inside. I used it normally after replacing USBinjectALL.kext.
3. I replaced the network card with BCM94360CS2, but the Bluetooth cannot be recognized. It feels that it is a USB customization problem, so I need to use USBinjectALL to re-customize the USB ports.It has been resolved.

Now, it works normally in Mojave, translated by Google.

If there is the same situation, Bluetooth cannot be used, you can add me QQ, 1295302031, I send efi.

--------------------------------------------------------------------------------------------------------------------------------------------

7.7.4版本我发现了几个问题
1. GUI界面不再管用，我用propertree调整pickmode，但并不管用，索性我直接调整为builtin mode.我猜测是GUI驱动没有更新，这个有待验证，showpick被我关掉了，所以暂时用不上
2. USBinjectALL.Kext似乎不管用，感觉是USBports改了个名字放在里面，我在替换了USBinjectALL.kext后正常使用了.
3. 我把网卡替换成了 BCM94360CS2 ，但是蓝牙并不能识别出来，感觉是USB定制问题，所以需要使用USBinjectALL重新定制USB ports.这个定制已经解决了.

现在，它正常工作在Mojave，谷歌翻译所得。

如果有一样的情况蓝牙无法使用可以加我QQ，1295302031，我发efi.

**Comment by knifead** [comment]
Let's talk about the follow-up development

1. The usbports is normal after I upgraded to Catalina, and the Bluetooth is also recognized normally. The usbports I customized before cannot be used in Catalina, so it should only be applied to Mojave.

2. Airdrop between my devices is normal but not normal with M1 macbook air, BTW macbook air is my girlfriend's device, running on big sur. When it searches for me, it only shows the name, but no avatar. I don't know what the situation is, and I may need to study it again.

----------------------------------------------------------------------------------------------------------------------------------------------

来聊聊后续的发展

1.usbports 在我升级到Catalina之后是正常的，蓝牙也被正常识别出来，我之前定制的usbports在Catalina用不了，所以应该只适用于Mojave.

2.我的设备之间Airdrop是正常但和M1的macbook air不太正常，BTWmacbook air是我女朋友的设备，运行在big sur。当它搜索我时只会显示名字，但没有头像。我不太清楚啥情况，可能需要再研究一下。

**Comment by lifsux** [comment]
> 7.7.4 version I found several problems
> 
> 1. The GUI interface no longer works. I used propertree to adjust the pickmode, but it didn’t work. I simply adjusted it to the builtin mode. I guess that the GUI driver has not been updated. This is yet to be verified. I turned off showpick, so I don’t need it for the time being. on
> 2. USBinjectALL.Kext doesn't seem to work. I feel that USBports has changed its name and put it inside. I used it normally after replacing USBinjectALL.kext.
> 3. I replaced the network card with BCM94360CS2, but the Bluetooth cannot be recognized. It feels that it is a USB customization problem, so I need to use USBinjectALL to re-customize the USB ports.It has been resolved.
> 
> Now, it works normally in Mojave, translated by Google.
> 
> If there is the same situation, Bluetooth cannot be used, you can add me QQ, 1295302031, I send efi.
> 
> 7.7.4版本我发现了几个问题
> 
> 1. GUI界面不再管用，我用propertree调整pickmode，但并不管用，索性我直接调整为builtin mode.我猜测是GUI驱动没有更新，这个有待验证，showpick被我关掉了，所以暂时用不上
> 2. USBinjectALL.Kext似乎不管用，感觉是USBports改了个名字放在里面，我在替换了USBinjectALL.kext后正常使用了.
> 3. 我把网卡替换成了 BCM94360CS2 ，但是蓝牙并不能识别出来，感觉是USB定制问题，所以需要使用USBinjectALL重新定制USB ports.这个定制已经解决了.
> 
> 现在，它正常工作在Mojave，谷歌翻译所得。
> 
> 如果有一样的情况蓝牙无法使用可以加我QQ，1295302031，我发efi.

GUI 可以利用OCC的主题工具修复

**Comment by Lelo5657** [comment]
Updated OC to Version 7.3 (although when I check via Terminal It says Version 074)  - Picker works again everything else seems to work like before - I'm on Big Sur 11.6 and on the Mi NB Air 2017 7500U/150MX

For updating I used this Guide:
https://www.insanelymac.com/forum/topic/347035-guide-updating-and-maintaining-opencore-new-method/

If you like I can share my EFI with you! If you stay on Catalina you would have to change the AirportItlwm.kext to this one: https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0/AirportItlwm_v2.0.0_stable_Catalina.kext.zip

**Comment by hongtm77** [comment]
> Updated OC to Version 7.3 (although when I check via Terminal It says Version 074) - Picker works again everything else seems to work like before - I'm on Big Sur 11.6 and on the Mi NB Air 2017 7500U/150MX
> 
> For updating I used this Guide: https://www.insanelymac.com/forum/topic/347035-guide-updating-and-maintaining-opencore-new-method/
> 
> If you like I can share my EFI with you! If you stay on Catalina you would have to change the AirportItlwm.kext to this one: https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0/AirportItlwm_v2.0.0_stable_Catalina.kext.zip

Hi, yes. Can you share your EFI? I would like to try. Currently im running okay but airdrop is not working and sometimes bluetooth is buggy
