### ISSUE TITLE
Hi dude. Do you have any problems with frequency and performance while Geekbench doing tests and Xiaomi works on battery? Multicore performance seems to be disabled. Low score about 1000 and frequency dropped on 0.4Ghz.

### ISSUE THREAD

**Issue by Bryce85** [johnnync13/Xiaomi-Mi-Air#255]
I have the same problem, does anyone know how to solve it?

_Originally posted by @darkleon78 in https://github.com/johnnync13/Xiaomi-Mi-Air/issues/232#issuecomment-830778841_

**Comment by knifead** [comment]
1、降级bios，找到bios文件下的老版本bios，XMAKB3M0P100B.rar，解压得到一个[.exe]文件，修改里面的platform.ini文件[bios_version_check=1]为0，然后就可以降级bios
2、拆开你的电脑，拔掉电池，按住开机键10s后松开，开机你就会发现一切正常
3、如果你使用Windows，在设备管理器中删除后卸载一个大概叫做[firmware]的设备，删除[c:/windows/firmware]里面的[.fd]文件
---------------------------------------------------------------------------------------------------------------------------
1. Downgrade bios, find the old version bios under the bios file, XMAKB3M0P100B.rar, unzip it to get a [.exe] file, modify the platform.ini file inside [bios_version_check=1] to 0, and then downgrade bios
2. Disassemble your computer, unplug the battery, press and hold the power button for 10 seconds and then release it, you will find everything is normal when you turn it on
3. If you are using Windows, uninstall a device called [firmware] after deleting it in the device manager, and delete the [.fd] file in [c:/windows/firmware]

**Comment by Bryce85** [comment]
Vale, gracias por la información. Una pregunta: Donde se encuentra el archivo platform.ini y como lo modifico?. Me podrías especificar un poco mas ese proceso ?

**Comment by knifead** [comment]
Pasos
1. Descomprima el archivo XMAKB3M0P100B.exe, puede obtener un montón de archivos como este
2. Abra platform.ini, busque bios_version_check, cambie 1 a 0, guarde y cierre
<img width="303" alt="截屏2021-08-24 下午7 59 22" src="https://user-images.githubusercontent.com/59995673/130614413-3b7b0448-cb44-4a38-b418-955f8d8fdd8c.png">
<img width="406" alt="截屏2021-08-24 下午8 14 18" src="https://user-images.githubusercontent.com/59995673/130614504-b07f9f59-152c-40f0-8d15-ccecdb758968.png">
3. Ejecute H2OFFT_Wx64.exe como administrador
4. La computadora se reiniciará y degradará automáticamente la BIOS, y se apagará una vez finalizada.
5. Abra la cubierta posterior de la computadora, desenchufe el cable de la batería y el cable de carga y mantenga presionado el botón de encendido durante más de 10 segundos.
6. Ensamble la computadora, solo encienda su computadora

Atención
1. Todos los pasos se ejecutan en la última versión de Windows Professional Edition
2. Windows actualizará su BIOS, así que asegúrese de que Windows ya no actualice su BIOS
3. Después de la prueba, la desactivación y desinstalación de los dispositivos de firmware dejarán de ser válidas después de reiniciar, y no hay investigaciones sobre cómo resolver este problema.
---------------------------------------------------------------------------------------------------------------------------
Steps
1. Unzip the XMAKB3M0P100B.exe file, you can get a bunch of files 
2. Open platform.ini, find bios_version_check, change 1 to 0, save and close
3. Run H2OFFT_Wx64.exe as an administrator
4. The computer will automatically restart and downgrade bios, and shut down after completion

5. Open the back cover of the computer, unplug the battery cable and charging cable, and press and hold the power button for more than 10 seconds
6. Assemble the computer, just turn on your computer

Attention
1. All steps run on the latest version of Windows Professional Edition
2. Windows will update your bios, so make sure that windows no longer update your bios
3. After testing, disabling and uninstalling firmware devices will become invalid after restarting, and there is no research on how to solve this problem.
--------------------------------------------------------------------------------------------------------------------------
步骤
1、解压XMAKB3M0P100B.exe 文件，你可以得到这样的一堆文件
2、打开platform.ini，找到bios_version_check,将1改为0，保存并关闭
3、以管理员身份运行H2OFFT_Wx64.exe
4、电脑会自动重启降级bios，完成后关机
5、拆开电脑后盖，拔掉电池排线和充电线，长按电源键10秒以上
6、把电脑组装好，开机你的电脑就好了

注意
1、所有的步骤运行在windows专业版最新版本
2、windows会更新你的bios，所以一定要确保windows不再更新你的bios
3、经过测试，禁用和卸载固件设备在重启后会失效，暂时还没有研究如何解决这个问题

**Comment by Bryce85** [comment]
Muchisimas gracias @knifead . He conseguido solucionarlo gracias a ti.
Por si a alguien le pasa lo mismo y aplica esta solución os dejo por aquí un video que me ayudo a encontrar el archivo platform.ini
https://www.youtube.com/watch?v=svECr9hIDMk&t=186s

**Comment by Bryce85** [comment]
Hola, alguien sabe como hacer que la BIOS no se actualice? Hay alguna opcion en la BIOS o algún comando para bloquear las actualizaciones?

**Comment by darkleon78** [comment]
Hi dude. Easy solutiona is available
Just install SimpleMSR kext
You can download it from here https://drive.google.com/file/d/1HtCehMeLH-x8GL2nMS0nQNxe52RC_dSr/view?usp=sharing
BIOS must be UNLOCKED

**Comment by Lelo5657** [comment]
How can I check if my BIOS is unlocked? is there someone who has a unlocked BIOS version for the i7 7500u version?

**Comment by Bryce85** [comment]
> Hi dude. Easy solution is available
> Just install SimpleMSR kext
> You can download it from here https://drive.google.com/file/d/1HtCehMeLH-x8GL2nMS0nQNxe52RC_dSr/view?usp=sharing
> BIOS must be UNLOCKED

Gracias, me puedes detallar un poco como hacerlo?
