### ISSUE TITLE
Questions to people running Mojave (need help)!

### ISSUE THREAD

**Issue by kojinmalia** [johnnync13/Xiaomi-Mi-Air#256]
Hello, for various reasons i want to stay on Mojave. I can install it and use it BUT i got no trackpad support and wasn't able to make AirportITWLM (or even ITWLM+Heliport) working > By the way, same on Catalina, i could only get it to work on BigSur.

Of course i did try kext from various configs (2019, 2020 = when Mojave was the current) but no luck. Please tell me what's the last config i can use for Mojave WITH working trackpad (and ITWLM)? Same question for Catalina & ITWLM. Again, i'm asking people who run that version. Thanks!

**Comment by Lelo5657** [comment]
Hi - for WIFI you have to download the Mojave kext and replace it in the kext folder - here ist the link: 
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0
https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0/AirportItlwm_v2.0.0_stable_Mojave.kext.zip
I can't remember if I had touchpad support when installing (long time ago) but for sure I had it when installation was finished - maybe use a USB-Mouse for installing and check it afterwards. Do you have any experience modifying OC/EFI? Which cpu is in your model? Maybe I could modify an EFI for you and test the installer on my 7500u model ...
