### ISSUE TITLE
Which BIOS should we use? 

### ISSUE THREAD

**Issue by Lelo5657** [johnnync13/Xiaomi-Mi-Air#257]
I have an 2017 Version Mi 13 with the 7500U. Since Windows updated my BIOS im having a hard time with Clockspeeds and temp - BigSur and also in Windows. Also I would like to undervolt the cpu ... Has anyone here the expierience and knowledge to tell me which BIOS version should be used? 

kindest Lothar

**Comment by Lelo5657** [comment]
Downgraded to XMAKB3M0P100B ... now works like a charm - no insane fan noise when AC is plugged and normal clocks when on battery!

**Comment by hongtm77** [comment]
Hi, is this same with 7200U version? How do you downgrade the bios?
