### ISSUE TITLE
Voltage Unlock Script Working for Xiaomi Air 13.3, i5 7200u on XMAKB3M0P1B13

### ISSUE THREAD

**Issue by willxs** [johnnync13/Xiaomi-Mi-Air#259]
This is to let people to know that the script is working for the Xiaomi Air 13.3 (2017) and successfully enabled undervolting, even though my laptop is not specifically mentioned to the compatible in the readmes.

**Comment by sigmundai** [comment]
Yes it does^^ I ignored to read the reader. It is originally made for 8250U
> > does the script work for air 13 with 8250u?
> 
> 
> 
> I believe that's the one listed as compatible, in the readme.

**Comment by hongtm77** [comment]
Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?

**Comment by willxs** [comment]
I followed the instruction outlined in the Readme, however I was doing it on windows not too sure how it would go on macOS.

**Comment by sigmundai** [comment]
> Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?

hi, corevolts -0,1V works well on my laptop, with intel extreming tuning

**Comment by willxs** [comment]
> > Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?
> 
> hi, corevolts -0,1V works well on my laptop, with intel extreming tuning

I'm running -0.9v across the board, but I didn't spend much time tuning it.

**Comment by hongtm77** [comment]
> > Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?
> 
> hi, corevolts -0,1V works well on my laptop, with intel extreming tuning

Hi, thanks for the reply. I have downloaded the XTU, but for some reason the core voltage option is greyed out! I cant adjust anything. Any idea?

**Comment by sigmundai** [comment]
> > > Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?
> > 
> > 
> > hi, corevolts -0,1V works well on my laptop, with intel extreming tuning
> 
> Hi, thanks for the reply. I have downloaded the XTU, but for some reason the core voltage option is greyed out! I cant adjust anything. Any idea?

hi, that's why you need this script to unblock the voltage settings

**Comment by hongtm77** [comment]
> > > > Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?
> > > 
> > > 
> > > hi, corevolts -0,1V works well on my laptop, with intel extreming tuning
> > 
> > 
> > Hi, thanks for the reply. I have downloaded the XTU, but for some reason the core voltage option is greyed out! I cant adjust anything. Any idea?
> 
> hi, that's why you need this script to unblock the voltage settings

Hi, thanks for your quick response. Sorry for asking the noob question, may I know how can I find the script? thanks

**Comment by sigmundai** [comment]
> > > > > Hi, may i know how you undervolt your laptop? I have the same model running bigsur. Is it in the bios? Or?
> > > > 
> > > > 
> > > > hi, corevolts -0,1V works well on my laptop, with intel extreming tuning
> > > 
> > > 
> > > Hi, thanks for the reply. I have downloaded the XTU, but for some reason the core voltage option is greyed out! I cant adjust anything. Any idea?
> > 
> > 
> > hi, that's why you need this script to unblock the voltage settings
> 
> Hi, thanks for your quick response. Sorry for asking the noob question, may I know how can I find the script? thanks

It's very easy, just follow the Readme: https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS
In brief, download the scripts and open it with administrator
