### ISSUE TITLE
能用在I5上吗

### ISSUE THREAD

**Issue by hb2013** [johnnync13/Xiaomi-Mi-Air#26]
我用在I5 8250U上，发热严重。

**Comment by Kuparuysaka** [comment]
发热严重？你是什么工作模式，温度大概多少

**Comment by Turaiiao** [comment]
同问

**Comment by Turaiiao** [comment]
同问

**Comment by Kuparuysaka** [comment]
我已经测试过了，完美！ 电耗与发热都不错，触摸板支持所有收拾，XiaoMiYes！

**Comment by Turaiiao** [comment]
> 我已经测试过了，完美！ 电耗与发热都不错，触摸板支持所有收拾，XiaoMiYes！

那好。我就用这个EFI了。下午刚到的air

**Comment by Turaiiao** [comment]
> 我已经测试过了，完美！ 电耗与发热都不错，触摸板支持所有收拾，XiaoMiYes！

请问你是安装的哪个版本的系统？

**Comment by Kuparuysaka** [comment]
我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题

**Comment by Turaiiao** [comment]
> 我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题

Mojave 10.14.5 我测试了一下，不能进入安装界面。卡在进度条，应该是不支持 I5

**Comment by Turaiiao** [comment]
> 我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题

请问你的是 2019 款吗，会不会是 MX250 显卡没屏蔽的问题。

**Comment by hb2013** [comment]
我测试，安装10.14.5没问题。声音都有，只有一点可能不太好，有时发热严重。CPU 80
 
 
------------------ Original ------------------
From: "Turaiiao"; 
Date: 2019年6月20日(星期四) 晚上10:21
To: "johnnync13/Xiaomi-Mi-Air"; 
Cc: "hb2013"; "Author"; 
Subject: Re: [johnnync13/Xiaomi-Mi-Air] 能用在I5上吗 (#26)

 
 
我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题
  
Mojave 10.14.5 我测试了一下，不能进入安装界面。卡在进度条，应该是不支持 I5

**Comment by Turaiiao** [comment]
> 我测试，安装10.14.5没问题。声音都有，只有一点可能不太好，有时发热严重。CPU 80
> […](#)
> ------------------ Original ------------------ From: "Turaiiao"; Date: 2019年6月20日(星期四) 晚上10:21 To: "johnnync13/Xiaomi-Mi-Air"; Cc: "hb2013"; "Author"; Subject: Re: [johnnync13/Xiaomi-Mi-Air] 能用在I5上吗 (#26) 我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题 Mojave 10.14.5 我测试了一下，不能进入安装界面。卡在进度条，应该是不支持 I5 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问你是哪一年的Air啊。我试了好多个都没进入系统。

**Comment by hb2013** [comment]
> > 我测试，安装10.14.5没问题。声音都有，只有一点可能不太好，有时发热严重。CPU 80
> > […](#)
> > ------------------ Original ------------------ From: "Turaiiao"; Date: 2019年6月20日(星期四) 晚上10:21 To: "johnnync13/Xiaomi-Mi-Air"; Cc: "hb2013"; "Author"; Subject: Re: [johnnync13/Xiaomi-Mi-Air] 能用在I5上吗 (#26) 我安装的是10.13.5，你可以先试试10.14.x，可以的话请告诉我一下，10.13是百分百没问题 Mojave 10.14.5 我测试了一下，不能进入安装界面。卡在进度条，应该是不支持 I5 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 请问你是哪一年的Air啊。我试了好多个都没进入系统。

2018年的

**Comment by hb2013** [comment]
> 我已经测试过了，完美！ 电耗与发热都不错，触摸板支持所有收拾，XiaoMiYes！

你好，我安装的是10.14.5，有时CPU高达80度，键盘都觉得烫手，但有时候，正常，40，50度。80度时，也没打开太多。你说的电耗与发热都不错，CPU最高达到多少？有80度吗？如果温度正常，我也安装10.13.5试试。现在10.14.5，就是这个发热问题。或者你也可以安装试试。我看应该是变频了的
