### ISSUE TITLE
Bluetooth not working on Monterey

### ISSUE THREAD

**Issue by Lelo5657** [johnnync13/Xiaomi-Mi-Air#260]
Has anyone a solution to get the bluetooth working on monterey?

**Comment by darkleon78** [comment]
Hmm. I cant install Monterey. Can you provide your config.plist
All info about smbios not needed. 
thank you

**Comment by Lelo5657** [comment]
I will be back at home on Friday - I think also important are the updated kexts.

**Comment by Lelo5657** [comment]
The bluetooth is now half working - can connect to my nouse but for example I was only able once to connect to a bluetooth speaker - since then it's in the known devices list but I can't reconnect?!?!
I already asked Johnny if I could update the EFI here with mine

**Comment by Lelo5657** [comment]
Oh just realized that Johnny already forked the Repo - https://github.com/Lelo5657/Xiaomi-Mi-Air/tree/patch-1

**Comment by darkleon78** [comment]
Do you installed Monteray? If yes i am very insteresting in your configuration (if you using Opencore)
Thank you

**Comment by Lelo5657** [comment]
Yes I am - but im not sure if I can upload my EFI till friday

**Comment by darkleon78** [comment]
No problem. I have my own OC config which absolutely correct works with BigSur. But if i trying update it to Monterey its boot loop on second stage of update process…

**Comment by Lelo5657** [comment]
had the same issue so i Changed th EFI to my current one - you have at least to deactivate the IntelBluetoothInjector.kext - somehow this was also my main issue for updateing to monterey

**Comment by darkleon78** [comment]
Yes. I know about this option. But still no success. I've started updating to Monteray. After that maOS request reboot.
Then I saw standart updating progress bar... Reboot againg
And now boot always dropped. 
I installed OC 0.7.5
Advise all settings in config.plist but situation the same.
In DEBUG version with -v option boot halted and i see errors from CPUFriend and SMCProcessor that don't recognize my CPU. Something strange happened

**Comment by Lelo5657** [comment]
somehow it worked with my old EFI with IntelBluetoothinjector.kext disabled but i booted from an external USB - don't know how this makes an real difference but it workt - just you know - during updated the Laptop reboots quite a lot of times

**Comment by darkleon78** [comment]
Hey dude.
Finally, i got fixes in my EFI and successfully installed Monterey. 
Also, I have fixed the problem with Bluetooth. Now it's working. But now i have a strange problem - when macOS rebooted and i enter in opencore boot menu - my keyboard is not working....
Only long pressing on power button can fix this problem till 1st reboot of macos....
Very stange

**Comment by TedLIS** [comment]
> Hey dude. Finally, i got fixes in my EFI and successfully installed Monterey. Also, I have fixed the problem with Bluetooth. Now it's working. But now i have a strange problem - when macOS rebooted and i enter in opencore boot menu - my keyboard is not working.... Only long pressing on power button can fix this problem till 1st reboot of macos.... Very stange

Hey, can you show youre efi fixes please? I cant update to Monterey too. That would be great.

**Comment by SpaHuang** [comment]
bluetooth working in Monterey very well, you can use the bluetoolfixup.kext and remove intelbluetoothinjecter.kex.
