### ISSUE TITLE
Can't boot after Monterey update

### ISSUE THREAD

**Issue by mijanto** [johnnync13/Xiaomi-Mi-Air#261]
After updating EFI to 7.7.6 I was finally able to upgrade to Monterey, but now it's not booting, on the photo is progress bar after 30mins (first boot attempt to system after upgrade). I tried nvram cleaning, turning off SIP(it's great to have it in bootloader)).![IMG_20211107_185752.jpg](https://user-images.githubusercontent.com/36339954/140656503-9011174f-2fd0-4420-b110-68e6ca27af30.jpg)

**Comment by mijanto** [comment]
EDIT: Don't be scared if you see white fade around the screen, it just heats up, and display messes up. Let it cool down. This issue begin after 7.7.6. Mine went like that after next 15 mins.

**Comment by SpaHuang** [comment]
Disable IntelBluetoothInjector.kext. and use bluetoolfixup.kext

**Comment by Lelo5657** [comment]
Hi! I've updated the EFI to OC 7.6 and did the same changes to bluetooth as mentioned before - i was allowed to fork Johnny's repo so here is the link if anyone needs it https://github.com/Lelo5657/Xiaomi-Mi-Air/releases 
Still trying to figure out some strange issues on reboot and hibernation (concerning bluetooth and keyboard)
