### ISSUE TITLE
SSD not see when install Monterey in Disk Utility?

### ISSUE THREAD

**Issue by giusedm** [johnnync13/Xiaomi-Mi-Air#263]
Anyone help me?

**Comment by TedLIS** [comment]
Same

**Comment by giusedm** [comment]
idk because Big Sur work perfectly

**Comment by giusedm** [comment]
@johnnync13 have you idea od the problem?

**Comment by johnnync13** [comment]
No idea. Maybe https://github.com/acidanthera/OcBinaryData/tree/master

**Comment by Lelo5657** [comment]
Try the pre release https://github.com/Lelo5657/Xiaomi-Mi-Air

**Comment by giusedm** [comment]
What changed to johnny efi?

**Comment by Lelo5657** [comment]
Updated to OC 0.76 and fixed Bluetooth (see description) - with the IntelBluetoothInjector.kext activated somehow NVMEs are not detected - i realised that, because I've installed Windows a NVME and MacOS on a m2. SSD and when I was booting with IntelBluetoothInjector.kext activated I didn't see my (Windows-Partition) NVME in MacOS

**Comment by johnnync13** [comment]
you can do a pull request if you want @Lelo5657

**Comment by Lelo5657** [comment]
there is already a OPEN pull request for updating

**Comment by Lelo5657** [comment]
Thanks - I ll merge it in the evening when I'm back at my PC

**Comment by johnnync13** [comment]
You have not created the pull request correctly. You have requested a merge from my repository to yours. One question, have you updated the kexts to the latest version? The latest releases are only 3 days old. @Lelo5657

**Comment by giusedm** [comment]
if remove or disable intelbluetoothinjector or add bluetoolfix, in boot don't see the Monterey installer

**Comment by Lelo5657** [comment]
???? did you just try my EFI-Folder? Just edit the Serials in the config to fit yours and try it - don't forget to clear NVRAM!

**Comment by Lelo5657** [comment]
but are you trying a new install or a update?

**Comment by giusedm** [comment]
new install

**Comment by Lelo5657** [comment]
thats strange - because to try my EFI I always use an USB-Installer to boot from - but as I remember it is a BugSur one - I'll check at home if there is any difference ... did you take the EFI from the Pre-Release or just from the REPO?

**Comment by giusedm** [comment]
efi from pre-release

**Comment by giusedm** [comment]
i have the same problem in another pc, the 12,5" version Xiaomi air

**Comment by Lelo5657** [comment]
When get back home i'll create a new clean Monterey installer and try it!

**Comment by giusedm** [comment]
ok I'm waiting news

**Comment by johnnync13** [comment]
BlueToolFixup.kext this is not for intel...

**Comment by giusedm** [comment]
if I remove bluetooth kext I don't see Monterey installer in boot

**Comment by giusedm** [comment]
I think witch the two things are connected

**Comment by Lelo5657** [comment]
> BlueToolFixup.kext this is not for intel...
here there is the advice to use it for Monterey
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/295

**Comment by Lelo5657** [comment]
maybe disable all bluetooth related kext to install and try to reactivate it once it is installed?

**Comment by giusedm** [comment]
if I disable all bluetooth kext I don't see installer monterey in boot

**Comment by johnnync13** [comment]
Oh amazing! I didn't know it. Thanks! I don't have these laptops anymore. I only have the macbook pro m1 max.

**Comment by giusedm** [comment]
"only" ahahahahah gg bro

**Comment by johnnync13** [comment]
@Lelo5657 use this to generate the latest kexts. I upload a new version from blueeothtool and intelfirmware

**Comment by Lelo5657** [comment]
be careful - as far as I understood you shouldn't use Bluetool and injector together! can't test it now ...

**Comment by johnnync13** [comment]
yes! I know it. I disable it in opencore @Lelo5657  Try now @giusedm @Lelo5657

**Comment by johnnync13** [comment]
sorry the link is https://github.com/corpnewt/Lilu-and-Friends is a good script to build automatically for the last commit in master

**Comment by giusedm** [comment]
can you modify refi on Xiaomi 12,5

**Comment by johnnync13** [comment]
@giusedm done!

**Comment by Lelo5657** [comment]
So after testing your EFI:
WORKS:
- Bluetooth works and I can see my nvme so this is solved
DOESN'T WORK:
 - still when rebooting from MacOS keyboard is not responding to enter BIOS or choose drive in Picker - works again when MacOS is booted.
NEW MINOR BUG:
- before OC "boots"  following error shows up: "OCS: No schema for UI at 13 Index, context <Output>I"

After Updating your lastest EFI to OC 0.7.6 the Error disappears and the graphical interface of the Picker is back again. Also updated Rehab USB kext to last Version. Still the Keyboard issue is present.

now I will create a monterey installer and test your this EFI with it. With my BigSur installer it works like described.

**Comment by johnnync13** [comment]
Nice. yes i'm using oc configurator in mode development(0.7.6), so ocs error it's normal because oc files in github is 0.7.5.
The keyboard not working is strange. I have to investigate and read more details for this.
Keyboard is used by VoodooPs2. Maybe sst-x.aml need an update, i don't know...

**Comment by Lelo5657** [comment]
try this https://github.com/ic005k/QtOpenCoreConfig/releases/tag/20211204 - works like a charm for bug finding and updating

**Comment by johnnync13** [comment]
I should used other one. But it was closed. Thanks.
@Lelo5657 you have permission for do commits directly on this repository.

**Comment by Lelo5657** [comment]
![Picker](https://user-images.githubusercontent.com/73521872/141368975-0c6268c2-e9b1-44c5-aaab-25adbc07ffdc.jpeg)
![Installer](https://user-images.githubusercontent.com/73521872/141369008-baf945b7-bcfb-4230-a80c-3ed2468baa60.jpeg)
![HD-Utility-tool](https://user-images.githubusercontent.com/73521872/141369032-26898089-9357-43cf-acea-c0469dcabad1.jpeg)
![Volumes](https://user-images.githubusercontent.com/73521872/141369064-c7166ab7-b782-42cb-883a-c0baee860d1b.jpeg)

So works for me with my EFI - Installer shows up - NVMe and SATA SSD shows up - didn't install because I have it already installed ;)
I am afraid of messing around in your Repo so I would just upload it to my fork and create a release 1 - can you @johnnync13 integrate it to your repo?

**Comment by Lelo5657** [comment]
https://github.com/Lelo5657/Xiaomi-Mi-Air/releases/tag/v7.7.8a here is the EFI i used

**Comment by giusedm** [comment]
@Lelo5657 can you see the 12,5 Xiaomi EFI and see what not working?

**Comment by Lelo5657** [comment]
I can check the EFI with the updater if there are any errors, but I don't own the device so I cant test it ...

**Comment by giusedm** [comment]
Ok i test with my notebook, i have 12,5

**Comment by Lelo5657** [comment]
@giusedm: here is the Updated EFI - No Idea if it works ....
https://github.com/Lelo5657/Xiaomi-Mi-Air/releases/tag/v7.7.8b
