### ISSUE TITLE
Touchpad doesn't work 

### ISSUE THREAD

**Issue by yaoyuan188** [johnnync13/Xiaomi-Mi-Air#266]
Hi, the OC EFI works perfectly for most of the functions. 
But, I can not figure out why the touchpad doesn't work, while the keyboard works fine. 
Bluetooth mouse or keyboard also works.

**Comment by Lelo5657** [comment]
What OS Version are you working with? Did you reset the NVRAM?

**Comment by Lelo5657** [comment]
due to Bluetooth works i guess you are on Monterey?

**Comment by yaoyuan188** [comment]
oh, thanks. I tried this on High sierta... I guess that's the problem, not the right OS...
