### ISSUE TITLE
Moving from Clover v2.4k r4945 to latest OC 7.7.9 didn't work on Mojave 10.14.6

### ISSUE THREAD

**Issue by mikmikmik** [johnnync13/Xiaomi-Mi-Air#268]
I have a working Mojave on Clover v2.4k r4945 but want to update to at least Catalina and maybe Monterey (with Software update) so I thought I should try to change to latest OC first.
I tried replacing EFI folder with the latest release 7.7.9 containing BOOT and OC
but it's stuck on MI logo (although I can see OpenCore in bios boot order)
Should I try with an older OC or stick to Clover (I'm trying not to format the drive)?
Thanks

**Comment by Lelo5657** [comment]
OK so first you will habe Tod take the 7.7.4 EFI to work with Catalina and most Mojave

**Comment by Lelo5657** [comment]
Don't forget to clear nvram

**Comment by mikmikmik** [comment]
Thanks a lot @Lelo5657 I could boot Mojave with 7.7.4
Can I upgrade with Install macOS Catalina.app (I made it with a script to use for another computer)
System prefs > Software update have only Monterey, would it work?

**Comment by Lelo5657** [comment]
I was able to update to Monterey with a modified EFI - but I think for updating to Monterey you should use Johnny's newest EFI or my modified EFI - would be the first try release of my fork

**Comment by Lelo5657** [comment]
For update to Catalina stay with 7.7.4

**Comment by Lelo5657** [comment]
You can download Catalina installer in AppStore and try

**Comment by mikmikmik** [comment]
I'll update to Catalina, thanks. But you need a flashed usb with the new efi for the Monterey update... otherwise you can't boot. Or could you change the efi before reboot?

**Comment by mikmikmik** [comment]
Thanks i'm now running Catalina.
