### ISSUE TITLE
Hello, Can this be used in Mojave 10.14.5 ?

### ISSUE THREAD

**Issue by Turaiiao** [johnnync13/Xiaomi-Mi-Air#27]
Hello, Can this be used in Mojave 10.14.5 ?

**Comment by vimcaw** [comment]
Yes, It works well.

![image](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)

**Comment by Turaiiao** [comment]
> Yes, It works well.
> 
> ![image](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)

After I replaced the EFI folder, I went to the Clover flash screen, and then went directly to the installation interface. Would it be the problem of I5?

**Comment by Kuparuysaka** [comment]
> 是的，它运作良好。
> 
> ![图片](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)

hey my friend,My laptop now working on 10.13.5,and it works well,so i can update to 10.14,and still work well? i think it should be working perfect as 10.13.5,if you know. Thanks ! 💃

**Comment by vimcaw** [comment]
I used 10.14 only, and it works well, it's better to back up before updating cross a major version.

**Comment by vimcaw** [comment]
> > Yes, It works well.
> > ![image](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)
> 
> After I replaced the EFI folder, I went to the Clover flash screen, and then went directly to the installation interface. Would it be the problem of I5?

How did you install the system and EFI?

**Comment by Turaiiao** [comment]
> > > Yes, It works well.
> > > ![image](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)
> > 
> > 
> > After I replaced the EFI folder, I went to the Clover flash screen, and then went directly to the installation interface. Would it be the problem of I5?
> 
> How did you install the system and EFI?



> > > Yes, It works well.
> > > ![image](https://user-images.githubusercontent.com/21964227/59847620-98887280-9395-11e9-895e-623e576be64e.png)
> > 
> > 
> > After I replaced the EFI folder, I went to the Clover flash screen, and then went directly to the installation interface. Would it be the problem of I5?
> 
> How did you install the system and EFI?

Using 10.14.5 with clover, after successful transcription with transMac, replace the EFI folder with this repository.
