### ISSUE TITLE
Brightness Control

### ISSUE THREAD

**Issue by 0x47726567** [johnnync13/Xiaomi-Mi-Air#29]
Brightness control doesn't appear to work on the latest EFI. No option in Display Settings and brightness keys don't work.

**Comment by ailuoku6** [comment]
me too

**Comment by vimcaw** [comment]
After updating to the latest, brightness control still doesn't work to me.

**Comment by 0x47726567** [comment]
Yeah, me too. I also tried another patched PNLF but i couldn't get brightness control to work.
