### ISSUE TITLE
Sonoma

### ISSUE THREAD

**Issue by mannii66** [johnnync13/Xiaomi-Mi-Air#290]
is there any possibility to update the Xiaomi air 13.3 2018 kaby lake from ventura to sonoma?

**Comment by 1nikolas** [comment]
we are waiting for stable update of the wifi driver. Everything else should work

**Comment by mannii66** [comment]
Anhang verfügbar bis 25.12.2023
Hello Nikolas, hello Johnny,

thanks for your email message. I am not a software developer and so I am very happy that people like you share your result with others. Only based on your given information and files it was be possible for me to get a running macOS on my xiaomi air 13.3 2018 laptop as dual boot together with Win11.

The last real good working macOS version for me was Ventura. To crash not my running macOS I tried an update to Sonoma on a clone of this Ventura on an external SSD. The update basically worked with problems because I thought I have to use the latest versions of EFI files. But this was wrong. After replacing some never ACPI files like SSDT-GPRW, SSDT-PMCR & SSDT-TPDO to the files from my working Ventura I solved the problems of non working trackpad & camera. Nevertheless on this stage bluetooth has not worked (at working Ventura also bluetooth is working fine). Only after replacing the kext files BlueToolFixup.kext, IntelBluetoothFirmware.kext, IntelBTPatcher.kext & IntelBluetoothInjector.kext (from aka80 user  of tonymacx86.com <http://tonymacx86.com/>) I got now a full function macOS Sonoma I think.

Attached you will find the EFI files of my Xiaomi air 13.3 2018 laptop for reference. Maybe you can check and use.

By the wy: both macOS versions Ventura & Sonoma does work with original Xiaomi air 13.3 2018 laptop WIFI hardware, no other hardware in use for working WIFI.

Best regards, Manfred

Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAWNm8q62hHhUNxmuYSY9-KMboPscAZyWi9NpJKRMl9sg_OrOp2iyPKpk%2F%24%7Bf%7D%3Fo%3DAm2AS-4z-pzGS93js16vAaWH4Ux_mW-Kf92RYcaVeEIO%26v%3D1%26x%3D3%26a%3DCAogGoArergHk2yozghBJ279dIDjeksxQU4a260W_GrUmSYSdhDP_bW0wDEYz42xiMoxIgEAKgkC6AMA_3Rrs-dSBBug-xxaBLI8qmRqJZp6CvjfZt2Xig-ndYD4R9nQjlGz6Coj_ah059EAcuXe5J8mL0lyJabnLaVSqOkhCMD0FaIFMWKDkv20GG72emyZgDwAA7j8WoU2uTs%26e%3D1703508985%26fl%3D%26r%3D22B77075-35B8-4F5A-BA74-372C28D28006-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DCFFEE6EB-8E63-421A-B258-CEC5FE496AF7%26p%3D148%26s%3Dqlz4muBD_Hnf4EfQWD3b9ARstOM&uk=S9uNKzajMsO_sTWRwlHtBQ&f=EFI%20sonoma.zip&sz=44360975>EFI sonoma.zip
44,4 MB

**Comment by sakib1361** [comment]
@mannii66 Would u please share the file again.

**Comment by mannii66** [comment]
file size is too big to upload. Please let me have email address to which I should send

**Comment by mannii66** [comment]
@sakib1361 have upload the EFI to wetranfer. You will get download link by email

**Comment by mannii66** [comment]
On my Xiaomi air 13.3 2018 kaby lake does run now macos sonoma 14.3

**Comment by sixunity** [comment]
> @sakib1361 have upload the EFI to wetranfer. You will get download link by email

hai could I have the link as well please?

edit: oops sorry forgot to add an address, you can send it to niks@mail.lv

**Comment by mannii66** [comment]
@niks@mail.lv: have upload the EFI to wetranfer. You will get download link by email

**Comment by lolom68** [comment]
> @niks@mail.lv: have upload the EFI to wetranfer. You will get download link by email

Hello is it possible to have the link too, please? lolom_1@hotmail.com

**Comment by lolom68** [comment]
> @niks@mail.lv: have upload the EFI to wetranfer. You will get download link by email

Hello, id it possible to get the link too please? lolom_1@hotmail.com

**Comment by MarFre22** [comment]
@mannii66 , Hi Thanks for your work.

It would be possible to share the EFI with me, please?
My email: git.chump909@passfwd.com

Thanks :)

**Comment by 1nikolas** [comment]
you dont need anything else for sonoma. Just get this repo and go though all the kexts to find their githubs and grab the latest version. Put the latest versions in the efi partition and then just do the update from settings. This is what I did and it worked
