### ISSUE TITLE
How to make Bluetooth work？

### ISSUE THREAD

**Issue by TIL-MICE** [johnnync13/Xiaomi-Mi-Air#3]
Hi, my notebook is XiaoMi air i7-8550u 8g 256gssd and which has fingerprint.
i guess we have same notebook,so i use this EFI file , every time when i try to start my notebook, it always reboot after pass the clover ui,
so, i delete the file in "patched/dsdt.aml" and problem sovled, but my bluetooth not work, is there sth need modify in DSDT.aml? 
thank you very much !

**Comment by johnnync13** [comment]
Bluetooth and wifi intel is not compatible with macOS
