### ISSUE TITLE
Brightness Control and Sleep on latest version 3.2 and 3.1

### ISSUE THREAD

**Issue by XYSheldon** [johnnync13/Xiaomi-Mi-Air#31]
Thanks for your work of running macOS on Xiaomi Notebook.

The **brightness control** does not work on v3.2 and v3.1.
In Release, v3.2 fixed brightness, but it seems not effective.
And brightness works on v3.0.

Besides, **Sleep** does not work. It only turn off the screen, and wake instantly after a keyboard press. The USB ports are stiil active in sleep state.

**Current OS Version: 10.15 Beta (19A487m)**
**Xiaomi Mi Air 13.3" 2018 CPU: Intel i7-8550U** 
![image](https://user-images.githubusercontent.com/35442887/60426907-326add80-9c28-11e9-9ebb-ac717f33c094.png)

Screenshot: System Preferences of Built-In Display

**Comment by 0x47726567** [comment]
I submitted a PR which fixes brightness. We will have to wait for it to get merged.

**Comment by ccsirer** [comment]
你的网速显示正确吗，我感觉下载速度显示不正确

**Comment by johnnync13** [comment]
I don’t have this laptop yet. Because m.2 nvme not accept wifi card

**Comment by johnnync13** [comment]
It is possible that it was not working because i put addpnlf on config.plist
