### ISSUE TITLE
ALCPlugFix_Xiaomi_Air_13_alc255Gen有什么用？

### ISSUE THREAD

**Issue by hb2013** [johnnync13/Xiaomi-Mi-Air#33]
替换EFI后，我看就可以了呀，ALCPlugFix_Xiaomi_Air_13_alc255Gen是有什么用，怎么使用

**Comment by XYSheldon** [comment]
内含有一个ALCPlugFix程序用于控制ALC类型声卡的CodecCommander
The folder contains a program called ALCPlugFix, which is designed to control the CodecCommander of your sound card.
运行Install.sh之后它将被复制到系统内作为后台服务运行
It runs as a system service at background after Install.sh executed.
它使得插拔耳机和休眠唤醒的时候能正常切换EAPD（外部音频放大器）
The program enable the regular behaviour of EAPD when you Plug/Unplug headphones and after wake from sleep.

相关中文文章，其中有这两节是相关的，希望能对你有所帮助：
 _CodecCommander 编解码器指挥官_ 
_ALCPlugFix能做什么?_
Here is a related Chinese blog.
[https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html](url)
