### ISSUE TITLE
Brightness key and Sound key don't work on v3.4

### ISSUE THREAD

**Issue by vimcaw** [johnnync13/Xiaomi-Mi-Air#34]
Brightness key and Sound key don't work on v3.4 but they can be adjusted in system preference.

**Comment by ccsirer** [comment]
有没有升级到 beta3的？

**Comment by webe0** [comment]
> 有没有升级到 beta3的？

试了一下直接升级，开机后就自动关机了，没能进入系统，用的是v3.3，v3.4也不行

**Comment by ccsirer** [comment]
看来 还要等大佬们放新的 efi才能升级

**Comment by webe0** [comment]
> 看来 还要等大佬们放新的 efi才能升级

确实，试了重新安装也不行
