### ISSUE TITLE
Keyboard and Trackpad doesnt work on Release 3.5 (i5 Model) 

### ISSUE THREAD

**Issue by 0x47726567** [johnnync13/Xiaomi-Mi-Air#35]

**Comment by vimcaw** [comment]
It's still don't work to me on the latest update (commit message: fix boot arguments).

**Comment by johnnync13** [comment]
Sudo kextcache-i /

**Comment by vimcaw** [comment]
> Sudo kextcache-i /

Thank you for help, unfortunately, the keyboard is still won't work and I get some invalid signatures (I use the latest Clover EFI):
![image](https://user-images.githubusercontent.com/21964227/60776705-aba28d00-a160-11e9-8557-cd23d073e5a4.png)
