### ISSUE TITLE
The keyboard and touchpad are not working on Mojave (i5-8250u)

### ISSUE THREAD

**Issue by Lonsho** [johnnync13/Xiaomi-Mi-Air#36]

**Comment by Turaiiao** [comment]
If your computer is 2019 and ssd is sansung pm981, you should replace the ssd.

**Comment by Lonsho** [comment]
If CLOVER is used, the keyboard and touch pad cannot be used. If it is changed to EFIOC, it will be normal, but the shutdown will be turned into restart, and win10 cannot be switched in EFIOC. EFIOC will often lead to win10 blue screen, can not start.

**Comment by Lonsho** [comment]
my computer is xiaomi air 2018

**Comment by johnnync13** [comment]
I know the problem. is the buggy tgtbridge. Soon, when I have time, i change it to previous version patch

**Comment by johnnync13** [comment]
fixed
