### ISSUE TITLE
TouchPad doesn't work

### ISSUE THREAD

**Issue by helloforrestworld** [johnnync13/Xiaomi-Mi-Air#39]
Xiaomi air 1.3, touchPad doesn't work
![image](https://user-images.githubusercontent.com/28107509/61214992-0711e380-a73c-11e9-8349-0a7866f879a6.png)

how can i fix it? if you have some solution, please give me a hand!!
 plz, thx!

**Comment by johnnync13** [comment]
sudo kextcache -i /
