### ISSUE TITLE
Trackpad Random movements and bad patched

### ISSUE THREAD

**Issue by johnnync13** [johnnync13/Xiaomi-Mi-Air#4]

**Comment by YimeAli** [comment]
Hi, my notebook is the same as yours. My Majove's EFI is : https://pan.baidu.com/s/1aIOKxSZhngNW2mo5azZa3Q.
But, the EFI have three problems. 
1, When the touchpad moves, the mouse often jumps to the upper right corner of the screen.
2, Graphics card memory is only 1536M.
3, No sound after sleep.
We can communicate more.

**Comment by johnnync13** [comment]
I have the same problems.. @YimeAli

**Comment by YimeAli** [comment]
Sorry, I am not the original author of it. I just am a learner. And the original author seems to have no solution.
