### ISSUE TITLE
OpenCore Boot menu

### ISSUE THREAD

**Issue by rbotte** [johnnync13/Xiaomi-Mi-Air#40]
Opencore is getting in the way to be my number one, very very stabe, I don't mind not having graphical interface but when using opencore I don't get my windows startup disk option. Is there any way to fix or edit this ? I can only start windows if I force startup windows disk on BIOS.
Xiaomi i5'8250 with 2 sdds, one for each OS. Thanks

**Comment by johnnync13** [comment]
OpenCore is a beta bootloader. Wait for version release
