### ISSUE TITLE
触摸板不能用

### ISSUE THREAD

**Issue by Curtain2112** [johnnync13/Xiaomi-Mi-Air#41]
我是小米air 8250u 指纹版的 触摸板不能使用 执行了 sudo kextcache -i/命令了依旧无法使用触摸板

**Comment by Kuparuysaka** [comment]
可以用啊

**Comment by cqliyi** [comment]
我是小米Air 8550u 指纹版，3.0版本触摸板、音量、亮度可用，后续的版本都无法使用；

**Comment by dzxxdzy** [comment]
> 可以用啊
你也是指纹版吗

**Comment by Kuparuysaka** [comment]
> > 可以用啊
> > 你也是指纹版吗

我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？

**Comment by dzxxdzy** [comment]
> > > 可以用啊
> > > 你也是指纹版吗
> 
> 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？

据说蓝牙和WiFi无解，我用无线网卡，再装个驱动

**Comment by Kuparuysaka** [comment]
> > > > 可以用啊
> > > > 你也是指纹版吗
> > 
> > 
> > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> 
> 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
你是i5还是I7

**Comment by dzxxdzy** [comment]
> > > > > 可以用啊
> > > > > 你也是指纹版吗
> > > 
> > > 
> > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > 
> > 
> > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > 你是i5还是I7

i5

**Comment by Kuparuysaka** [comment]
> > > > > > 可以用啊
> > > > > > 你也是指纹版吗
> > > > 
> > > > 
> > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > 
> > > 
> > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > 你是i5还是I7
> 
> i5

是不是也是换了硬盘才装上的

**Comment by dzxxdzy** [comment]
> > > > > > > 可以用啊
> > > > > > > 你也是指纹版吗
> > > > > 
> > > > > 
> > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > 
> > > > 
> > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > 你是i5还是I7
> > 
> > 
> > i5
> 
> 是不是也是换了硬盘才装上的
对啊，原装的PM981据说也无解，就加了个EVO 860

**Comment by Kuparuysaka** [comment]
> > > > > > > > 可以用啊
> > > > > > > > 你也是指纹版吗
> > > > > > 
> > > > > > 
> > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > 
> > > > > 
> > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > 你是i5还是I7
> > > 
> > > 
> > > i5
> > 
> > 
> > 是不是也是换了硬盘才装上的
> > 对啊，原装的PM981据说也无解，就加了个EVO 860

我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。

**Comment by dzxxdzy** [comment]
> > > > > > > > > 可以用啊
> > > > > > > > > 你也是指纹版吗
> > > > > > > 
> > > > > > > 
> > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > 
> > > > > > 
> > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > 你是i5还是I7
> > > > 
> > > > 
> > > > i5
> > > 
> > > 
> > > 是不是也是换了硬盘才装上的
> > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> 
> 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。

你测试这个的时候可以使用手势吗？我现在用的EFI挺合适的，就是只能U盘引导进入系统，改成硬盘就不行，所以想试试这个

**Comment by Kuparuysaka** [comment]
> > > > > > > > > > 可以用啊
> > > > > > > > > > 你也是指纹版吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > > 
> > > > > > > 
> > > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > > 你是i5还是I7
> > > > > 
> > > > > 
> > > > > i5
> > > > 
> > > > 
> > > > 是不是也是换了硬盘才装上的
> > > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> > 
> > 
> > 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。
> 
> 你测试这个的时候可以使用手势吗？我现在用的EFI挺合适的，就是只能U盘引导进入系统，改成硬盘就不行，所以想试试这个

我用的时候一切完美，就wifi蓝牙独显不工作而已，其他没问题的

**Comment by dzxxdzy** [comment]
> > > > > > > > > > > 可以用啊
> > > > > > > > > > > 你也是指纹版吗
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > > > 你是i5还是I7
> > > > > > 
> > > > > > 
> > > > > > i5
> > > > > 
> > > > > 
> > > > > 是不是也是换了硬盘才装上的
> > > > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> > > 
> > > 
> > > 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。
> > 
> > 
> > 你测试这个的时候可以使用手势吗？我现在用的EFI挺合适的，就是只能U盘引导进入系统，改成硬盘就不行，所以想试试这个
> 
> 我用的时候一切完美，就wifi蓝牙独显不工作而已，其他没问题的

ok

**Comment by Turaiiao** [comment]
今天装这个和 10.14.6，触控板不能用。2019 款的 Air，硬盘换的是 Acer 128G

**Comment by Kuparuysaka** [comment]
> > > > > > > > > > > > 可以用啊
> > > > > > > > > > > > 你也是指纹版吗
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > > > > 你是i5还是I7
> > > > > > > 
> > > > > > > 
> > > > > > > i5
> > > > > > 
> > > > > > 
> > > > > > 是不是也是换了硬盘才装上的
> > > > > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> > > > 
> > > > 
> > > > 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。
> > > 
> > > 
> > > 你测试这个的时候可以使用手势吗？我现在用的EFI挺合适的，就是只能U盘引导进入系统，改成硬盘就不行，所以想试试这个
> > 
> > 
> > 我用的时候一切完美，就wifi蓝牙独显不工作而已，其他没问题的
> 
> ok

兄弟你测试了吗，ok不

**Comment by dzxxdzy** [comment]
> 今天装这个和 10.14.6，触控板不能用。2019 款的 Air，硬盘换的是 Acer 128G
机型一样，也是装了10.14.6，试了3.3和3.4  版本，触摸板可以用但键盘又不行，还有一个版本键盘触摸可以但不能调亮度

**Comment by dzxxdzy** [comment]
> > > > > > > > > > > > > 可以用啊
> > > > > > > > > > > > > 你也是指纹版吗
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > > > > > 你是i5还是I7
> > > > > > > > 
> > > > > > > > 
> > > > > > > > i5
> > > > > > > 
> > > > > > > 
> > > > > > > 是不是也是换了硬盘才装上的
> > > > > > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> > > > > 
> > > > > 
> > > > > 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。
> > > > 
> > > > 
> > > > 你测试这个的时候可以使用手势吗？我现在用的EFI挺合适的，就是只能U盘引导进入系统，改成硬盘就不行，所以想试试这个
> > > 
> > > 
> > > 我用的时候一切完美，就wifi蓝牙独显不工作而已，其他没问题的
> > 
> > 
> > ok
> 
> 兄弟你测试了吗，ok不
还是有问题，哎

**Comment by Turaiiao** [comment]
大家可以尝试重建缓存

**Comment by cqliwei** [comment]
＃重复
@Turaiiao 能否描述下系统安装完成后需要执行的具体步骤和命令，感谢！
我现在用的EFI是3.0版本，后面的能进入系统，但按键都无反映，请教下。

**Comment by cqliwei** [comment]
> 大家可以尝试重建缓存

@Turaiiao能否描述下系统安装完成后需要执行的具体步骤和命令，感谢！
我现在用的EFI是3.0版本，后面的能进入系统，但按键都无反映，请教下。

**Comment by Turaiiao** [comment]
> > 大家可以尝试重建缓存
> 
> @Turaiiao能否描述下系统安装完成后需要执行的具体步骤和命令，感谢！
> 我现在用的EFI是3.0版本，后面的能进入系统，但按键都无反映，请教下。

你可以先加我的微信号。MCMenjoy

**Comment by fafafafaer** [comment]
> 今天装这个和 10.14.6，触控板不能用。2019 款的 Air，硬盘换的是 Acer 128G
> 机型一样，也是装了10.14.6，试了3.3和3.4 版本，触摸板可以用但键盘又不行，还有一个版本键盘触摸可以但不能调亮度

老哥你好，我想问下你的电脑有没有装网卡，现在状态怎么样，可以用吗，方便加个qq嘛，1526385776

**Comment by fafafafaer** [comment]
> > > > > > > > > 可以用啊
> > > > > > > > > 你也是指纹版吗
> > > > > > > 
> > > > > > > 
> > > > > > > 我大概是1月前测试一切正常的，那个时候应该是3.3版本吧。 兄弟你wifi怎么解决？
> > > > > > 
> > > > > > 
> > > > > > 据说蓝牙和WiFi无解，我用无线网卡，再装个驱动
> > > > > > 你是i5还是I7
> > > > 
> > > > 
> > > > i5
> > > 
> > > 
> > > 是不是也是换了硬盘才装上的
> > > 对啊，原装的PM981据说也无解，就加了个EVO 860
> 
> 我把981送人了，sata口加了个固态，想着nvme装个黑果免驱网卡，但上次买了个不能用也不知道那个网卡是不是坏的，想再买一个。

老哥你好，我想问问你的电脑有没有装网卡，现在可以用吗，方便加个qq嘛，1526385776
