### ISSUE TITLE
Swap Fn and Ctrl keys

### ISSUE THREAD

**Issue by bt** [johnnync13/Xiaomi-Mi-Air#45]
Is there a way I can replace the functionality of the Fn and Ctrl key on the left of the keyboard? Similar to the BIOS setting on Lenovo laptops.

This is to make the Mi Notebook more aligned with the keyboard style of the MacBook, where Fn is on the bottom left corner of the keyboard compared to Ctrl being on the bottom left.

**Comment by johnnync13** [comment]
here https://github.com/acidanthera/VoodooPS2 you can change the keys on config.plist
