### ISSUE TITLE
Nvme Issue

### ISSUE THREAD

**Issue by festo95** [johnnync13/Xiaomi-Mi-Air#48]
Hi, your work is awesome, I follow it since the beginning and I can tell you that I've faced an issue on the PCI express NVME where the ssd with the windows installation is located, every time I try to read (no write on NTFS) a big file like a video or an iso/dmg it goes in kernel panic, even if I try to copy those files, it doesn't happen on small files like documents
I renew my compliments for this project that let me use macOS without big problems

**Comment by johnnync13** [comment]
what is your ssd?

**Comment by festo95** [comment]
I have macOS on crucial MX500 on the second slot ssd, and I'm having issues with the NVMe that comes pre-installed on the laptop it's a Samsung Model MZ-VLB2560 that should be the OEM version of the 970

**Comment by johnnync13** [comment]
Of course, this is PM981.  It has problems with macOS. Change ssd to 970 evo or 970 evo plus with lastest firmware

**Comment by festo95** [comment]
Ok, sorry didn't know that
