### ISSUE TITLE
Could you please upload BIOS file

### ISSUE THREAD

**Issue by czg1997** [johnnync13/Xiaomi-Mi-Air#49]

**Comment by czg1997** [comment]
The forum has blocked BIOS topics. After using the files, the laptop just reboots before entering to desktop

**Comment by johnnync13** [comment]
What version have you been use?

**Comment by czg1997** [comment]
Hi johnny, thanks for your feedback. My laptop is gen 1. :)

**Comment by johnnync13** [comment]
Your laptop not supported by this repository. I have another repository for support your laptop
