### ISSUE TITLE
Bios whitelist on Nvme interface

### ISSUE THREAD

**Issue by xujianjie1213** [johnnync13/Xiaomi-Mi-Air#51]
Hi Johnny,

Saw your threads on different forums for bios mod. Any update regarding the bios? I am thinking about why Mi Air gen1 support the wifi card, but gen 2018 not. Is it possible that the Nvme interface in bios set as only support M2 mode, not PCIEX1 or PCIEX2?

**Comment by johnnync13** [comment]
exactly! I tried in the past to make a biosmod by modifying several parameters related to port nvme taking as reference the bios of the 1gen, but I am a beginner in this and I could not do it.I would be as interested as you
