### ISSUE TITLE
Can the readme.md contain more information?

### ISSUE THREAD

**Issue by wilsonnkwan** [johnnync13/Xiaomi-Mi-Air#54]
Hi, thank you for your help in providing support but I am at lost here. Your github contains multiple folders and I am not sure what are their functions or how to use them. A little bit of clarity would go a long way. Thanks

**Comment by johnnync13** [comment]
I don't have much time to complete more information because I study 4th Computer Engineering degree in this moment. I add video tutorial : https://www.youtube.com/watch?v=Pm5rPk7i41c&feature=youtu.be
