### ISSUE TITLE
Anyone managed to fix the imessage in this hackintosh? I am not sure if I should change the en0

### ISSUE THREAD

**Issue by wilsonnkwan** [johnnync13/Xiaomi-Mi-Air#56]
The typical fix of imessage requires us to align the mac address to the en0 but our en0 in this hackintosh is an internal loop with mac address 11:22:33:44:55:66. I am not sure the funciton of this internal loop en0. 

On theory, we need an en0 with a working internet connection to activate iMessage.

**Comment by johnnync13** [comment]
You should use clover configurator to assign new SMBIOS in config.plist

**Comment by wilsonnkwan** [comment]
How do I do that? got guides?
I tried generating new serial number and uuid and board serial number and i copied those to rt variable. but didn't work.
