### ISSUE TITLE
Restart it inexplicably.

### ISSUE THREAD

**Issue by Turaiiao** [johnnync13/Xiaomi-Mi-Air#57]
Hello, I'm 13.3 of 2019 model. Please tell me why I restart it inexplicably, and then it shows some problems. Is it the problem with the original 981 hard disk? I didn't remove it because there was a Windows 10 system in it.

**Comment by johnnync13** [comment]
It is possible. PM981 is incompatible with macOS.

**Comment by Turaiiao** [comment]
Thank you for your reply. Can I shield the 981 hard disk in Mac OS? You still have to uninstall it.

**Comment by Turaiiao** [comment]
> It is possible. PM981 is incompatible with macOS.

Thank you for your reply. Can I shield the 981 hard disk in Mac OS? You still have to uninstall it.
