### ISSUE TITLE
how to use the alcplugfix?

### ISSUE THREAD

**Issue by lifsux** [johnnync13/Xiaomi-Mi-Air#66]
how to use the alcplugfix?is there a tutorial?

""cp: ALCPlugFix: No such file or directory
cp: hda-verb: No such file or directory
cp: good.win.ALCPlugFix.plist: No such file or directory
chmod: /Library/LaunchDaemons/good.win.ALCPlugFix.plist: No such file or directory
chown: /Library/LaunchDaemons/good.win.ALCPlugFix.plist: No such file or directory
/Library/LaunchDaemons/good.win.ALCPlugFix.plist: No such file or directory
Done!""

**Comment by johnnync13** [comment]
sudo ./install.sh
