### ISSUE TITLE
Random reboot due to NVMe [Solved]

### ISSUE THREAD

**Issue by mikmikmik** [johnnync13/Xiaomi-Mi-Air#68]
Even though I didn't install Mojave on the stock NVMe, I had random reboot fatal error pointing to IONVMeFamily, Mojave is installed on a crucial m2 SATA in the second slot. For some reason it seems Mojave still uses NVMe and cause a fatal error, quite often.
Maybe it is spotlight that is checking the drive so you can add it to the ignore list.
I don't need the first drive in macOS so I just added the `nvme=-1` flag to boot, if it can help someone with the same issue.

**Comment by sunls24** [comment]
It is useful, thanks
