### ISSUE TITLE
Is it possible to use sidecar?

### ISSUE THREAD

**Issue by Creedowl** [johnnync13/Xiaomi-Mi-Air#72]
i have an ipad 2018 and try to use sidecar in 10.15. i connect ipad to laptop by wire and bluetooth, and login to the same icloud account, but cant find my ipad in setting. does this feature need wifi? my laptop uses cable network

**Comment by johnnync13** [comment]
to use sidecar needs cable type C to lightning.
By wireless or bluetooth still not working

**Comment by Creedowl** [comment]
that's a little inconvenient😥

**Comment by johnnync13** [comment]
Really, it's not my problem. Intel bluetooth is his first release and intel wifi still is not working

**Comment by Creedowl** [comment]
still thanks for your work👍 hope

**Comment by johnnync13** [comment]
Sure @Creedowl but is difficult to developer this. Patient
