### ISSUE TITLE
V5.6 Brightness Keys dont work any more

### ISSUE THREAD

**Issue by AlexRuck** [johnnync13/Xiaomi-Mi-Air#74]
Hey Johnny. 

Thank you for your hard work. It's really amazing how it works and for now also bluetooth is working with internal card. Thanks a lot for this.

I've just updated to your new Version and have figured out that the brightness keys dont work anymore.

Kind regards Alex

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v5.7

**Comment by AlexRuck** [comment]
Thank you. I've tried this but it did not work. I've also rebuild my kextcache but no change. The brightness keys don't work.
