### ISSUE TITLE
HDMI Kernel Panic

### ISSUE THREAD

**Issue by spicytrance** [johnnync13/Xiaomi-Mi-Air#75]
hey johnny, great work!!
everything seems to work, very stable. 
im just having a problem, my i7 air (2018) is getting a kernel panic every time i connect something over the HDMI port. i tried your last 4 releases, nothing worked... kexts in L/E, or even with injected kexts...

the mi pro EFI (https://github.com/daliansky/XiaoMi-Pro-Hackintosh) folder seems to work compared to yours. output works and no kernel panic. (but of course other things are broken)

here is the panic:

panic(cpu 4 caller 0xffffff800ec6520a): Kernel trap at 0xffffff7f91cff554, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x00000000000001dc, CR3: 0x0000000025e25000, CR4: 0x00000000003626e0
RAX: 0x2d2f0a0f96c600df, RBX: 0x0000000000000002, RCX: 0x0000000000010002, RDX: 0x0000000000000001
RSP: 0xffffff8123bb3e20, RBP: 0xffffff8123bb3ea0, RSI: 0x0000000000000001, RDI: 0xffffff8034778020
R8:  0x0000000000000001, R9:  0x0000000000000002, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0x0000000000000000, R15: 0xffffff803683d000
RFL: 0x0000000000010206, RIP: 0xffffff7f91cff554, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000000000001dc, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffff8123bb3880 : 0xffffff800eb3bb1b 
0xffffff8123bb38d0 : 0xffffff800ec733e5 
0xffffff8123bb3910 : 0xffffff800ec64e5e 
0xffffff8123bb3960 : 0xffffff800eae2a40 
0xffffff8123bb3980 : 0xffffff800eb3b207 
0xffffff8123bb3a80 : 0xffffff800eb3b5eb 
0xffffff8123bb3ad0 : 0xffffff800f2d24f9 
0xffffff8123bb3b40 : 0xffffff800ec6520a 
0xffffff8123bb3cc0 : 0xffffff800ec64f08 
0xffffff8123bb3d10 : 0xffffff800eae2a40 
0xffffff8123bb3d30 : 0xffffff7f91cff554 
0xffffff8123bb3ea0 : 0xffffff7f91cdcc7c 
0xffffff8123bb3ee0 : 0xffffff800f240ccd 
0xffffff8123bb3f30 : 0xffffff800f23f612 
0xffffff8123bb3f70 : 0xffffff800f23eb9c 
0xffffff8123bb3fa0 : 0xffffff800eae213e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelKBLGraphicsFramebuffer(14.0.3)[D660BE6F-E3A2-39D8-B9AC-3193DF203C9E]@0xffffff7f91caa000->0xffffff7f91ed5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1286D5E5-A6A1-3C44-A244-04C068903DB2]@0xffffff7f8f52f000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[3467C105-9354-3BD2-85F3-E5AEF94BD275]@0xffffff7f8f596000
            dependency: com.apple.iokit.IOAcceleratorFamily2(438.2.8)[9176E894-E24A-36BA-AFDA-0DB11F3F512A]@0xffffff7f91374000
            dependency: com.apple.iokit.IOReportFamily(47)[E3C37E96-3AFA-301F-B89C-719FB3D4DA53]@0xffffff7f8ff41000
            dependency: com.apple.AppleGraphicsDeviceControl(4.5.21)[EF326A60-9936-3267-A6E7-0044C7B4A952]@0xffffff7f90689000
            dependency: com.apple.iokit.IOGraphicsFamily(569.3)[7B5CA52B-0BD1-34AB-BFC9-7D5C3A0DBE7C]@0xffffff7f90345000

BSD process name corresponding to current thread: kernel_task
Boot args: gfxrst=1 darkwake=0 dart=0 

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x000000000e800000
Kernel text base: 0xffffff800ea00000
__HIB  text base: 0xffffff800e900000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 83246463568
last loaded kext at 6649477628: >AudioAUUC	1.70 (addr 0xffffff7f91b5b000, size 32768)
loaded kexts:
com.realtek.driver.RtWlanU1827	1827.4.b36
com.alexandred.VoodooI2CHID	1
com.zxystd.!I!BFirmware	1.0.0d1
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.0
com.alexandred.VoodooI2C	2.3
ru.joedm.SMCSuperIO	1.1.0
as.acidanthera.voodoo.driver.PS2!C	2.1.0
org.coolstar.VoodooGPIO	1.1
org.rehabman.driver.NullEthernet	1.0.6
as.vit9696.SMCProcessor	1.1.0
as.lvs1974.HibernationFixup	1.3.2
xyz.racermaster.NoTouchID	1.0.3
as.vit9696.!AALC	1.4.5
org.tw.CodecCommander	2.7.2
org.acidanthera.NVMeFix	1.0.0
as.vit9696.WhateverGreen	1.3.6
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.1.0
com.rehabman.driver.USBInjectAll	0.7.4
org.vanilla.driver.CPUFriend	1.2.0
as.vit9696.Lilu	1.4.1
com.alexandred.VoodooI2CServices	1
>AudioAUUC	1.70
@fileutil	20.036.15
@filesystems.autofs	3.0
@filesystems.msdosfs	1.10
>AGPM	111.4.1
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AHDAHardwareConfigDriver	283.15
>!AUpstreamUserClient	3.6.8
>!AHDA	283.15
>!AGraphicsDevicePolicy	4.5.21
@AGDCPluginDisplayMetrics	4.5.21
>!A!IPCHPMC	2.0.1
>!AHV	1
|IOUserEthernet	1.0.1
>eficheck	1
>!A!IKBLGraphics	14.0.3
|IO!BSerialManager	7.0.2f4
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>AGDCBacklightControl	4.5.21
>ACPI_SMC_PlatformPlugin	1.0.0
>!ABacklight	180.1
>!A!IKBLGraphicsFramebuffer	14.0.3
>!ASMCLMU	212
>!AFIVRDriver	4.1.0
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.13
@private.KextAudit	1.0
>!ATopCaseHIDEventDriver	3420.1
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.61.1
>!ASmartBatteryManager	161.0.0
>!AAHCIPort	341.0.2
>!AACPIEC	6.1
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AGraphicsControl	4.5.21
|IOAVB!F	800.17
>!ASSE	1.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!ABacklightExpert	1.1.0
|IONDRVSupport	569.3
>!ASMBusPCI	1.0.14d1
|IOAccelerator!F2	438.2.8
>!AHDA!C	283.15
|IOHDA!F	283.15
@!AGPUWrangler	4.5.21
@!AGraphicsDeviceControl	4.5.21
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBus!C	1.0.18d1
@plugin.IOgPTPPlugin	800.14
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>!AHS!BDriver	3420.1
>IO!BHIDDriver	7.0.2f4
>!AActuatorDriver	3420.2
>!AMultitouchDriver	3420.2
>!AInputDeviceSupport	3420.4
|IOGraphics!F	569.3
>!UAudio	320.49
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	7.0.2f4
|IO!BHost!CUSBTransport	7.0.2f4
|IO!BHost!CTransport	7.0.2f4
|IO!B!F	7.0.2f4
|IO!BPacketLogger	7.0.2f4
|IOSerial!F	11
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOAHCI!F	290.0.1
>!A!ILpssGspi	3.0.60
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSMBus!F	1.1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.60.3
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	800.14
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by johnnync13** [comment]
I don't have this laptop! Use Hackintool to fix this with 2048mb vram

**Comment by spicytrance** [comment]
What should i do in Hackintool? thanks for your response!

**Comment by johnnync13** [comment]
You have to see what port is activated when you plug

**Comment by HandKraft** [comment]
It's the same for me... there's a little trick you can use...

Download the latest version (currently 6.1) and put in the EFI all the files but change the config.plist to the version 4.6 (which was the last one where the HDMI worked correctly)... you will have all the updated improvements of the kexts and the HDMI working :)

It's a crappy fix, but it works...

If anyone knows of a better solution... please share it :)
