### ISSUE TITLE
HDMI Port

### ISSUE THREAD

**Issue by Notics-Seed** [johnnync13/Xiaomi-Mi-Air#78]
My Mi Air 13.3 
It's HDMI Port doesn't work.Everytime i plug in a  cable, it just reboots.
Please help. 
Thanks.

**Comment by Notics-Seed** [comment]
By the way, it's i7-7500U mx150 version

**Comment by HandKraft** [comment]
It's the same for me... there's a little trick you can use...

Download the latest version (currently 6.1) and put in the EFI all the files but change the config.plist to the version 4.6 (which was the last one where the HDMI worked correctly)... you will have all the updated improvements of the kexts and the HDMI working :)

It's a crappy fix, but it works...

If anyone knows of a better solution... please share it :)
