### ISSUE TITLE
The trackpad is not work.(opencore) 

### ISSUE THREAD

**Issue by knifead** [johnnync13/Xiaomi-Mi-Air#79]
The trackpad is not work.(opencore)

**Comment by knifead** [comment]
15.2，8250u

**Comment by knifead** [comment]
the bluetooth isn't work ( in clover)
and I find the oc is very faster than clover,
so I wish you can update the oc more usually.thx

**Comment by johnnync13** [comment]
There is a problem. Clover use tgt bridge but it cause problems. I will change the patches on open core

**Comment by timmmmmmmmm** [comment]
Same issue here with OC. Touchpad not working. Is this issue fixed in the latest version?

**Comment by yllwfsh** [comment]
Should be. I'm using OC and the latest version of the config and it should be working fine. 
If not:
1. Make sure there's no 'hackintosh' kexts in /Library/extensions
2. try resetting NVRAM and then reboot.
3. Do a 'sudo kextcache -i /' and then reboot

**Comment by timmmmmmmmm** [comment]
@yllwfsh thanks, I tried all suggested options but no luck. Anyway I had power/sleep issues with it too (maybe related to #88 ) so going to give a reinstall a try now.

**Comment by yllwfsh** [comment]
Yeah that's a sneaky one! In any case it's also good to check your OC plist for these settings, they've given me the best results (power management and sleep/wake):

![image](https://user-images.githubusercontent.com/43885719/74609544-51e94480-50eb-11ea-8746-a23fc7664c3d.png)

After that check with Intel Power Gadget if your CPU is using <1W and <1GHz in idle conditions:
![image](https://user-images.githubusercontent.com/43885719/74609557-86f59700-50eb-11ea-82c1-c129310f9aa4.png)
