### ISSUE TITLE
Keyboard not working anymore

### ISSUE THREAD

**Issue by uwetrempelmann** [johnnync13/Xiaomi-Mi-Air#80]
Hi Johnny
,
with 6.3 my keyboard is not working anymore (Kaby Lake 8550u).
After downgrade to 6.2 everything fine again, but of cause WiFi is missing.

Could you pls. give me a clue what I'm doing wrong with 6.3?

thanks in advance and cheeers from Germany,
  Uwe

**Comment by johnnync13** [comment]
Use OpenCore in v6.3

**Comment by johnnync13** [comment]
@uwetrempelmann the v6.4 fix keyboard

**Comment by knifead** [comment]
opencore，But it can't select the default startup item, it starts quickly, but there is no graphical interface, and you said that Intel's network card can be used, but I can't start it, I don't know if it is a problem with my settings, (Google Translate)

**Comment by Creedowl** [comment]
@johnnync13 I use clover with v6.4 and everything seems well. As you said in the readme that the intel wifi works, here is wifi in system report:
![image](https://user-images.githubusercontent.com/22554751/73748485-8593a880-4794-11ea-81f6-3543a5d5603a.png)
But in system preference, Internet I can't find where to use wifi. My system version is 10.15.2

**Comment by johnnync13** [comment]
@Creedowl @knifead wifi will work when I commit with the kext... At the momment I'm testing

**Comment by Creedowl** [comment]
@johnnync13 Waiting for that, it's really amazing. Thank you very much for your work

**Comment by johnnync13** [comment]
Here I wrote the instructions: 
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330

**Comment by uwetrempelmann** [comment]
Hi Johnny,

Keyboard is working fine now with 6.4/6.5.
Thank you so much for your lightning fast support!

cheers from Germany,
  Uwe
