### ISSUE TITLE
Questions about wifi

### ISSUE THREAD

**Issue by Creedowl** [johnnync13/Xiaomi-Mi-Air#81]
I try to load wifi, but it can't be opened like this
![image](https://user-images.githubusercontent.com/22554751/73810032-1d82a800-4810-11ea-93ff-88eba9df628c.png)

The following is what I did:
1. delete SSDT-DRP08.aml in clover/ACPI/patched/
2. I copyed IO80211Family.kext, both IO80211Family.kext and IO80211FamilyV2.kext, neither to /Library/Extensions and rebuild cache
3. follewed the Installation of AppleIntelWifi
4. rebuilt cache
5. reboot

But I still can't open wifi, is there anything wrong? My system version is 10.15.2 and use the newest EFI

By the way, I don't know what does the last line in wifi readme do: `Commands: sudo mv ./.kext /tmp sudo chown -R root:wheel /tmp/.kext sudo kextload /tmp/.kext`

**Comment by timmmmmmmmm** [comment]
I have a similar issue, and I tried to [improve the instructions a bit](https://github.com/timmmmmmmmm/Xiaomi-Mi-Air/blob/patch-1/WIFI/README.md). I didn't add any information though.

The last "command" section also confuses me. I altered the commands a bit so that I refer to the kext on my Desktop (from the previous commands), move it to /tmp, and then do the 'kextload' command. This resulted in my Wifi card listing the available networks around me. However I couldn't connect to my SSID (with WPA2) since the prompt tries to connect with it using WEP.

**Comment by Creedowl** [comment]
@timmmmmmmmm which IO80211Family.kext did you load or both? I load both of them, and when I try to load AppleIntelWifi.kext, wifi works and it can list the avaliable networks, but soon I got a system panic and reboot. Here is the system report
```text
panic(cpu 3 caller 0xffffff800c196b35): "Zone cache element was used after free! Element 0xffffff8037232800 was corrupted at beginning; Expected 0x8eefea5dfb21e233 but found 0; canary 0x711015ddcc02ca33; zone 0xffffff800caa5b20 (kalloc.2048)"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.61.1/osfmk/kern/zcache.c:658
Backtrace (CPU 3), Frame : Return Address
0xffffff812194afd0 : 0xffffff800c13bb1b 
0xffffff812194b020 : 0xffffff800c2733e5 
0xffffff812194b060 : 0xffffff800c264e5e 
0xffffff812194b0b0 : 0xffffff800c0e2a40 
0xffffff812194b0d0 : 0xffffff800c13b207 
0xffffff812194b1d0 : 0xffffff800c13b5eb 
0xffffff812194b220 : 0xffffff800c8d24f9 
0xffffff812194b290 : 0xffffff800c196b35 
0xffffff812194b2d0 : 0xffffff800c192c17 
0xffffff812194b400 : 0xffffff800c1487f4 
0xffffff812194b470 : 0xffffff800c686af8 
0xffffff812194b4a0 : 0xffffff800c48e280 
0xffffff812194b6e0 : 0xffffff800c486d32 
0xffffff812194bee0 : 0xffffff800c48649b 
0xffffff812194bf40 : 0xffffff800c79acba 
0xffffff812194bfa0 : 0xffffff800c0e3206 

BSD process name corresponding to current thread: SystemUIServer
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x000000000be00000
Kernel text base: 0xffffff800c000000
__HIB  text base: 0xffffff800bf00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 96348989130
last loaded kext at 83490614421: com.zhong.!A!IWiFi	1 (addr 0xffffff7f90224000, size 622592)
loaded kexts:
```

**Comment by Creedowl** [comment]
Another panic when I try to connect to a network
```text
panic(cpu 4 caller 0xffffff8012ad2e09): "os_refcnt: attempted resurrection (rc=0xffffff803ae12088)\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.61.1/libkern/os/refcnt.c:50
Backtrace (CPU 4), Frame : Return Address
0xffffff8127ac3be0 : 0xffffff801233bb1b 
0xffffff8127ac3c30 : 0xffffff80124733e5 
0xffffff8127ac3c70 : 0xffffff8012464e5e 
0xffffff8127ac3cc0 : 0xffffff80122e2a40 
0xffffff8127ac3ce0 : 0xffffff801233b207 
0xffffff8127ac3de0 : 0xffffff801233b5eb 
0xffffff8127ac3e30 : 0xffffff8012ad24f9 
0xffffff8127ac3ea0 : 0xffffff8012ad2e09 
0xffffff8127ac3eb0 : 0xffffff8012861538 
0xffffff8127ac3ee0 : 0xffffff80128fdb27 
0xffffff8127ac3f40 : 0xffffff801299acba 
0xffffff8127ac3fa0 : 0xffffff80122e3206 

BSD process name corresponding to current thread: mDNSResponder
Boot args: darkwake=0 dart=0 gfxrst=1 

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x0000000012000000
Kernel text base: 0xffffff8012200000
__HIB  text base: 0xffffff8012100000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 736919525908
last loaded kext at 717118267512: >!A!ILpssGspi	3.0.60 (addr 0xffffff7f964b5000, size 45056)
last unloaded kext at 272167247447: >!A!ILpssGspi	3.0.60 (addr 0xffffff7f94357000, size 45056)
loaded kexts:
```

**Comment by timmmmmmmmm** [comment]
I'm working on a Mojave installation so I did not install IO80211Family.kext.
Last thing I did is placing AppleIntelWifi.kext in my Library/Extensions folder and now I can't boot into MacOS anymore. This might be just a regular noobie 'Hackintosh mistake', but how do I revert this now without having to reinstall macOS (again)?

**Comment by YuHayring** [comment]
> I'm working on a Mojave installation so I did not install IO80211Family.kext.
> Last thing I did is placing AppleIntelWifi.kext in my Library/Extensions folder and now I can't boot into MacOS anymore. This might be just a regular noobie Hackintosh mistake, but how do I revert this now without having to reinstall macOS (again)?

Install "mac drive" in windows and you are access to explore the apfs partition.
delete the kext in /Library/Extensions , The AppleIntelWifi.kext is still a debug version ,so it couldn't appear in wherever  the kext can be loaded.You must load it with "kextload" or "kextutil" command in Terminal.

**Comment by YuHayring** [comment]
Commands: sudo mv ./.kext /tmp sudo chown -R root:wheel /tmp/.kext sudo kextload /tmp/.kext

把AppleIntelWifi.kext放在 /tmp目录下，
在应用程序里找到终端app，打开，执行这两行命令
sudo chown -R root:wheel /tmp/*.kext
sudo kextload /tmp/*.kext

**Comment by Creedowl** [comment]
> Commands: sudo mv ./.kext /tmp sudo chown -R root:wheel /tmp/.kext sudo kextload /tmp/.kext
> 
> 把AppleIntelWifi.kext放在 /tmp目录下，
> 在应用程序里找到终端app，打开，执行这两行命令
> sudo chown -R root:wheel /tmp/_.kext sudo kextload /tmp/_.kext

应该是少了个*号，加载后是可以加载wifi列表，但很快就五国重启了

**Comment by YuHayring** [comment]
> I have a similar issue, and I tried to [improve the instructions a bit](https://github.com/timmmmmmmmm/Xiaomi-Mi-Air/blob/patch-1/WIFI/README.md). I didn't add any information though.
> 
> The last "command" section also confuses me. I altered the commands a bit so that I refer to the kext on my Desktop (from the previous commands), move it to /tmp, and then do the 'kextload' command. This resulted in my Wifi card listing the available networks around me. However I couldn't connect to my SSID (with WPA2) since the prompt tries to connect with it using WEP.

The kext is still a debug version. There are many bugs to be fixed.
You will see that it is WEP but it actually is WAP2
It can only connect to the WAP2 with AES .

**Comment by YuHayring** [comment]
> > Commands: sudo mv ./.kext /tmp sudo chown -R root:wheel /tmp/.kext sudo kextload /tmp/.kext
> > 把AppleIntelWifi.kext放在 /tmp目录下，
> > 在应用程序里找到终端app，打开，执行这两行命令
> > sudo chown -R root:wheel /tmp/_.kext sudo kextload /tmp/_.kext
> 
> 应该是少了个*号，加载后是可以加载wifi列表，但很快就五国重启了

原帖地址在远景，这个kext还不稳定，暂时不能拿来用，等作者修复。
原帖地址：http://bbs.pcbeta.com/viewthread-1838489-1-1.html

**Comment by Creedowl** [comment]
> > > Commands: sudo mv ./.kext /tmp sudo chown -R root:wheel /tmp/.kext sudo kextload /tmp/.kext
> > > 把AppleIntelWifi.kext放在 /tmp目录下，
> > > 在应用程序里找到终端app，打开，执行这两行命令
> > > sudo chown -R root:wheel /tmp/_.kext sudo kextload /tmp/_.kext
> > 
> > 
> > 应该是少了个*号，加载后是可以加载wifi列表，但很快就五国重启了
> 
> 原帖地址在远景，这个kext还不稳定，暂时不能拿来用，等作者修复。
> 原帖地址：http://bbs.pcbeta.com/viewthread-1838489-1-1.html

还是很牛逼的，等作者更新

**Comment by johnnync13** [comment]
7a61aa7f2c2e78be4bc816fb20634a809e792c83 be patient!
