### ISSUE TITLE
Can you support other way of rewarding?

### ISSUE THREAD

**Issue by YuHayring** [johnnync13/Xiaomi-Mi-Air#83]
Most of users are Chinese like me, but we are not access to use Paypal.

**Comment by johnnync13** [comment]
@YuHayring what you use? WeChat?

**Comment by vimcaw** [comment]
@johnnync13 We use WeChatPay and AliPay, but our rewards may be a little small for you because Spain's GNI per capita is more than three times that of China in 2018 ([List of countries by GNI (nominal) per capita - Wikipedia](https://en.wikipedia.org/wiki/List_of_countries_by_GNI_(nominal)_per_capita)), our cost of living is also much lower.

**Comment by fafafafaer** [comment]
老哥🐂🍺

**Comment by Xinyao0512** [comment]
How do we donate to you by Alipay or WeChat Pay? Because we can't use PayPal in China.

**Comment by arthoes** [comment]
Can you help install macos?

**Comment by cly1998** [comment]
> How do we donate to you by Alipay or WeChat Pay? Because we can't use PayPal in China. @johnnync13

agree with

**Comment by johnnync13** [comment]
@cly1998 @YuHayring @Xinyao0512 @vimcaw my wechat is johnnync13

**Comment by johnnync13** [comment]
> Can you help install macos?

https://www.youtube.com/watch?v=FgJucJKbn2Y&feature=youtu.be

**Comment by vimcaw** [comment]
@johnnync13 Only WeChat account is not enough, you have to generate a QR code to receive payment, you can search the Tutorial.

**Comment by vimcaw** [comment]
@johnnync13 

This is a short tutorial: 

![](https://user-images.githubusercontent.com/21964227/89245570-ad78a180-d63b-11ea-840b-a3cd6bf3ab01.png)

Then choose `QR code to receive payment` (maybe, I don't know its official translation), you will see the UI like this:

![](https://user-images.githubusercontent.com/21964227/89245586-b79aa000-d63b-11ea-89a3-deab87341a8b.png)

Click `Save QR Code` and share the code to `README.md`.
