### ISSUE TITLE
Display brightness keys not working in Opencore config

### ISSUE THREAD

**Issue by yllwfsh** [johnnync13/Xiaomi-Mi-Air#84]
First of all thanks for your excellent work on this laptop! I also created an EFI folder before but yours is soo much better!!! Going to retire my project.

Using macOS 10.15.3 and version 6.5 of your EFIOC (opencore) folder. All kexts are also copied into /Library/Extensions, kextcache -i / performed.

Keyboard, trackpad, brightness slider in System Pref. all work but the brightness keys (F4 and F5) don't change the display brightness. Can't figure out why. Anything i'm doing wrong?

**Comment by timmmmmmmmm** [comment]
@yllwfsh your tutorial for installing it all is the best though. I used @johnnync13's EFI files, but your tutorial and got everything working apart from the wifi. Would be great if you're okay in merging some of your tutorial into this repo, I think it would help people a lot.

By the way I had no issues with the brightness buttons, are you sure you use the right combination with the fn key?

**Comment by yllwfsh** [comment]
> @yllwfsh your tutorial for installing it all is the best though. I used @johnnync13's EFI files, but your tutorial and got everything working apart from the wifi. Would be great if you're okay in merging some of your tutorial into this repo, I think it would help people a lot.
> 
> By the way I had no issues with the brightness buttons, are you sure you use the right combination with the fn key?

@timmmmmmmmm Thx for your nice words about my repo ;) I'll try to make a pull request for the tutorial. Are you using Clover or Opencore? In System Preferences->keyboard->shortcuts, do you have your display brightness set to keys F14 and F15 or something else? Did you put kexts in /System/Extensions or are you booting vanilla macOS? Thx

**Comment by yllwfsh** [comment]
This will be fixed by https://github.com/johnnync13/Xiaomi-Mi-Air/pull/85
