### ISSUE TITLE
BIOS patches?

### ISSUE THREAD

**Issue by yllwfsh** [johnnync13/Xiaomi-Mi-Air#88]
Regarding: https://github.com/johnnync13/Xiaomi-Mi-Air/commit/94455a1c88fc69f11362166995397c7d27c4d71b

I had no idea! That's very interesting. My laptop seems to boot fine with opencore without any mods though...

Can you teach us how to patch the BIOS and/or provide some scripts?

Thanks!

**Comment by yllwfsh** [comment]
I did a bit more research about the MSR 0x02 problem and if BIOS patching is necessary. First of all these are my relevant OC config.plist values:
![Screenshot 2020-02-14 at 10 16 44](https://user-images.githubusercontent.com/43885719/74517941-5955f580-4f13-11ea-82bc-1da9abbabae5.png)

After a quick test with Cinebench and Intel Power Gadget open it seems that native CPU power management is working:
![Screenshot 2020-02-14 at 10 12 08](https://user-images.githubusercontent.com/43885719/74518121-94f0bf80-4f13-11ea-9759-677a2d5cc9c8.png)
![Screenshot 2020-02-14 at 10 13 03](https://user-images.githubusercontent.com/43885719/74518134-9a4e0a00-4f13-11ea-9c18-656d63602def.png)

Also no problems with sleep/wake, all my devices are working.

@johnnync13 What's your opinion on this? Still necessary to patch BIOS? What would i gain in features?

**Comment by johnnync13** [comment]
It works better than you !!

**Comment by 0x47726567** [comment]
I think with Locked MSR and Clover/OC you use a community made frequency table which does not fully utilize power management and you lose performance and/or battery life. I think there is a MSR Unlock script from Cr0wTom but we need to test it.

**Comment by yllwfsh** [comment]
Ok sounds plausible but I cannot risk testing it at the moment on one of my main working machines. Anyone else volunteering? ;)

Btw, these Cr0wTom scripts are for the Notebook Pro, they might not work with the Notebook Air BIOS (plus several versions going around) ...

**Comment by 0x47726567** [comment]
I think @johnnync13 knows exactly which patches work and i'm willing to test them. I had terrible battery life on macOS ( 3-4 hours max ) and that's the reason i switched back to windows. I hope we can figure it out.

**Comment by johnnync13** [comment]
No use script of Xiaomi laptop pro. Every laptop is different

**Comment by 0x47726567** [comment]
I used the CFG unlock and DVMT patches on my Xiaomi Mi Air 13.3(2018) as i found its motherboard is the same (Timi1703) with the Xiaomi Pro one.

**Comment by timmmmmmmmm** [comment]
I'm happy to be the second person to test the patches @0x47726567 was mentioning. Would there be any effects on how Windows runs though? And most importantly @0x47726567, to which BIOS version did you apply the patches?

**Comment by 0x47726567** [comment]
I forgot to mention that i used [daliansky's ](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/BIOS/DVMT_and_0xE2_fix)BIOS patches because Cr0wTom's didn't work for me(there was a missing file?).I'm using XMAKB3M0P0100B bios.  Also, I haven't noticed any difference on Windows yet and i didn't expect anything to change in Windows.

**Comment by johnnync13** [comment]
In hackintool you have a test if you CFG Lock is unlocked and more parameters

**Comment by johnnync13** [comment]
if you follow open core tutorial to unlock cfg it's easy...

**Comment by johnnync13** [comment]
Anyone send me backup Bios P100C? I do script to add folder OpenCore shell

**Comment by johnnync13** [comment]
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/msr-lock

**Comment by johnnync13** [comment]
I have great news! https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen/issues/47

**Comment by johnnync13** [comment]
@yllwfsh @0x47726567 @elGiank @timmmmmmmmm anyone have the latest exe bios p100d?

**Comment by johnnync13** [comment]
@yllwfsh here is all laptops bios https://drive.google.com/drive/folders/1RIqdN3C9UDBN0KPwazyaerW1bEApivqN

**Comment by johnnync13** [comment]
@yllwfsh with this version, can you send me a backup?

**Comment by johnnync13** [comment]
I have been able to extract bios.
setup_var 0x3C 0x00 to unlock CFG Lock.
I will upload Excel with all Xiaomi laptops variables to unlock cfg and more things like enable speedshift, unlock mc lock etc
[Setup.txt](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4424319/Setup.txt)

**Comment by johnnync13** [comment]
@yllwfsh tutorial uploaded!!!!

**Comment by yllwfsh** [comment]
@johnnync13 Thx! I'm sorry i was not quick enough to respond yesterday. I'll have to make some time to try your instructions but it looks very simple so should be no issue!

**Comment by johnnync13** [comment]
@yllwfsh  I finished the tutorial. See on bios folder

**Comment by yllwfsh** [comment]
@johnnync13 Where did that latest BIOS version come from? Is there any improvements for the laptop? I'm really scared to update, afraid to brick my laptop again. I guess i'll try the cfg-lock first on my current BIOS.

**Comment by johnnync13** [comment]
@yllwfsh I always have the BIOS updated to the latest version

**Comment by yllwfsh** [comment]
Strange: When I try the Mod Grub Shell and enter setup_var 0x3C (without value to read the current state), I get 0x00 (disabled). But the verifyMSr2.efi says locked. What am I doing wrong?

**Comment by yllwfsh** [comment]
setup_var also tells me "expected a different size of the Setup value (got 1800 bytes) Continue with care..."

Is that the same for you?

**Comment by yllwfsh** [comment]
If you like here is my BIOS backup (made with flashrom in Linux):
[backup_XMAKB3M0P100B.bin.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4427346/backup_XMAKB3M0P100B.bin.zip)

**Comment by 0x47726567** [comment]
@yllwfsh In case i brick my laptop, how did u un-brick it?

**Comment by yllwfsh** [comment]
> @yllwfsh In case i brick my laptop, how did u un-brick it?

You won't like the answer ;)

Normally you have to use an EEPROM programmer and open the laptop to program the EEPROM directly...

In my case it didn't work and I had to use Xiaomi Warranty when I was on a business trip in China. They fixed it in the end...

**Comment by yllwfsh** [comment]
@johnnync13 (See my posts above for more info and my BIOS backup) I finally worked up the courage to just try it and typed setup_var 0x3C 0x00 and it gave me the following error:

error: can't set variable using efi (error: 0x000000000000008)

**Comment by lang-ji** [comment]
> @johnnync13 (See my posts above for more info and my BIOS backup) I finally worked up the courage to just try it and typed setup_var 0x3C 0x00 and it gave me the following error:
> 
> error: can't set variable using efi (error: 0x000000000000008)

I also got this error

**Comment by johnnync13** [comment]
@yllwfsh @lang-ji have you tried to modify bios lock and bios guard before to change CFG Lock?

**Comment by yllwfsh** [comment]
> @yllwfsh @lang-ji have you tried to modify bios lock and bios guard before to change CFG Lock?

No, didn't know I had to. I might give it a try later

**Comment by johnnync13** [comment]
@yllwfsh y will see if the Xiaomi pro has the same values from mi air to use recoding scripts..

**Comment by lang-ji** [comment]
> @yllwfsh @ lang-ji在更改CFG锁之前，您是否尝试过修改BIOS锁和BIOS保护？

![Uploading image.png…]()


> @yllwfsh I will see if the Xiaomi pro has the same values from mi air to use recoding scripts..



> > @yllwfsh @lang-ji have you tried to modify bios lock and bios guard before to change CFG Lock?
> 
> No, didn't know I had to. I might give it a try later



> @yllwfsh @lang-ji have you tried to modify bios lock and bios guard before to change CFG Lock?

![img](https://user-images.githubusercontent.com/23096078/78368805-c96d2780-75f6-11ea-9e5b-82a2604bd5da.png)

ohhh..Looks like it's already 0x00

**Comment by yllwfsh** [comment]
> ohhh..Looks like it's already 0x00

No it's not reading the proper value or it can't read the bios at all... See you got an error on the last line

**Comment by johnnync13** [comment]
@yllwfsh I upload another grub shell. Try this too

**Comment by terberes** [comment]
I have this error too

**Comment by yllwfsh** [comment]
> @yllwfsh I upload another grub shell. Try this too

No change. I've included a screenshot: 
![image](https://user-images.githubusercontent.com/43885719/78371050-c149c380-75c7-11ea-8c4c-6ad00ac15914.jpg)

Especially the readout for value 0xEC is weird: it says 0x02, but that's not possible, it should be 0 or 1. Maybe it's reading the wrong part of the BIOS for the settings?

**Comment by yllwfsh** [comment]
Here's my version of setup.txt extracted from my BIOS dump btw:

[setup.txt](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4427877/setup.txt)

**Comment by johnnync13** [comment]
I'm good news! The values from Xiaomi Mi air are the same from Xiaomi Pro
<img width="975" alt="Screenshot 2020-04-03 at 16 27 37" src="https://user-images.githubusercontent.com/22727137/78371483-52209f00-75c8-11ea-8713-e6253a866211.png">

**Comment by yllwfsh** [comment]
> I'm good news! The values from Xiaomi Mi air are the same from Xiaomi Pro
> <img alt="Screenshot 2020-04-03 at 16 27 37" width="975" src="https://user-images.githubusercontent.com/22727137/78371483-52209f00-75c8-11ea-8713-e6253a866211.png">

So we can just use daliansky's BIOS scripts then?

**Comment by johnnync13** [comment]
@yllwfsh I modified shell to do a bypass. 

[Scripts.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4427932/Scripts.zip)

**Comment by johnnync13** [comment]
@yllwfsh any news?

**Comment by 0x47726567** [comment]
> > I'm good news! The values from Xiaomi Mi air are the same from Xiaomi Pro
> > <img alt="Screenshot 2020-04-03 at 16 27 37" width="975" src="https://user-images.githubusercontent.com/22727137/78371483-52209f00-75c8-11ea-8713-e6253a866211.png">
> 
> So we can just use daliansky's BIOS scripts then?

Yup as i reported i used those patches and they worked. It was kinda risky though as i thought it was just a rebrand of the air series( i think they use both the Timi 1703 board )

**Comment by johnnync13** [comment]
@0x47726567 I fix coffee lake gaming with the same error, and CFG Lock now is unlocked

**Comment by johnnync13** [comment]
you should use the last release
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.0.3

**Comment by yllwfsh** [comment]
> The scripts on Xiaomi pro, I think that works on macOS

Just tested: Yes they do work, but only for 10 sec or so, then the CPU is back at 15W. The cooling can easily handle more though. It's hanging at 72 degrees C

There must be a BIOS value somewhere in there that we can tune ;)

**Comment by spicytrance** [comment]
Hey guys, how did you patch the bios? EFI shell cannot read/change the values. i flashed the bios version @johnnync13 put into 7.0.3. the scripts on windows broke my windows partition, and the ones on Mac dont change anything...

**Comment by yllwfsh** [comment]
> Hey guys, how did you patch the bios? EFI shell cannot read/change the values. i flashed the bios version @johnnync13 put into 7.0.3. the scripts on windows broke my windows partition, and the ones on Mac dont change anything...

I used the scripts from the daliansky repo: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/BIOS/DVMT_and_0xE2_fix

@johnnync13 Shall I include these scripts in your repo and write some README's?

**Comment by johnnync13** [comment]
You are free

**Comment by yllwfsh** [comment]
Thx. I'll work on it for a while now

**Comment by johnnync13** [comment]
I'm going to upload new bluetooth firmware and voodooi2c

**Comment by johnnync13** [comment]
We should look to change all SSDTs, for better compatibility with OC, and to be able to start windows.
```
Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0B)
                }
                Else
                {
                    Return (Zero)
                }
            }
```

**Comment by yllwfsh** [comment]
@johnnync13 Yes! Good idea. Would you like to do it or shall I look into it?

**Comment by johnnync13** [comment]
@yllwfsh I am researching. It turns out that SSDT-OSI is not compatible with OC, and it causes kernel panic at times, and disables boot with windows. This is fixed with the patch from before, but I don't know how to do it in several SSDTs because if you remove the trackpad it stops working because the SSDT-TPD0 is not well done, so I'm investigating.

**Comment by yllwfsh** [comment]
@johnnync13 Ok i'll research when I have some time. At the moment my trackpad is not working at all in macOS. Any tips? haha

**Comment by johnnync13** [comment]
Do you have connected battery? Battery shows? See if voodooinput is charged

**Comment by yllwfsh** [comment]
Yes the battery shows up. Btw i'm still on 10.14. Maybe that's different?

**Comment by yllwfsh** [comment]
I think it stopped working after i did the Security update 2020-2 this morning

**Comment by yllwfsh** [comment]
@johnnync13 Do we need both VoodooI2C and VoodooInput?

**Comment by johnnync13** [comment]
Yes. I Compile***Voodooi2c and now is needed voodooinput

**Comment by yllwfsh** [comment]
But which kext is actually doing the Trackpad? I think it's very confusing which depends on what now

We have:
VoodooI2C (I2C bus?)
VoodooI2CHID (For trackpad?)
VoodooInput (For multitouch)
VoodooPS2Controller (has trackpad kext inside)

**Comment by johnnync13** [comment]
no.
Voodooi2c, I2C
Voodooi2chid trackpad
voodooinput mT2 APPLE
voodoops2controller Keyboard.

Why not use the repository EFI?

**Comment by yllwfsh** [comment]
I'm trying the latest release right now

**Comment by yllwfsh** [comment]
But it doesn't work. No trackpad with OC and 10.14.6

**Comment by johnnync13** [comment]
Update to Catalina... why not?

**Comment by yllwfsh** [comment]
> Update to Catalina... why not?

Because Mojave is more stable i think and I don't need any of their new features. Besides, it should just be backwards compatible, right?

**Comment by johnnync13** [comment]
@yllwfsh No. Because voodoo input only works on 10.15

**Comment by yllwfsh** [comment]
As of version 1.0.1 they added support for previous versions:
![image](https://user-images.githubusercontent.com/43885719/78455427-9b432280-769e-11ea-95c7-3bc44be7e109.png)

**Comment by yllwfsh** [comment]
But i guess i can try on 10.15 as well, see if that fixes it

**Comment by johnnync13** [comment]
Okey! you can test Intel Wifi in 10.15 too

**Comment by yllwfsh** [comment]
@johnnync13 @spicytrance @terberes @lang-ji @0x47726567 @timmmmmmmmm 

BIOS modding howto is now uploaded: https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/BIOS

I'll close this one finally :)
