### ISSUE TITLE
Delete SSDT-XOSI and rewrite SSDT to fix Windows/Linux boot using OC

### ISSUE THREAD

**Issue by johnnync13** [johnnync13/Xiaomi-Mi-Air#89]
Change some SSDT to delete XOSI

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2.2.1

**Comment by johnnync13** [comment]
@yllwfsh may you tell me if this efioc works well?

**Comment by yllwfsh** [comment]
@johnnync13 I'll give it a try

**Comment by yllwfsh** [comment]
@johnnync13 It boots fine, but trackpad is broken

**Comment by johnnync13** [comment]
@yllwfsh  if you can send me a log https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/

**Comment by johnnync13** [comment]
@yllwfsh I think that it is very complicated to do if I don't have the laptop. Maybe I could modify XOSI to only works on macOS and no affected to others OS

**Comment by yllwfsh** [comment]
I booted twice, 721 is working configuration, 7221 is the latest, but without working trackpad
[release_7221.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4455916/release_7221.zip)
[release_721.zip](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4455918/release_721.zip)

**Comment by johnnync13** [comment]
thanks a lot @yllwfsh

**Comment by johnnync13** [comment]
try the last version @yllwfsh

**Comment by yllwfsh** [comment]
Boots, but still no trackpad unfortunately :(

**Comment by johnnync13** [comment]
@yllwfsh windows boot now works.. step by step

**Comment by johnnync13** [comment]
@yllwfsh try this release https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.2.3.1
Send me log and two screens of https://github.com/williambj1/GenI2C/releases/tag/v1.3.0 like
![Screenshot 2020-04-09 at 18 03 43](https://user-images.githubusercontent.com/22727137/78915929-f99c4680-7a8c-11ea-962e-78ff1797ebd4.png)
![Screenshot 2020-04-09 at 18 03 27](https://user-images.githubusercontent.com/22727137/78915935-facd7380-7a8c-11ea-8103-ad3f90cea192.png)

**Comment by terberes** [comment]
Tried last release, exactly the same, trackpad does not work.
<img width="592" alt="Screen Shot 2020-04-11 at 11 53 13" src="https://user-images.githubusercontent.com/24474728/79039607-12bb0980-7beb-11ea-8b51-4778619b686e.png">
<img width="592" alt="Screen Shot 2020-04-11 at 11 53 27" src="https://user-images.githubusercontent.com/24474728/79039608-151d6380-7beb-11ea-8a1f-f2a4d392dbf4.png">

**Comment by johnnync13** [comment]
@terberes i need a log. https://github.com/syscl/maclog With this.
Tutorial: http://bbs.pcbeta.com/viewthread-1839143-1-1.html

**Comment by terberes** [comment]
Ok, I'll send it soon

**Comment by west-shell** [comment]
https://github.com/n-d-k/OpenCorePkg
how about this one

**Comment by johnnync13** [comment]
@west-shell please do not comment other than the thread. If you are interested in that, do it yourself. thank you

**Comment by johnnync13** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.3.3

**Comment by paranoiagu** [comment]
Trackpad also does not work after i upgrade to  the build 7.3.3.
I the OpenCore bootloader.

**Comment by johnnync13** [comment]
@paranoiagu may you do the tutorial?
 http://bbs.pcbeta.com/viewthread-1839143-1-1.html

**Comment by terberes** [comment]
Here are my logs since last boot

[system.log](https://github.com/johnnync13/Xiaomi-Mi-Air/files/4466370/system.log)

**Comment by lang-ji** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.3.4.1

**Comment by johnnync13** [comment]
@lang-ji send me a log

**Comment by lang-ji** [comment]
> @lang-ji send me a log

Sorry,I don't know how to create the system log   (＞人＜；)
