### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by CamilloCorleone** [johnnync13/Xiaomi-Mi-Air#9]
I see you wrote Bluetooth is compatible (while WiFi is not).
Honestly on my Xiaomi Notebook Air 13.3" 2018 (i5-8250u version // Mojave 10.14.2) I can't see Bluetooth Icon in Preferences.
Are you sure Bluetooth is working? If yes, how did you manage to make it work? Is there something to change in Config.plist?

Thank you

**Comment by TIL-MICE** [comment]
not work, few month ago,i asked the same question ...

**Comment by CamilloCorleone** [comment]
> not work, few month ago,i asked the same question ...

So why is it said that it works? Maybe someone did the trick! :)

**Comment by TIL-MICE** [comment]
Maybe，but i can't find nothing about it,So i have to use a USB Bluetooth Adapter～

**Comment by CamilloCorleone** [comment]
@johnnync13 thank you for your work, can you explain how to make Bluetooth work?

**Comment by TIL-MICE** [comment]
> @johnnync13 thank you for your work, can you explain how to make Bluetooth work?

By the way, is your usb mouse' scroll wheel still work on Mojave 10.14.2 ？
just me have this problem？

**Comment by johnnync13** [comment]
Because, Xiaomi mi Air has a whitelist that can Read some m.2 components. I’m working to resolve this

**Comment by TIL-MICE** [comment]
So.It means you can find the BIOS of Mi Air 2018?

**Comment by TIL-MICE** [comment]
I'm not good at this. Good luck to you. I hope you can solve this problem successfully.

**Comment by johnnync13** [comment]
I hope so, but after exams
