### ISSUE TITLE
Bluetooth microphone can't use

### ISSUE THREAD

**Issue by handhackaaron** [johnnync13/Xiaomi-Mi-Air#93]
Thanks for your effort Johny, 10.15.3 Xiaomi air, cant use Bluetooth headphones as input.Hope this can be fixed. thanks

**Comment by paranoiagu** [comment]
Bluetooth headset also can not hear any sound when make wechat audio call.

**Comment by yllwfsh** [comment]
Bluetooth kexts have been updated in https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v6.7 Maybe this fixes your issues? If you use FileVault with OpenCore, please take note of this fix: https://github.com/johnnync13/Xiaomi-Mi-Air/commit/638baf6ac6195042ee81eca6f7910b7c5b576f49 ('Vault' should be set to 'Optional', not 'Secure')

**Comment by paranoiagu** [comment]
bluetooth headphones sound in and out is still not work, after update the v6.7 and the fix : 638baf6 .

**Comment by handhackaaron** [comment]
> been

**Comment by handhackaaron** [comment]
Updated BT kext, still same problem, when switch the input to BT microphone, system setting will hang for some time, and the microphone doesn't work, when switching back to laptop microphone, the input works.
