### ISSUE TITLE
An Internet connection is required to install macos

### ISSUE THREAD

**Issue by Andrea485** [johnnync13/Xiaomi-Mi-Air#95]
![15823119331462822863754270074614](https://user-images.githubusercontent.com/7497813/75063587-88f19880-54e5-11ea-8c86-7ce40aaa2926.jpg)
I follow the guide for Windows, whit gibmacos, but I have this error.

**Comment by yllwfsh** [comment]
You need a compatible (apple) usb ethernet adapter to install Catalina, or try creating the install usb from macOS
