### ISSUE TITLE
cat not boot to opencore, after the latest update 

### ISSUE THREAD

**Issue by paranoiagu** [johnnync13/Xiaomi-Mi-Air#96]
I can not boot to opencore after the commit : 9b2af2e1167df3bd399a52fa3f7d5ebc93406b86
here is the message:
> OCS: NO schema for Matchkernel at 4 index!
OCS: No schema for HatchKernel at 4 index!
OCS: NO schema for HatchKernel at 4 index!
OCS: NO schema for HatchKernel at 4 index!
OCS: NO schema for HatchKernel at 4 index!
OCS: NO schema for Natchkernel at 4 index!
OCS: NO schema for MatchKernel at 4 index!
OCS: NO schema for Matchkernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: NO schema for MatchKernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: NO schema for MatchKernel at 4 index!
OCS: NO schema for MatchKernel at 4 index!
OCS: NO schema for MatchKernel at 4 index! 
OCS: NO schema for MatchKernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: No schema for HatchKernel at 4 index!
OCS: No schema for HatchKernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: No schema for MatchKernel at 4 index!
OCS: NO schema for HatchKernel at 4 index!
OCS: No schema for MatchKernel at 8 index!
OCS: NO schema for MatchKernel at 8 index!
OCS: No schema for ThirdPartyTrim at 13 index!
OCS: Failed to parse string field of type 2
OCS: Failed to parse string field of type 2
Ocs: Failed to parse string field of type 1
OC: Configuration requires vault but no vault provided!

and I have enable the FileVault.

**Comment by yllwfsh** [comment]
Should be fixed with https://github.com/johnnync13/Xiaomi-Mi-Air/commit/638baf6ac6195042ee81eca6f7910b7c5b576f49

Please give us feedback if it's fixed now. Thanks!

**Comment by paranoiagu** [comment]
the bug is fixed. thanks.
