### ISSUE TITLE
About the OpenCore (some trouble）

### ISSUE THREAD

**Issue by HatsuneMiku-01** [johnnync13/Xiaomi-Mi-Air#97]
I had installed Catalina, it's good in clover. But when I want to use OC (OpenCore), it can't enter Mac OS. The code is "no vault provided!", I try to modify config.plist about "Misc → Security", make "RequireSignature = NO" and "RequireVault = NO", but I didn't find them. So, could you tell me how to do， thank you. @johnnync13

**Comment by yllwfsh** [comment]
This is already fixed in commit: https://github.com/johnnync13/Xiaomi-Mi-Air/commit/638baf6ac6195042ee81eca6f7910b7c5b576f49 (No release made yet)

(open your Opencore config.plist and find the option 'Misc'->'Security'->'Vault' and change it to 'Optional' instead of 'Secure')

**Comment by yllwfsh** [comment]
v6.7.1

**Comment by HatsuneMiku-01** [comment]
thank you !!!
