### ISSUE TITLE
About Prtscn

### ISSUE THREAD

**Issue by Notics-Seed** [johnnync13/Xiaomi-Mi-Air#99]
Would you please make the Prtscn a function key ？ I think it's useful. Thanks.

**Comment by vladdenisov** [comment]
On Mac there is another way to make screenshots. 
You can find out here more about it: https://support.apple.com/en-us/HT201361

**Comment by yllwfsh** [comment]
I agree with @vladdenisov 

Taking screenshots on macOS is normally done as suggested in the link by Apple
